<div class="menu">	
  <a href="<?= KUMBIA_PATH ?>credenciales/imprimirProvicional" onmouseover="toolTip('Imprime la credencial provisional de un alumno',this)" >Imprimir Provisional</a>
  &nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
  <a href="<?= KUMBIA_PATH ?>credenciales/actualizarDatos" onmouseover="toolTip('Actualiza los datos de un alumno',this)" >Actualizar Datos</a>
  &nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
  <a href="<?= KUMBIA_PATH ?>credenciales/generarReporte" onmouseover="toolTip('Genera el reporte de los alumnos solicitados',this)">Generar Reporte</a>
  &nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
  <a href="<?= KUMBIA_PATH ?>ventanilla/index" onmouseover="toolTip('Regresa al m&oacute;dulo de ventanilla',this)">Regresar</a>
<div>
