<?php
    header('Window-target: _blank');
	header('Content-type: application/vnd.ms-excel');
	header("content-disposition: attachment;filename=Reporte.xls");
?>
<center>
  <table style="width:100%; font-family:arial; font-size:12px; margin-top:10px; float:left; margin-bottom:80PX;" align="center" border=1>
	<tr style="font-weight:bold; color:#FFFFFF; text-align:center;" height="32">
	  <td bgcolor="#F7B64C" height="35px" width="131px">
		&nbsp;&nbsp;&nbsp;No.&nbsp;&nbsp;&nbsp;
	  </td>
	  <!--<td bgcolor="#F7B64C" height="35px" width="100px">
		FOTO ALUMNO
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="100px">
		FIRMA ALUMNO
	  </td>-->
	  <td bgcolor="#F7B64C" height="35px" width="100px">
		REGISTRO
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="131px">
		NOMBRE
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="110px">
		APELLIDO PATERNO
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="111px">
		APELLIDO MATERNO
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="111px">
		NOMBRE COMPLETO
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="169px">
		CURP
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="169px">
		NIVEL
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="169px">
		PLANTEL
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		CARRERA
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		CARRERA COMPLETA
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		TIPO CREDENCIAL
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		FECHA ENVI” CETI
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		ESTADO DE IMPRESI”N
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		FECHA DE IMPRESI”N KD
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		HID
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		OBSERVACIONES
	  </td>
	  <td bgcolor="#F7B64C" height="35px" width="211px">
		FIRMA DE RECIBIDO
	  </td>
	</tr>
<?php 
$count = 1;

	if(count($registros) == 0 || $registros == NULL)
	{
	   echo tr_color('#F9F7F7','#FFFFFF'); 
	   echo '<td align="center" colspan="6" style="font-weight:bold;" height="30">NO SE ENCONTRARON REGISTROS</td>';
	   echo "</tr>";
	}
	
	else
	{
	  	
		foreach($registros AS $valueR)
		{  
		  $objeto = new alumnos();
		
		  $datosRegistro = $objeto -> buscar_registro_alumno($valueR -> registro);
				
				foreach($datosRegistro AS $value){
				  
			      /*//Se valida la imagen del alumno
				  if(file_exists("/var/www/htdocs/calculo/ingenieria/public/img/fotos/".$value -> registro.".JPG"))
					$foto = "<img width='100' height='80' align='center' src='http://ase.ceti.mx/ingenieria/public/img/fotos/".$value -> registro.".JPG' />";
					  
				  else if(file_exists("/var/www/htdocs/calculo/ingenieria/public/img/fotos/".$value -> registro.".jpg"))
					$foto = "<img width='100' height='80' src='http://ase.ceti.mx/ingenieria/public/img/fotos/".$value -> registro.".jpg' />";
					  
				  else
					$foto = "SIN FOTO";

				  //Se valida la imagen de la firma del alumno
				  if(file_exists("/var/www/htdocs/calculo/ingenieria/public/img/firmas/F".$value -> registro.".jpg"))
					$firma = "<img width='100' height='80' src='http://ase.ceti.mx/ingenieria/public/img/firmas/F".$value -> registro.".jpg' />";
					  
				  else if(file_exists("/var/www/htdocs/calculo/ingenieria/public/img/firmas/f".$value -> registro.".jpg"))
					$firma = "<img width='100' height='80' src='http://ase.ceti.mx/ingenieria/public/img/firmas/f".$value -> registro.".jpg' />";
					  
				  else if(file_exists("/var/www/htdocs/calculo/ingenieria/public/img/firmas/F".$value -> registro.".JPG"))
					$firma = "<img width='100' height='80' src='http://ase.ceti.mx/ingenieria/public/img/firmas/F".$value -> registro.".JPG' />";
					  
				  else if(file_exists("/var/www/htdocs/calculo/ingenieria/public/img/firmas/f".$value -> registro.".JPG"))
					$firma = "<img width='100' height='80' src='http://ase.ceti.mx/ingenieria/public/img/firmas/f".$value -> registro.".JPG' />";
					  
				  else
					$firma = "SinFirma";*/
	  
				  //Se valida el nivel del alumno
				  if($value -> nivel == "T")
				    $nivel = "TGO."; //"TECN”LOGO";
					
				  else
				    $nivel = "ING."; //"INGENIERÕA";
					
				  //Se valida el plantel del alumno
				  if($value -> plantel == "C")
				    $plantel = "COLOMOS";
					
				  else
				    $plantel = "TONALA";
					
				  echo tr_color('#F9F7F7','#EFEDED'); 
				  echo '<td align="center" height="30" style="line-height: 50px;">   '.$count.'   </td>';
				  //echo '<td align="center" height="80" width="100" style="font-weight:bold;">'.$foto.'</td>';
				  //echo '<td align="center" height="80" width="100" style="font-weight:bold;">'.$firma.'</td>';
				  echo '<td align="left" height="30">'.$value->registro.'</td>';
				  echo '<td align="left" height="30">'.$value->nombres.'</td>';
				  echo '<td align="left" height="30">'.$value->a_paterno.'</td>';
				  echo '<td align="left" height="30">'.$value->a_materno.'</td>';
				  echo '<td align="left" height="30">'.$value->nombres." ".$value->a_paterno." ".$value->a_materno.'</td>';
				  echo '<td align="left" height="30">'.$value->curp.'</td>';
				  echo '<td align="left" height="30">'.$nivel.'</td>';
				  echo '<td align="left" height="30">'.$plantel.'</td>';
				  echo '<td align="left" height="30">'.htmlentities(strtr(strtoupper($value -> carrera),"‡ËÏÚ˘·ÈÌÛ˙ÁÒ‰ÎÔˆ¸","¿»Ã“Ÿ¡…Õ”⁄«—ƒÀœ÷‹")).'</td>';
				  echo '<td align="left" height="30">ING. '.htmlentities(strtr(strtoupper($value -> carrera),"‡ËÏÚ˘·ÈÌÛ˙ÁÒ‰ÎÔˆ¸","¿»Ã“Ÿ¡…Õ”⁄«—ƒÀœ÷‹")).'</td>';
				  echo '<td align="left" height="30"></td>';
				  echo '<td align="left" height="30"></td>';
				  echo '<td align="left" height="30"></td>';
				  echo '<td align="left" height="30"></td>';
				  echo '<td align="left" height="30">'.$value -> hid.'</td>';
				  echo '<td align="left" height="30"></td>';
				  echo '<td align="left" height="30"></td>';
				  echo "</tr>";
				  
				  $count++;
				}
		   
		}
    }
?>
  </table>
</center>