
	<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>CREDENCIALES</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
						<hr/><br/>
						Este m&oacute;dulo permite imprimir credenciales provisionales, actualizar los datos de los alumnos y generar reporte <br/>segun los alumnos solicitados.
					</div>
				</td>
			</tr>
		</table>
		<br><br>