<div class="menu">
	<a href="<?= KUMBIA_PATH ?>tgoprofesor/index">Entrar como Prof.</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/alumnos">Alumnos</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/profesores">Profesores</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/infraestructura">Salones</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/materias">Materias</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/grupos">Grupos</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/horarios">Horarios</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/asignacion">Asignacion</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/calificaciones">Calificaciones</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/apoyo">Apoyo Académico</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/salir">Salir</a>
<div>