<style type="text/css">
	.linknegrita a:hover{
		font-weight: bold;
		text-decoration: none;
		color:#000000;
	}
	.linknegrita a{
		font-weight: none;
		text-decoration: none;
		color:#000000;
	}
</style>

<form method="POST" action="<?= KUMBIA_PATH ?>ventanilla/checarContra2/">
	<table border="0" cellpadding="0" cellspacing="0" align="center">
	<br /><br />
		<tr>
			<td style="font-family: Verdana;" align="center">
			<h3>Ingrese el registro, para obtener su contrase&ntilde;a.</h3>
			</td>
		</tr>
		<tr>
			<td width="350" class="fondonaranja" align="center" valign="center">
				<br />
				<input type="text" name="registro" id="registro" maxlength="10">
				<br />
				&nbsp;
				<br />
				<input type ="submit">
				<br />
				&nbsp;
			</td>
		</tr>
		<tr>
			<td width="225" valign="top" style="vertical-align:top;" class="fondonaranja">
			</td>
		</tr>
	</table>
	<br><br>
</form>