<table border="1" style="font-size:10px;" class="bordeazul">
						<th height="20" class="naranja" colspan="7">
							SELECCIONA EL PROFESOR QUE QUIERES REVISAR
						</th>
						<tr>
							<td width="100" align="center" class="azul">&nbsp;</td>
							<th width="50" align="center" class="azul">Lun</th>
							<th width="50" align="center" class="azul">Mar</th>
							<th width="50" align="center" class="azul">Mie</th>
							<th width="50" align="center" class="azul">Jue</th>
							<th width="50" align="center" class="azul">Vie</th>
							<th width="50" align="center" class="azul">Sáb</th>
						</tr>
						<tr>
							<th height="25" class="naranja">7:00 - 7:55</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">7:55 - 8:50</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="10" class="naranja">8:50 - 9:30</th>
							<th bgcolor="#999999">-</th>
							<th bgcolor="#999999">-</th>
							<th bgcolor="#999999">-</th>
							<th bgcolor="#999999">-</th>
							<th bgcolor="#999999">-</th>
							<th bgcolor="#999999">-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">9:30 - 10:25</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">10:25 - 11:20</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">11:20 - 12:15</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">12:15 - 13:10</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">13:10 - 14:05</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">14:05 - 15:00</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
					</table><br>
					<table border="1" style="font-size:10px;" class="bordeazul">
						<tr>
							<td width="100" align="center" class="azul">&nbsp;</td>
							<th width="50" align="center" class="azul">Lun</th>
							<th width="50" align="center" class="azul">Mar</th>
							<th width="50" align="center" class="azul">Mie</th>
							<th width="50" align="center" class="azul">Jue</th>
							<th width="50" align="center" class="azul">Vie</th>
							<th width="50" align="center" class="azul">Sáb</th>
						</tr>
						<tr>
							<th height="25" class="naranja">15:00 - 15:55</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">15:55 - 16:50</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">16:50 - 17:45</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">17:45 - 18:40</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">18:40 - 19:35</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
						<tr>
							<th height="25" class="naranja">19:35 - 20:30</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
							<th>-</th>
						</tr>
					</table>