		<table border="0" cellpadding="0" cellspacing="0" width="770" style="margin-left:10px;">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px; margin-top:20px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>ACCESO DENEGADO</b></div>
					<div style="color: #000000; font-size: 13px; font-family:arial; font-weight:bold;" align="justify">
					<br>
						Intentaste ingresar de una forma ilegal al sistema.
					</div>
				</td>
			</tr>
		</table>
	
		<br><br>