		<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>ASPIRANTES</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<hr>
						<br>
						<table border="0" cellpadding="1" cellspacing="1" width="750">
							<tr>
								<td width="350" valign="top">
								<b>TRÁMITE PARA ASPIRANTE A INGRESAR AL CETI</b>
								<br>
								<br>
									Haber adquirido el Paquete de aspirante a ingresar al CETI, el cual contiene:
								<br>
								<ul>
								<li>Solicitud de Aspirante
								<br>
								<li>Guía de CENEVAL
								<br>
								<li>Anexo Módulo de Inglés (solo para Nivel Tecnólogo)
								<br>
								<li>Copia de Hoja de registro de CENEVAL
								<br>
								<li>Hoja de trámites a seguir para Legalización de Certificados
								<br>
								<li>Hoja de documentos necesarios cuando son aceptados en el Dictamen Definitivo.
								</ul>
								<br>
								Entregar a la Ventanilla del Departamento de Servicios de Apoyo Académico los siguientes documentos:
								<br><br>
								<ul>
									<li>Solicitud de Aspirante de Nuevo Ingreso, la cual deberá estar requisitada correctamente, tal y como se indica en la misma.</li>
									<br>
									<li>Copia del Certificado de Secundaria o Nivel Medio Superior, o equivalente, según el nivel al que vas a ingresar; o bien, constancia de estudios con promedio global, que avale que cursas el último grado de dicho nivel y que indique la clave oficial de la escuela.</li>
									<br>
									<li>Copia de CURP en hoja tamaño carta.</li>
									<br>
									<li>4 fotografías tamaño credencial blanco y negro de FOTO ESTUDIO, no instantáneas.</li>
									<br>
									<li>Recibo del pago del paquete de derecho a examen de Admisión al CETI (recibo color amarillo).</li>
								</ul>
								</td>
								<td width="50">
								
								</td>
								<td width="350" valign="top">
									<b>TRÁMITE PARA ALUMNOS ADMITIDOS</b>
									<br>
									<br>
									Si fuiste admitido como alumno, deberás entregar la siguiente documentación en el Departamento de Apoyo Académico.
									<br>
									<ul>
										<li>Certificado de estudios del nivel anterior: original y copia tamaño carta, el cual deberá estar legalizado por la instancia u organismo que regule la escuela de procedencia, si es que requiere dicho trámite.</li>
										<li>Copia de la CURP en tamaño carta.</li>
										<li>Acta de nacimiento original y copia en tamaño carta (en buenas condiciones o de fecha reciente).</li>
										<li>Copia del pago de inscripción sellado por Banco Banorte.</li>
										<li>2 fotografías tamaño credencial blanco y negro de FOTO ESTUDIO.</li>
										<li>Constancia de buena conducta en original.</li>
										<li>Certificado médico, original (expedido por alguna dependencia oficial, de fecha reciente de 2 semanas máximo, Cruz Roja, Cruz Verde, IMSS, etc.).</li>
									</ul>
									<br><br>
									EN CASO DE SER MAYOR DE EDAD:
									<ul>
										<li>Constancia de no antecedentes penales (fecha de expedición máximo 1 mes).</li>
										<li>Copia de la cartilla del servicio militar o constancia que se encuentra en trámite.</li>
									</ul>
									<br><br>
									NOTA: Todos los documentos deberán estar en buen estado, sin mutilaciones o alteraciones, de lo contrario serán rechazados.
								</td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
		</table>
		<br><br>