		<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>CALENDARIO ESCOLAR 2010 - 2011</b></div>
					<div style="color: #000000; font-size: 11px;" align="center">
					<br>
						<?= img_tag("calendario10-11.jpg","border: 0", "width: 715", "height: 512") ?>
					</div>
				</td>
			</tr>
		</table>
		<br><br>