<div id="encabezado">
<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	INGRESO AL SISTEMA DE CONTROL ESCOLAR<br />
 	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CETI Plantel Colomos
</div>

<br>
<div style="color: #FFFFFF; font-size: 14px;" class="azul">
<center>
<br />
<p style="padding: 0px 10px;"><b>Las <span style="color: #ffca5b">FICHAS DE PAGO</span> quedaran disponibles el día <span style="color: #ffca5b">20 de Agosto del 2009</span><br /> al <span style="color: #ffca5b">31 de Agosto del 2009</span> con un recargo de <span style="color: #ffca5b">$230.00</span>
<br />
<h3>DEPTO. DE SERVICIOS DE APOYO ACADEMICO</h3>
<br />
</center>
</div>
<br>
<div class="naranja" style="color:#333333; padding: 10px;">
<br />
<center>
	<h2>Alumnos de Nuevo Ingreso</h2>
	<p><li>Alumno de nuevo ingreso tu Usuario y Contraseña para ingresar al sistema es igual que tu numero registro en ambos casos</li></p>
	<!--<p><li><b>Se solicita que todos los alumnos realicen la actualizaci&oacute;n de datos, 
	y los alumnos que ya la hayan realizado favor de verificar que la informaci&oacute;n sea la correcta; quien NO lo realice, NO 
	vizualizara su tira de materias el d&iacute;a Jueves 13 de Agosto</li></b></p>
	<p><li><span style="color: #cc3333;">Ultima oportunidad para todos aquellos alumnos que por una razon justificada no se presentaron a la toma de fotograf&iacute;a en el d&iacute;a y hora programadas 
	en el curso de inducci&oacute;n favor de presentarse el dia Jueves 13 de Agosto en la ventanilla de servicios de Apoyo Acad&eacute;mico para 
	la toma de la misma; con horario de 9am - 12pm</span></li></p>
    <br />-->
</center>
</div>
<br />
<center>
<table border="1" style="font-size:10px;">
	<tr>
		<th class="azul" width="400" height="25">
			Iniciar sesión
		</th>
		<th class="azul" width="400" height="25">
			Ayuda
		</th>
	</tr>
	
	<tr>
		<th width="400" height="25"><center><br>
		<form method="POST" action="<?= KUMBIA_PATH ?>seguridad/iniciarsesion">
			<table border="1" style="font-size:10px;">
				<tr>
					<td class="naranja" width="150">&nbsp;Código(Registro):</td>
					<td><input type="text" name="registro"></td>
				</tr>
				<tr>
					<td class="naranja" width="150">&nbsp;Contraseña:</td>
					<td><input type="password" name="password"></td>
				</tr>
			</table>
			<br>
			<input type="submit" value="INGRESAR AL SISTEMA">
			<br>
		</form>
		</th>
		<td width="400" height="25"><center>
			<div align="justify" style="width:300px;">
				<b>¿Perdiste tu contraseña?</b>
				<br><br>
				Si aún no cuentas con una contrasena de acceso o la has olvidado, deberás acudir con una identificación oficial al Departamento de Apoyo Académico para obtener una contrasena nueva. 
			</p>
		</td>
	</tr>
</table>
</center>