<script language="JavaScript1.2">

function setIt( Objeto ){
	if( Objeto.value == "" )
		Objeto.value = "Registro";	
}
function clearIt( Objeto ){
	if( Objeto.value == "Registro" )
		Objeto.value = "";
}

</script>

<link rel="stylesheet" type="text/css" href="<?= KUMBIA_PATH ?>css/estilo.css"/>
<body style="background: none repeat scroll 0 0 #FFFFFF;">
<table border="0" cellpadding="0" cellspacing="0" width="580" >
	<tr>
	  <td valign="middle" style="font-family: Verdana;">

	<div>
	<div class="side-aa">
		<div class="reticulas00">
			<p style="font-weight:bold; font-size: 10px;">Plan 2000</p>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas00/plan_ing_elect_comp_ago_2000.pdf" 
				target="_blank">Reticula Electr&oacute;nica en Computaci&oacute;n</a><br /><br style="font-size: 4px"/>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas00/plan_ing_elect_manufactura_ago_2000.pdf" 
				target="_blank">Reticula Electr&oacute;nica Manufactura</a><br /><br style="font-size: 4px"/>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas00/plan_ing_ind_instrumentacion_ago_2000.pdf" 
				target="_blank">Reticula Industrial Instrumentaci&oacute;n</a><br /><br style="font-size: 4px"/>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas00/plan_ing_ind_mecanica_ago_2000.pdf" 
				target="_blank">Reticula Industrial Mec&aacute;nica</a><br /><br style="font-size: 4px"/>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas00/plan_ing_mecatronica_ago_2000.pdf" 
				target="_blank">Reticula Mecatr&oacute;nica</a><br /><br style="font-size: 2px"/>
		</div>
		<div class="reticulas">
			<p style="font-weight:bold; font-size: 10px;">Plan 2007</p>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas/Reticula_Electronica_2007.pdf" target="_blank">Reticula Electrónica</a><br /><br style="font-size: 4px"/>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas/Reticula_Mecatronica_2007.pdf" target="_blank">Reticula Mecatrónica</a><br /><br style="font-size: 4px"/>
			<a class="letra11px" href="<?= KUMBIA_PATH ?>files/reticulas/Reticula_Industrial_2007.pdf" target="_blank">Reticula Industrial</a><br /><br style="font-size: 2px"/>
		</div>
	</div>
    <div class="side-bb">
     <div class="mylogin2">
				<p style="font-weight:bold; font-size: 12px;"><b>Para Descargar las <span style="color: #ffca5b">FICHAS DE PAGO</span> descarga el instructivo del siguiente link:<br /><br>
                  <span style="color: #ffca5b"><a  href="<?= KUMBIA_PATH ?>files/ComoDescargarFichaIngenieria.pdf" target="blank">Como Descargar Ficha de Pago para Inscripcion</a></span> <br />
                </p>
				
     </div>    
	</div>
	<div class="side-bb">
		<div class="side-aaa">
		<div class="mylogin">
		<form method="POST" action="<?= KUMBIA_PATH ?>seguridad/iniciarsesion" target="_blank">
			<p style="font-weight:bold; font-size: 13px;">Iniciar Sesi&oacute;n</p>
			<br style="font-size: 3px"/>
			<input type="text" onBlur="setIt(this)" onFocus="clearIt(this)" size="16" value="Registro" name="login" id="login" class="input">
			<br style="font-size: 2px"/><br style="font-size: 2px"/>
			<input type="password" onBlur="setIt(this)" onFocus="clearIt(this)" size="16" value="Registro" name="password" id="password" class="input">
			<input type="image" border="0" alt="Log In" src="<?= KUMBIA_PATH ?>img/button_go.gif" value="Enter" name="LoginUserSubmitNewEvent">
			<br style="font-size: 2px"/><br style="font-size: 2px"/>
			<br />
			
		</form>
		</div>
        
		</div>
		<div class="side-bbb">
			<div class="mylogin1">
				<p style="font-weight:bold; font-size: 13px;">&iexcl;Ayuda!</p>
				<p style="font-weight:bold; font-size: 11px;">&iquest;Perdiste tu contraseña?</p>
				<p style="font-weight:bold; font-size: 10px;">Si a&uacute;n no cuentas con una 
				contraseña de acceso o la has olvidado, deber&aacute;s acudir con una identificación
				oficial al Departamento de Apoyo Académico para obtener una contraseña nueva.</p>
			</div>
		</div>
	</div>
	</div>
    
	</div>
		</td>
  </tr>
</table>
</body>