		<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>REGLAMENTOS VIGENTES</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<br />
					A continuación se presentan los reglamentos vigentes para cada uno de los planes de estudio
					<br />
					<br />
					
<!--
<table width="500"  border="1" align="center" cellpadding="1" cellspacing="0">
  <tr>
    <th height="39" colspan="4"><p>OBTENCIÓN DE LAS NORMATIVAS ACTUALES, VIGENTES, DEL CETI.<br /></p></th>
  </tr>
  <tr>
    <td bgcolor="#666633" class="calendarText"><span class="style1">NIVEL</span></td>
    <td bgcolor="#666633" class="calendarText"><span class="style1">PLAN DE ESTUDIOS</span></td>
    <td bgcolor="#666633" class="calendarText"><span class="style1">TAMA&Ntilde;O</span></td>
    <td bgcolor="#666633" class="calendarText"><span class="style1"></span></td>

  </tr>
  <tr>
    <td width="90"> TECN&Oacute;LOGO</td>
    <td width="104">PLAN 1998 </td>
    <td width="51">6.1 MB</td>
    <td width="154"><form action="pdfs/Reglamento1988.pdf" method="post" name="form1" target="_blank" id="form1">

      <div align="center">        
          <input name="button" type="submit" class="button01" id="button" value="DESCARGAR ARCHIVO" />
       
        </div>
    </form>    </td>
  </tr>
  <tr>
    <td>TECN&Oacute;LOGO</td>
    <td>PLAN 2007</td>

    <td>6.5 MB</td>
    <td><form action="pdfs/Reglamento2007.pdf" method="post" name="form2" target="_blank" id="form2">
      <div align="center">
        <input name="button2" type="submit" class="button01" id="button2" value="DESCARGAR ARCHIVO" /></div></form>    </td>
  </tr>
  <tr>
    <td>INGENIERIA</td>

    <td>PLAN FLEXIBLE</td>
    <td>5.3 MB</td>
    <td><form action="pdfs/ReglamentoIngenieria.pdf" method="post" name="form2" target="_blank" id="form2">
      <div align="center">
        <input name="button2" type="submit" class="button01" id="button2" value="DESCARGAR ARCHIVO" />
      </div>
    </form>    </td>

  </tr>
</table>
-->
<a href ="http://www.colomos.ceti.mx/Documentos/Reglamentos/REGLAMENTO%20DE%20ALUMNOS%20VIGENCIA%20ENERO%202009.pdf" target= "_blank"><h3>Reglamento</h3></a>

					</div>
				</td>
			</tr>
		</table>
<!--
			<input type="submit" value="ENTRAR AL SISTEMA" style="font-family: Verdana; font-size: 14px; background: #FFCA5B;">
-->
		<br><br>