<style type="text/css">
/* CSS Document */

body
{
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
}

.enlaceSup
{
	font-size: 10px;
	color: #FFFFFF;
}

.hts
{
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	font-weight: bold;
	color: #FFFFFF;
}

.letrasChiquitas
{
	font-size: 9px;
	color: #FFFFFF;
}

.titulosMenu a:link, .titulosMenu a:visited, .titulosMenu a:hover, .titulosMenu a:active
{
	font-size: 12px;
	font-weight: bold;
	text-decoration: none;
	color: #FFFFFF;
}


.titulosMenu2
{
	font-size: 12px;
	font-weight: bold;
	color: #000000;
}

.itemMenu a:link, .itemMenu a:visited
{
	font-size: 12px;
	color: #000000;
	display:block;
	background:#f4944d;
}

.itemMenu a:hover
{
	font-size: 12px;
	color: #000000;
	display:block;
	background:#FFE2B7;
}
.itemMenu2 a:link, .itemMenu2 a:visited
{
	font-size: 12px;
	color: #000000;
}

.itemMenu2 a:hover
{
	font-size: 12px;
	color: #000000;
}

.itemMenuN
{
	font-size: 12px;
	color: #000000;
}

.enlaceIzquierdo
{
	font-size: 12px;
	font-weight: bold;
	color: #FFFFFF;
}

.tituloDerecha
{
	font-size: 10px;
	color: #FFFFFF;
}

.tituloP
{
	font-size: 12px;
	color: #FFFFFF;
	font-weight: bold;
}

.textoNoticias
{
	font-size: 12px;
	font-weight: normal;
	color: #000000;
}

.enlaceInterno
{
	font-size: 12px;
	font-weight: bold;
	color: #000000;
	text-decoration: underline;
}
A{color:#003399;font-size:10pt}
A.importante{color:#3333FF;font-size:10pt}
A.noticia{color:#66B9FD;font-size:10pt}
A.subdominio{color:#ffffff;font-size:10pt}
A.navegador{color:#000000;font-size:10pt}
/*Estilo general de parrafos con clases para distintos usos*/
P{color:#000000;font-size:10pt}
P.peque{color:#000000;font-size:7pt}

/*Estilo general de tablas*/
td.titulo{
 font-size:10pt;
 color:#000000;
 background-color:#f9ce8a;
 }
td.gris{
 background-color:#FFEECC;
}
tr{font-size:10pt}
</style>

<body bgcolor="#FFFFFF">
<table width="800" border='0' style='border:none;' align="center" cellpadding="0" cellspacing="0">
  <tr  bgcolor='#f4b439' >
	<td valign='top'><img src='<?= KUMBIA_PATH ?>public/imagenes/logo.jpg' height='99' style='border:2px solid #FFFFFF;'></td>
	<td valign='bottom'>
		<table bgcolor='#f4b439' border='0' style='border:none;'  cellpadding="0" cellspacing="0">
			<tr>
				<td valign='top' colspan='9'><img src='<?= KUMBIA_PATH ?>public/imagenes/cabeceraNaranja.jpg' width='540' /></td>
			</tr>
			<tr height="21" bgcolor="#404040">
					<td width='40'>&nbsp;</tD>
                    <td width="40%" align='center'><a href="http://www.ceti.mx/" class="enlaceSup">Sitio Institucional</a></td><td width='10'><font color='#ffffff'>|</font></td>
                    <td width="30%" align='center'><a href="http://www.ceti.mx/?id=27" class="enlaceSup">Mapa del Sitio</a></td><td width='10'><font color='#ffffff'>|</font></td>
					<td width="30%" align='center'><a href="http://www.ceti.mx/?id=contacto" class="enlaceSup">Contacto</a></td>
			</tr>
		</table>
	</td>

	<td valign='top'>
		<table border='0' style='border:none;'  cellpadding="0" cellspacing="0">
		<tr>
			<td valign='top' align='left' bgcolor='#eaebee'><img src='<?= KUMBIA_PATH ?>public/imagenes/logoMEX.gif' width='74'/></td>
		</tr>
		<tr>
			<td valign='top' align='left'><img src='<?= KUMBIA_PATH ?>public/imagenes/logoSEP.jpg'/></td>
		</tr>
		</table>

	</td>
  </tr>
  <tr>
	<td colspan='3'>
	<form action="http://www.ceti.mx/buscar.php" id="searchbox_009538413630072206378:sldupbeo6ou"> 
		<table width='100%'  bgcolor='#f4b439'  cellpadding="0" cellspacing="0">
			<tr bgcolor='#cccccc'>
				<td width='65%'align="center" ><div class="hts"><strong>Hombre, Tecnología y Sociedad</strong></div></td>
				<td>
					Buscar en el sitio:
					<input type="text" name="q" size="15" /> &nbsp;<button style='border:none; background:#898989;'>&nbsp;Ir&nbsp;</button>
					<input type="hidden" name="cx" value="009538413630072206378:sldupbeo6ou" />
					<input type="hidden" name="cof" value="FORID:11" />
				</td>
			</tr>
		</table>
		</form>
	</td>
  </tr>
  <tr>
	<td colspan='3'>
		<center>
			<br>
		<table border="0" cellpadding="0" cellspacing="0" width="770" >
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<br>
						<center>
						<form name="forma1" method="POST" action="https://cira.ceti.mx/cira/paginas/cirax2008.html">
							<table border="1" cellpadding="1" cellspacing="1" style="font-size: 10px;">
								<tr><th width="600" colspan="3" height="40" bgcolor="#f4b439" style="color:#000000;font-size:14px;">NIVEL TÉCNOLOGO</th></tr>
								<tr>
									<th colspan="2" height="25" bgcolor="#1569c7" style="color: #FFFFFF;">INICIAR SESION</th>
									<th height="25" bgcolor="#1569c7" style="color: #FFFFFF;">AYUDA</th>
								</tr>
								<tr>
									<td width="150" align="left"><b>&nbsp;Código (Registro): </b></td>
									<td width="150"><input type="text" name="clave" id="clave" style="font-weight: bold; font-size: 12px; size:150px;"></td>
									<td width="300" rowspan="3"><center>						
									<table style="font-size:11px;">
										<tr>
											<td width="280"><div align="justify">
												<b>¿Perdiste tu contraseña?</b>
												<br><br>
												Si aún no cuentas con una contraseña de acceso o la has olvidado, deberás acudir con una identificación oficial al <b>Departamento de Apoyo Académico</b> para obtener una contraseña nueva.
											</td>
										</tr>
									</table>
									</center>
									</th>
								</tr>
								<tr>
									<td width="150" align="left"><b>&nbsp;Contraseña: </b></td>
									<td width="150"><input type="password" name="contra" id="contra" style="font-weight: bold; font-size: 12px; size:150px;"></td>
								</tr>
								<tr>
									<th colspan="2"><br><input type="submit" value="INGRESAR" style="color: #000000;background: #FFCA5B;"></form></th>
								</tr>
					
			</table>
		</form>
		<br><br>
		<form method="POST" action="<?= KUMBIA_PATH ?>seguridad/iniciarsesion">
							<table border="1" cellpadding="1" cellspacing="1" style="font-size: 10px;">
								<tr><th width="600" colspan="3" height="40" bgcolor="#f4b439" style="color:#000000;font-size:14px;">NIVEL INGENIERIA</th></tr>
								<tr>
									<th colspan="2" height="25" bgcolor="#1569c7" style="color: #FFFFFF;">INICIAR SESION</th>
									<th height="25" bgcolor="#1569c7" style="color: #FFFFFF;">AYUDA</th>
								</tr>
								<tr>
									<td width="150" align="left"><b>&nbsp;Código (Registro): </b></td>
									<td width="150"><input type="text" name="registro" style="font-weight: bold; font-size: 12px; size:150px;"></td>
									<td width="300" rowspan="3"><center>						
									<table style="font-size:11px;">
										<tr>
											<td width="280"><div align="justify">
												<b>¿Perdiste tu contraseña?</b>
												<br><br>
												Si aún no cuentas con una contraseña de acceso o la has olvidado, deberás acudir con una identificación oficial al <b>Departamento de Apoyo Académico</b> para obtener una contraseña nueva.
											</td>
										</tr>
									</table>
									</center>
									</th>
								</tr>
								<tr>
									<td width="150" align="left"><b>&nbsp;Contraseña: </b></td>
									<td width="150"><input type="password" name="password" style="font-weight: bold; font-size: 12px; size:150px;"></td>
								</tr>
								<tr>
									<th colspan="2"><br><input type="submit" value="INGRESAR" style="color: #000000;background: #FFCA5B;"></form></th>
								</tr>
					
			</table>
		</form>
					</div>
				</td>
			</tr>
		</table>
			<br><br>
		</center>
	</td>
  </tr>
</table>
