<input type="hidden" readonly="readonly" name="tipoper" id="tipoper" value="<?php echo $tipoPersona; ?>"/>
<center>	
  <?= form_remote_tag('caja/buscarExAlumnos','update: viewExAlumnos', 'success: alertmsg();') ?>
	<table width="95%" border=1 cellspacing=0 cellpadding=2 bordercolor="#1E5EA8">
	  <tr>
	    <td bgcolor="#2462AB" style="height:30px; text-align:center; color:#FFFFFF; font-weight:bold; font-size: 13px;" colspan="4">
		  &nbsp;&nbsp;<div style="float: left; line-height: 44px; margin-left: 372px;">BUSCAR  EX-ALUMNO</div>&nbsp;&nbsp;&nbsp;&nbsp;
		  <img src="../public/img/Usuario_Agregar.png" style="float: left; width: 50px; height: 45px; cursor: pointer; margin-left: 337px;" title="Agregar Ex-Alumno al historial" onclick="viewAgregarExAlumno()" />
		</td>
	  </tr>
	  <tr>
		<td  bgcolor="#FFFFFF" style="text-align:center; font-weight:bold; font-size: 13px;">
		  &nbsp;&nbsp;Por registro&nbsp;&nbsp;<input type="radio" id="busquedaRegistro" name="tipoBusqueda" onclick="typeSearchExAlumno();"/>
		</td>
		<td  bgcolor="#FFFFFF" style="text-align:center; font-weight:bold; font-size: 13px;">
		  &nbsp;&nbsp;Por nombre&nbsp;&nbsp;<input type="radio" id="busquedaNommbre" name="tipoBusqueda" onclick="typeSearchExAlumno();"/>
		</td>
		<td align="center" bgcolor="#FFFFFF">
		  <?= text_field_tag('exAlumno', 'id: exAlumno',"style: width:320px; text-transform: uppercase;") ?>
		  <input type="hidden" id="activoBusqueda" name="activoBusqueda" readonly="readonly"/>
		</td>
		<td align="center">
		  <?= submit_tag('BUSCAR EX-ALUMNO','id: boton','class: common_button') ?>
		</td>
	  </tr>
	</table>
  <?= end_form_tag() ?>
</center>
 <!--Se muestran el formulario para agregar un ex-alumno al historico-->
<div id="addExAlumno" name="addExAlumno">
</div>

<style type="text/css">    
    #listadoConceptos{
        font-size: 12px;
        width: 100%;
        height: 370px;
        overflow: auto;
        background-color: #FFFFFF;
    }
    #listadoConceptos table{
        font-size: 12px;
    }
    #listadoConceptos td{
        border-bottom: 1px solid #CCCCCC;
		height:35px;
    }
    #listadoConceptos tr:hover{
        background-color: #13539B;
        color: #ffffff;
    }
    #listadoConceptos img{
        border: 0px;
    }
    #complementario{
        padding: 3px;
        font-size: 12px;
        /*background-color: #FFFFFF;*/
        height: 150px;
        overflow: auto;
    }
    #pagos{
        padding: 3px;
        font-size: 12px;
        min-height: 400px;
        background-color: #FFFFFF;
    }
</style>
<br /><br />
<div class="formulario" style="width: 100%">
    <div id="contenido">
	        <div id="viewExAlumnos">
			</div>

        <div id="complementario" style="margin-top:-35px; border:1px solid #FFFFFF; display:none; ">
            Se agrega el concepto y su costo.
        </div>
		<?php echo form_remote_tag('caja/guardarConcepto','update: muestraAqui', 'name: formConceptos')?>
		
		<div id="contenedor" style="margin-top:-35px; border:1px solid #FFFFFF; display:none;">
		  <table class="formulario" width="100%" style="margin-top:4px;" border="0" class="conceptos">
			<tr style=" background-color: #13539B;  color: #FFFFFF;  font-weight: bold; text-align: center;">
			  <td width="400px" align="center">
				CONCEPTO
			  </td>
			  <td align="center">
				CANTIDAD
			  </td>
			  <td colspan="2" align="center">
				COSTO
			  </td>
			  <td align="center">
				TOTAL
			  </td>
			  <td align="center">
				ACCI&Oacute;N
			  </td>
			</tr>
	      </table>
		  <input type="hidden" readonly="readonly" name="registro" id="registro" value="<?php echo $registro; ?>"/>
		  <input type="hidden" readonly="readonly" name="typeP" id="typeP" value="<?php echo $tipoPersona; ?>"/>
		  <input type="hidden" readonly="readonly" name="nombrePost" id="nombrePost"/>
		</div>
		<div id="buttoSave" style="display:none;">
		   <?php echo  submit_tag('Guardar','id: boton', 'class: common_button');?>
		</div>
		<?php echo end_form_tag() ?>
    </div>
</div>

<div id="muestraAqui">
</div>

 <!--Se muestran los registros encontrados de los ex-alumnos-->
<div id="dataExAlumno" name="dataExAlumno">
</div>