<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px; width:98%;" >
	<tr>
		<th width="125" height="25" bgcolor="#FFCA5B">&nbsp;Nombre:</th>
		<th width="400" colspan="3" bgcolor="#EEEEEE">&nbsp;
		<?php
		$record = CajaController::get_info_for_partial_info_alumno();

		echo htmlentities($record['vcNomAlu']."  ".( $record['miReg']));

		?>
		</th>
		<th width="125" height="25" bgcolor="#FFCA5B"><b>&nbsp;N&uacute;mero de <br />&nbsp;cr&eacute;ditos:</th>
		<th width="100" bgcolor="#EEEEEE">&nbsp;<?= $record['ncreditos'] ?></th>
		<th width="100" height="25" bgcolor="#FFCA5B">&nbsp;Promedio:</th>
		<th width="75" bgcolor="#EEEEEE">&nbsp;<?= $record['promedio'] ?></th>
	</tr>
	<tr>
		<th width="125" height="25" bgcolor="#FFCA5B">&nbsp;Carrera:</th>
		<th width="350" bgcolor="#EEEEEE">&nbsp;
		<?= $record['career'] ?>
		</th>
		<th width="100" height="25" bgcolor="#FFCA5B">&nbsp;Plantel:</th>
		<th width="100" bgcolor="#EEEEEE">&nbsp;<?= $record['plantel'] ?></th>
		<th width="75" height="25" bgcolor="#FFCA5B">&nbsp;Turno:</th>
		<th width="125" bgcolor="#EEEEEE">&nbsp;<?= $record['turno'] ?></th>
		<th width="125" height="25" bgcolor="#FFCA5B"><b>&nbsp;Estatus:</th>
		<th width="100" bgcolor="#EEEEEE">&nbsp;
		<?php
			switch($record['enTipo']){
				case "R": echo "Regular"; break;
				case "I": echo "Irregular"; break;
				case "P": echo "Proceso"; break;
				case "C": echo "Condicionado"; break;
			}
		?>
		</th>
	</tr>
</table>
<br />