<?php
	header('Content-type: application/vnd.ms-excel');
	header("content-disposition: attachment;filename=Reporte_General.xls"); 
	
	$cajaTramites = new CajaTramites();
  
	//Obtiene fecha de impresion 
	list($anioImp,$mesImp,$diaImp)= split("/", date('Y/m/d'));
	$nombreMesImp = CajaTramites::nombre_mes($mesImp);
	
	//Obtiene fecha de inicio (Desde) de reporte
	list($anioDesde,$mesDesde,$diaDesde)= split("/", $fechaD);
	$nombreMesD = CajaTramites::nombre_mes($mesDesde);
			  
	//Obtiene fecha final (Hasta) del reporte
	list($anioHasta,$mesHasta,$diaHasta)= split("/", $fechaH);
	$nombreMesH = CajaTramites::nombre_mes($mesHasta);
		
?>
<center>
  <table style="width:100%; font-family:arial; font-size:12px; margin-top:10px; float:left; margin-bottom:80PX;">
    <tr>
	  <td>
	    <img src="http://ase.ceti.mx/ingenieria/public/img/CETI_n.jpg" align="left" width="250" height="205" />
	  </td>
	  <td colspan="5" style="font-weight:bold; text-align:center; font-size:35px;">
	    CENTRO DE ENSEÑANZA TECNICA INDUSTRIAL
	  </td>
	</tr>
    <tr>
	  <td colspan="6" style="text-align:center; font-size:25px;">
	    MODULO DE CAJA PLANTEL COLOMOS
	  </td>
	</tr>
    <tr>
	  <td colspan="6" style="text-align:center; font-size:25px;" height="50px;">
	  </td>
	</tr>
    <tr>
	  <td colspan="5" style="font-weight:bold; text-align:center; font-size:20px;">
	   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CORTE GENERAL
	  </td>
	  <td style="text-align:center; font-size:20px;">
	    Fecha de Impresión : <?php echo $diaImp." / ".$nombreMesImp." / ".$anioImp;?>
	  </td>
	</tr>
    <tr>
	  <td colspan="6" style="text-align:center; font-size:25px;" height="50px;">
	  </td>
	</tr>
    <tr >
	  <td colspan="2">
	  </td>
	  <td colspan="2" style="border-color: #000000; border-width:1px; border-right:0px; border-style: solid; font-weight:bold; text-align:center; font-size:20px;">
	    CORTE CAJA
	  </td>
	  <td style="border-color: #000000; border-width:1px; border-right:0px; border-left:0px; border-style: solid; font-weight:bold;text-align:right; font-size:20px;">
	    DEL : <?php echo $diaDesde." / ".$nombreMesD." / ".$anioDesde;?>
	  </td>
	  <td style="border-color: #000000; border-width:1px; border-style: solid; border-left:0px; solid; font-weight:bold;text-align:center; font-size:20px;">
	    AL : <?php echo $diaHasta." / ".$nombreMesH." / ".$anioHasta;?>
	  </td>
	</tr>
    <tr>
	  <td colspan="6" style="text-align:center; font-size:25px;" height="50px;">
	  </td>
	</tr>
    <tr style="font-weight:bold; color:#FFFFFF; text-align:center;">
	  <td bgcolor="#969494" height="30">
		CONCEPTO
	  </td>
	  <td bgcolor="#969494" height="30">
		NOMBRE CONCEPTO
	  </td>
	  <td bgcolor="#969494" height="30">
		PERIODO
	  </td>
	  <td bgcolor="#969494" height="30">
		NIVEL
	  </td>
	  <td bgcolor="#969494" height="30">
	    CANTIDAD
	  </td>
	  <td bgcolor="#969494" height="30">
	    COSTO
	  </td>
	  <td bgcolor="#969494" height="30">
	    TOTAL
	  </td>
	</tr>
<?php 
	if(count($reporteCaja) == 0 || $reporteCaja == NULL)
	{
	   echo tr_color('#E5E3E3','#FFFFFF'); 
	   echo '<td align="center" colspan="6" style="font-weight:bold;" height="30;">NO SE ENCONTRARON REGISTROS</td>';
	   echo "</tr>";
	   $montoTotal = 0;
	}
	
	else
	{
	    //Iniciamos la variable montoTotal en 0
		$montoTotal = 0;
		
		foreach($reporteCaja AS $value)
		{
		  //Validacion nivel
		  if($value -> nivel == "1")
			$nivel = "TECN&Oacute;LOGO";
			
		  else
			$nivel = "INGENIER&Iacute;A";
		  //Termina validacion nivel
		  
		  //Validacion de caracteres de los conceptos
		  if(strlen($value -> conceptoRef) == 1)
			$concepto = "000".$value -> conceptoRef;

		  else if(strlen($value -> conceptoRef) == 2)	
			$concepto = "00".$value -> conceptoRef;	  
			
		  else if(strlen($value -> conceptoRef) == 3)	
			$concepto = "0".$value -> conceptoRef;	 

		  else
			$concepto = $value -> conceptoRef;	  
		  //Termina validacion conceptos
		  
          //Obtiene el nobre del periodo
		  $Periodos = new Periodos();
		  $nombrePeriodo = Periodos::nombre_periodo($value -> periodo);
		  //Termina nombre periodo
		  
		  //Obtiene la cantidad por concepto solicitado
	      $cajaTramites = new CajaTramites();
		  $countConcepto = CajaTramites::count_reporte_general($fechaD, $fechaH, $value -> conceptoRef, $value -> nivel);
		  
		  //Suma los costos para obtener el monto total
		  $total = $countConcepto * $value -> costo;
          //Se realiza la suma del monto total
		  $montoTotal = $montoTotal + $total;
		  
		  echo tr_color('#FFFFFF','#E5E3E3'); 
		  echo '<td align="center" height="30">'.$concepto.'</td>';
		  echo '<td align="center" height="30">&nbsp;&nbsp;'.$value -> nombre.'</td>';
		  echo '<td align="center" height="30">'.$nombrePeriodo.'</td>';
		  echo '<td align="center" height="30">'.$nivel.'</td>';
		  echo '<td align="center" height="30">'.$countConcepto.'</td>';
		  echo '<td align="center" height="30">'.number_format($value -> costo,2).'</td>';
		  echo '<td align="center" height="30">'.number_format($total,2).'</td>';
		  echo "</tr>";
		}
?>
	  <tr>
		<td colspan="5">
		</td>
		<td align="CENTER"  style="font-weight:bold; background:#969494; color: #FFFFFF;" height="30" >
		  MONTO TOTAL
		</td>
		<td align="center"  style="font-weight:bold; background: #969494; color: #FFFFFF;">
		  <?php echo number_format($montoTotal,2); ?>
		</td>
	  </tr>
<?php
    }
?>
  </table>
</center>