
	<table border="0" cellpadding="0" cellspacing="0" width="98%">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>Solicitar Pagos</b></div>
					<div style="color: #000000; font-size: 12px;" align="justify">
						<hr/><br/>
						Permite solicitar diferentes tipos de pagos, para posteriormente generar e imprimir las fichas de pago.
					</div>
				</td>
			</tr>
		</table>
		<br><br>
<?= render_partial("caja/info_alumno"); ?> 
		<p style="background:#FCFC0C; font-size:13px; height:30px; font-family:inherit; line-height:31px;">&nbsp;&#8226; Para dar inicio a tu tramite es necesario que muestres en ventanilla la ficha que el banco te otorga como comprobante de pago.</p>
