<?= stylesheet_link_tag('ventana/ventanaPopUp', true); ?>
<div id="dialog-mask"></div>
<div id="tipoDP">
<div id="fijo" >
  <div id="headerTittle">DERECHO DE PASANTE</div>
  <div id="contenido" >
  <center>
    <table style="width:95%; font-family:arial; font-size:12px; margin-top:40px;">
	  <tr style="font-weight:bold; color:#FFFFFF; text-align:center;">
	    <td bgcolor="#939292" height="35px">
		  AGREGAR
		</td>
		<td bgcolor="#939292" height="35px">
		  MATERIAS
		</td>
	  </tr>
<?php
	 if($msg != 0 || $msg == "No se encontraron datos")
     {
       echo "<tr style='background-color: #E5E3E3; height:40px;'>"; 
	   echo "<td colspan='7' align='center' ><b>".$msg."</b></td>";
	   echo "</tr>";
     }
    
     foreach($derechoPasante AS $value)
	 {
	    echo tr_color('#FFFFFF','#E5E3E3'); 
		//if($value -> Agregado == 'False')
        echo '<td align="center" height="35px;"><input type="checkbox" name="derechoPas'.$value -> id.'" id="derechoPas'.$value -> id.'" onclick="AgregarDerechoPas('.$concepto -> id.','.$concepto -> costo.','.$value -> id.')"/></td>';
	    
		//else
		 // echo '<td align="center" height="35px;" style="font-weight:bold;">LA FICHA YA FUE GENERADA</td>';
		  	
		echo '<td height="35px;" align="center"><div id="nombre'.$value -> id.'">&nbsp;&nbsp;'.utf8_encode($value -> nombre).'&nbsp;(&nbsp;'.$value -> clave.'&nbsp;)</div></td>';
	    echo "</tr>";
		
		echo "<script type='text/javascript'>
				for(var i=0; i < countDP; i++){
				  document.getElementById('derechoPas'+miArrayDP[i]).checked = 'True';
				}
			  </script>";
	 }
?>
	</table>
  </center>
	<br/><br/><br/>
	
	<!--<input type="button" class="common_button" id="agregar" name="agregar" value="AGREGAR" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
	<center>
      <input type="button" class="common_button"  style="width:150px;" id="cerrar" name="cerrar" value="Cerrar" onclick="cerrarVentanaDP()"/>
	</center>
  </div>
</div>
</div>