<!--Se llaman los archivos css y js-->
<?= javascript_library_tag('jquery-1.4.4.min'); ?>
<?= javascript_library_tag('jquery.ui.core'); ?>
<?= javascript_library_tag('jquery.ui.widget'); ?>
<?= javascript_library_tag('jquery.ui.datepicker'); ?>
<?= javascript_library_tag('dialog_box'); ?>

<?= stylesheet_link_tag('demo_page'); ?>
<?= stylesheet_link_tag('demo_table'); ?>
<?= stylesheet_link_tag('demo_table_jui'); ?>
<?//= stylesheet_link_tag('jquery-ui'); ?>
<?= stylesheet_link_tag('smoothness/jquery-ui-1.7.2.custom'); ?>
<?= stylesheet_link_tag('themes/demos', true); ?>
<?= stylesheet_link_tag('dialog_box'); ?>
<!--Termina llamado de archivos-->

<table border="0" cellpadding="0" cellspacing="0" width="770">
  <tr>
    <td style="font-family: Verdana;">
	  <br>
	  <div style="color: #1569C7; font-size: 14px;" align="left">
	    <?= img_tag("adorno.gif","border: 0") ?> <b>MODIFICA FECHAS DE CONCEPTOS</b>
	  </div>
	  <div style="color: #000000; font-size: 11px;" align="justify">
	    <hr/><br/>
		Selecciona el concepto al cual se desea modificar la fecha de vencimiento, tambien se pueden activar o desactivar los conceptos.
      </div>
	</td>
  </tr>
</table>
<br><br>

<?= form_remote_tag('caja/modificaFechas','update: modificaConcepto', 'success: cerrarVentanaExAl();') ?>
  <center>
	<div id="modificaConcepto">
	</div>
    <table style="font-family: arial; font-size: 13px; margin-top: 30px; border: medium none darkgrey;" border=1>
	  <tr height="35px;">
	    <td class="naranja" style="font-weight:bold;" align="right">
		  <font style="color:#FC1414;">*&nbsp;</font>CONCEPTO&nbsp;:&nbsp;&nbsp;
		</td>
		<td align="center">
		  &nbsp;&nbsp;
		  <?php 
		    $cajaConceptos = new CajaConceptos();
			$result = $cajaConceptos -> find('diasActivos = 0 AND (nivel = "I" OR nivel = "TI") ORDER BY nombre ASC');

				       echo select_tag("concepto", "style: width: 350px;","onchange: activarCon()");
				       echo option_tag("0", "SELECCIONAR CONCEPTO", "selected: true");
			           foreach($result AS $value){
					     echo option_tag($value -> id.','.$value -> activo, $value -> nombre);
					   }
						 
						 
		    
		  ?>
		  </select>&nbsp;&nbsp;
		</td>
	  </tr>
	  <tr height="35px;">
	    <td class="naranja" style="font-weight:bold;" align="right">
		  <font style="color:#FC1414;">*&nbsp;</font>FECHA&nbsp;:&nbsp;&nbsp;
		</td>
		<td align="center">
          <input type="text" id="fechaVencimiento" name="fechaVencimiento" readonly="readonly" style="width:348px; margin-left: 7px;" />
		</td>
	  </tr>
	  <tr height="35px;">
	    <td class="naranja" style="font-weight:bold;" align="right">
		  <font style="color:#FC1414;">*&nbsp;</font>ACTIVO/DESCACTIVO&nbsp;:&nbsp;&nbsp;
		</td>
		<td align="center">
         <input type="checkbox" id="activar" name="activar"/>
		</td>
	  </tr>
    </table>
	<div style="margin-top:50px;">
	  <?= submit_tag('MODIFICAR','id: boton','class: common_button') ?>
    </div>
  </center>
<?= end_form_tag() ?>


<script type='text/javascript'>
  //Funcion que crea el calendario de fecha "Desde"
  $q(function() {
	$q( "#fechaVencimiento" ).datepicker({
		changeMonth: true,
		changeYear: true
	});
  });
  
  //Funcion que limpia los cmapos del formulario
  function clearCampos(){
    document.getElementById('fechaVencimiento').value = "";
    document.getElementById('concepto').value = "0";
  }
  
  //Funcion que muestra si el concepto esta activo o desactivado
  function activarCon(){
     var str = document.getElementById('concepto').value;
	 var x = str.split(',');
	 
     if(x[1] == 1)
	   document.getElementById('activar').checked = true;
	   
	 else
	   document.getElementById('activar').checked = false;
  }
</script>
  