
	<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>CAJA</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
						<hr/><br/>
						Este m&oacute;dulo ser&aacute; utilizado para solicitar, consultar e imprimir pagos.
						<br/><br/>
						Este módulo esta en etapa de desarrollo por lo que su funcionalidad no esta completada al 100%, sin embargo todos los procesos aquí presentados estan revisados y probados por lo que su uso es seguro y de confianza.
					</div>
				</td>
			</tr>
		</table>
		<br><br>