
	<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br/><br/><br/><br/>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>REPORTES CAJA</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
						<hr/><br/>
						Este m&oacute;dulo ser&aacute; utilizado para crear reportes de caja.
						<br/><br/><br/><br/>
					 </div>
				</td>
			</tr>
		</table>
		<br><br>