<?php
$title = "Es obligatorio que agregues el nombre y tel&eacute;fono.";
$registro = "2222";

?>
<?= stylesheet_link_tag('formularios'); ?>
<?= stylesheet_link_tag('dialog_box'); ?>
<?= javascript_library_tag('dialog_box'); ?>

<table width="900" class="formulario" style="margin-top:40px;">
    <tr> 
      <td height="25" > 
        <h2 id="titulo" >Proped&eacute;utico</h2> <input type="hidden" readonly="readonly" name="tipoper" id="tipoper" value="<?php echo $otroTipoPer; ?>"/>
        <span id="subtitulo">
          <?php echo $title;?>
        </span>
      </td> 
    </tr>  
    <tr>
      <td>
        <div id="contenido">
            <table width="100%">
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td colspan="2">
                                <div id="texto_arriba">
                                    Ingresar  Nombre <span id="asterisco">*</span>
                                </div>     
                                  <?= text_field_tag('nombrePrope','id: nombrePrope', 'onkeypress: javascript:return validLetters(event)', 'onblur: nombreAspirantePrope()', 'style: width:300px;', 'maxlength: 30;') ?>
                                </td>
								<td>
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								</td>
                                <td colspan="2">
                                <div id="texto_arriba">
                                    Ingresar Tel&eacute;fono <span id="asterisco">*</span>
                                </div>     
                                  <?= text_field_tag('telefonoPrope','id: telefonoPrope', 'onkeypress: javascript:return ValidNum(event)', 'onblur: nombreAspirantePrope()', 'style: width:300px;', 'maxlength: 20;') ?>
                                </td>
                 
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
      </td>
    </tr>
</table>

<style type="text/css">    
    #listadoConceptos{
        font-size: 12px;
        width: 100%;
        height: 370px;
        overflow: auto;
        background-color: #FFFFFF;
    }
    #listadoConceptos table{
        font-size: 12px;
    }
    #listadoConceptos td{
        border-bottom: 1px solid #CCCCCC;
		height:35px;
    }
    #listadoConceptos tr:hover{
        background-color: #13539B;
        color: #ffffff;
    }
    #listadoConceptos img{
        border: 0px;
    }
    #complementario{
        padding: 3px;
        font-size: 12px;
        /*background-color: #FFFFFF;*/
        height: 150px;
        overflow: auto;
    }
    #pagos{
        padding: 3px;
        font-size: 12px;
        min-height: 400px;
        background-color: #FFFFFF;
    }
</style>
<br /><br />
<div class="formulario" style="width: 100%">
    <div id="contenido">
		    <div id="listadoConceptos">
              <?= render_partial('listadoConceptos') ?>
            </div>
		
        <div id="complementario" style="margin-top:-35px; border:1px solid #FFFFFF; display:none; ">
            Se agrega el concepto y su costo.
        </div>
		<?php echo form_remote_tag('caja/guardarConcepto','update: muestraAqui', 'name: formConceptos')?>
		
		<div id="contenedor" style="margin-top:-35px; border:1px solid #FFFFFF; display:none;">
		  <table class="formulario" width="100%" style="margin-top:4px;" border="0" class="conceptos">
			<tr style=" background-color: #13539B;  color: #FFFFFF;  font-weight: bold; text-align: center;">
			  <td width="400px" align="center">
				CONCEPTO
			  </td>
			  <td align="center">
				CANTIDAD
			  </td>
			  <td colspan="2" align="center">
				COSTO
			  </td>
			  <td align="center">
				TOTAL
			  </td>
			  <td align="center">
				ACCI&Oacute;N
			  </td>
			</tr>
	      </table>
		  <input type="hidden" readonly="readonly" name="registro" id="registro" value="<?php echo $registro; ?>"/>
		  <input type="hidden" readonly="readonly" name="typeP" id="typeP" value="<?php echo $tipoPersona; ?>"/>
		  <input type="hidden" readonly="readonly" name="typeOtherP" id="typeOtherP" value="<?php echo $otroTipoPer;?>"/>
		  <input type="hidden" readonly="readonly" name="nombrePostPrope" id="nombrePostPrope"/>
		  <input type="hidden" readonly="readonly" name="telPostPrope" id="telPostPrope"/>
		</div>
		<div id="buttoSave" style="display:none;">
		   <?php echo  submit_tag('Guardar','id: boton', 'class: common_button');?>
		</div>
		<?php echo end_form_tag() ?>
    </div>
</div>

<div id="muestraAqui">
</div>

<!--Se coloca el formulario-->
<div id="formu">

</div>

<script type='text/javascript'>
//funcion que valida que solo se puedan ingresar numeros
function ValidNum(e)
{
  var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
}

//Funcion que valida que solo se puedan ingresar letras
function validLetters(e)
{
  var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
      
  if(tecla == 8)
    return true;
    
    var patron = /[A-Za-z\s]/;
	var x = String.fromCharCode(tecla);
	
  return patron.test(x)
}

//Pone en el formulario el nombre del aspirante
function nombreAspirantePrope(){
   document.getElementById('nombrePostPrope').value = document.getElementById('nombrePrope').value;
   document.getElementById('telPostPrope').value = document.getElementById('telefonoPrope').value;
}
</script>