<style type="text/css">
    .listado{
        font-size: 13px;
    }
    .listado a{
        display: block;
        text-decoration: none;
        color: #333333;
    }
    .listado a:hover{
        text-decoration: none;
        color: #FFFFFF;
    }
    .listado tr:hover *{
        background-color: #13539B;
        color: #FFFFFF;
		font-weight: bold;
    }
    .listado img{
        padding-right: 20px;
    }
    .listado img:hover{
        width: 30px;
		height: 30px;
    }
    .listado .titulo{
        background-color: #13539B;
        color: #FFFFFF;
        font-weight: bold;
        text-align: center;
    }
    .listado .titulo td{
        padding: 10px;
    }
    .listado td *{
        padding-left: 3px;
        vertical-align: middle;
    }
</style>


<!--Opciones a elegir para visualizar los tramites-->
<?php echo form_remote_tag('caja/muestraTramites','update: muestraTramites', 'name: formTramites')?>
	<table width="100%" style="margin-top:30px;">
	  <tr style="background:#F9B240; color:#FFFFFF;font-weight:bold; font-family:arial">
		<td colspan="4" align="center">
		  TIPO DE TRAMITES
		</td>
	  </tr>
	  <tr style="background: #D6D4D4; text-align:center;">
	    <td>
		  &nbsp;Tipo de tramite&nbsp;:&nbsp;&nbsp;
		  <select id="statusTramite" name="statusTramite">
		    <option value="Todos">Todos</option>
			<option value="0">Solicitados</option>
			<option value="1">En proceso</option>
			<option value="2">Entregados</option>
		  </select>
		</td>
		<td>
		  &nbsp;Estatus de pago&nbsp;:&nbsp;&nbsp;
		  <select id="statusPago" name="statusPago">
		    <!--<option value="Todos">Todos</option>-->
			<option value="0">Sin pagar&nbsp;&nbsp;&nbsp;</option>
			<option value="1">Pagado</option>
		  </select>
		</td>
		<td>
		  &nbsp;Tipo Persona:&nbsp;&nbsp;
		  <select id="tipoPersona" name="tipoPersona" onchange="muestraBusqueda();">
		    <option value="Todos">Todos</option>
			<option value="1">Alumno</option>
			<option value="2">Aspirante</option>
			<option value="4">Otros</option>
		  </select>
		</td>
	  </tr>
	  <tr>
	    <td align="center" >
		  <div id="busqueda" name="busqueda" style="display:none; height:50px; background: #F9CE8A; line-height: 48px;">
		    &nbsp;Registro&nbsp;&nbsp;<input type="text" id="registro" name="registro" onkeypress="javascript:return ValidNum(event)" maxlength="10"  style="width:165px;"/>
		  </div>
		</td>
		<td>
		</td>
		<td colspan="3" align="right">
		  <?php echo submit_tag('Buscar Tramites', 'id: boton', 'class: common_button', 'style: margin-top:20px;')?>
		</td>
	  </tr>
	</table>
<?php echo end_form_tag()?>

<!--En la siguiente div se mostraran los tramites solicitados-->
<div id="muestraTramites" name="muestraTramites">

</div>

<script type='text/javascript'>
//funcion que valida que solo se puedan ingresar numeros
function ValidNum(e)
{
  var tecla = document.all ? tecla = e.keyCode : tecla = e.which;
    return ((tecla > 47 && tecla < 58) || tecla == 8);
}

//Funcion que muestra el campo de busqueda
function muestraBusqueda()
{
  if(document.getElementById('tipoPersona').value == 1)
    document.getElementById('busqueda').style.display = "block";
	
  else
    document.getElementById('busqueda').style.display = "none";
}

//Se mandan los parametros a modificar
function updateTramite(tipoTram,idTram)
{ 
  var param = tipoTram + "," + idTram;
  
  new AJAX.viewRequest({ 
    action: "caja/updateTramite/"+param, 
	container: "muestraTramites" 
  }); 
}


//Funcion que muestra el mensaje de alerta
function mensajeAlerta(){
	if(document.getElementById('status').value == "FALSE"){
	  showDialog('ERROR',document.getElementById('msg').value,'error',2);
	}
}

</script> 