<div class="menu">	
	<a href="<?= KUMBIA_PATH ?>tgocalculo/apoyo">Apoyo Académico</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
    <a href="<?= KUMBIA_PATH ?>tgocalculo/estadisticas">Estadisticas de Fin de Curso</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>pagos/activarPago">Activar Pagos de Extras y Titulos</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>pagos/promocion">Promoci&oacute;n</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocalculo/salir">Salir</a>	
<div>