<center>
	<table border="1" align="center">
		<tr>
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesor/informacion"><? echo "Regresar al m&oacute;dulo de profesor" ?></a>
			</td>
		</tr>
	</table>
	<br />
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesoreshorario/horarioPorProfesor"><? echo "Horario por Profesor" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesoreshorario/horarioPorMateria"><? echo "Horario por Materia" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesoreshorario/horarioPorDivision"><? echo "Horario por Divisi&oacute;n" ?></a>
			</td>
		</tr>
	</table>
</center>