<?php
	$MaestroDivisiones = new MaestroDivisiones();
	if($maestroDivisiones = $MaestroDivisiones -> find_first("maestro_id = ".Session::get_data('registro'))){
	$Divisiones = new Divisiones();
		if($division = $Divisiones -> find_first("id = ".$maestroDivisiones -> division_id)){
			$nDiv = $division -> nombre;
		}
	}else{
		$nDiv ="Sin Division Asignada";
	}
?>
<center>
	<table border="1" style="font-size: 10px;" bordercolor="#003399">
		<tr>
			<td width="75" height="20" class="naranja">&nbsp;Nomina: </td>
			<td width="50" class="gris" align="center">&nbsp;<?= Session::get_data('registro') ?>&nbsp;</td>
			<td width="75" class="naranja">&nbsp;Nombre: </td>
			<td width="300" class="gris" align="center">&nbsp;<?= Session::get_data('nombre') ?>&nbsp;</td>
			<td width="75" height="20" class="naranja">&nbsp;División: </td>
			<td class="gris" align="center">&nbsp;<?= $nDiv ?>&nbsp;</td>
		</tr>
	</table>
</center>