<?php
$fecha=1;
			
	if ($fecha == 0){
		Flash::error('No es fecha oficial para guardar tu autoevaluacion');
	}else{
		echo "Esta es la Autoevaluaci&oacute;n del Parcial No. ".$parcial;
?>
<div id="autoevaluacionFinal">
<?php echo  form_remote_tag('tgoprofesor/agregarAutoevaluacionFinal/'.$tipo.'/'.$id.'/'.$parcial, 'update: autoevaluacionFinal') ?>
<table width="100%" class="bordeazul" style="font-size:10px;">
	<?php
		if($tipo == 0){
			$ActividadMaestro= new ActividadClase();							
		}
		if($tipo == 1){
			$ActividadMaestro = new ActividadMaestro();			
		}
		if($tipo == 2){
			$ActividadMaestro = new ActividadMaestroEspecial();																
		}
		$autoevaluacion = "autoevaluacion".$parcial;
		$avance = "avance".$parcial;
		$ActividadMaestro -> find_first("id = ".$id);
		
		
	?>
	<tr>
		<th colspan="3" class="naranja">Autoevaluaci&oacute;n Parcial <?= $parcial ?></th>
	</tr>
	<tr>
		<td>
			<textarea name="autoevaluacion" rows="6" style="width:100%;"><?php if ($ActividadMaestro -> $autoevaluacion!=""){ echo utf8_encode($ActividadMaestro -> $autoevaluacion ); }else{ echo "Escribe Aqu&iacute; la Autoevaluaci&oacute;n"; }  ?></textarea>
		</td>
	</tr>
	<tr>
		<td>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Avance Total 
			<select name="avance" style="width: 20%">
				<option value="<?= $ActividadMaestro -> $avance ?>"><?= $ActividadMaestro -> $avance ?></option>
				<?php for($i=100;$i>0;$i--){ ?>
				<option value="<?= $i ?>"><?= $i ?></option>
				<?php } ?>
			</select>  %
		</td>
	</tr>
	<tr>
		<td>
			<center>
				<input type="submit" value="GUARDAR">
			</center>
		</td>
	</tr>
</table>
<?= end_form_tag() ?>
</div>
<?php } ?>
