<?= render_partial("info"); ?>
<br>
<div id="encabezado">
	<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	INFORMACIÓN IMPORTANTE
</div>
<br />
<div class="azul">
<h2 class="naranja">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AVISO IMPORTANTE</h2>
<p style="padding-left:30px;">
<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
Se les comunica a todos los profesores que para mejores resultados en la captura de calificaciones se les recomienda el uso de exploradores WEB de ultima generaci&oacute;n, es decir Internet Explorer 8, y las ultimas versiones de Firefox, Safari, Opera o Chrome.
</p>
<p style="padding-left:30px;">Pueden acceder a las descargas desde <a href="https://ase.ceti.mx/tecnologo/general/descargas" style="color:#FF9900; font-weight:bold;">aqu&iacute;</a></p>
<br />
<p style="padding-left:30px;">
<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
Al igual les pedimos que revisen el estado final de las calificaciones ordinarias, ya que la evaluación se esta haciendo automáticamente al finalizar la captura del 3er Parcial; para las materias ponderadas revisar si esta correcta la ponderación de estas mismas.</p>
<p>
<h3 style="padding-left:30px;">Agredecemos de antemano su colaboraci&oacute;n.</h3>
</p>
</div>