 <?php 
 header("content-disposition: attachment;filename=programa_trabajo_academico.xls"); 
 ?>
 <center><br><br>
<style type="text/css">	
	.gris th{
		background: #999999;
		font-weight: bold;
		text-align: center;
		border: 1px  solid #000000;
	}
	.gris td{		
		border:  1px solid #000000;
	}
	
	.borde td{
		border:  1px solid #000000;
	}
	
	.borde th{
		border: 1px solid #000000;
	}
	
	.lineaAbajo{
		border-bottom: 1px solid #000000;
	}
	
	.centrado{
		text-align: center;
	}	
	
	table{
		padding: 0px;
		margin: 0px;
		font-size:6px;
		text-transform: uppercase;
	}
	td, th {
		vertical-align: top;
	}
	.sinNegrita{
		font-weight: none;
		font-size:6px;
	}
</style>
<?php
$Maestros = new Maestros();
$MestroDivisiones = new MaestroDivisiones();
$Divisiones = new Divisiones();

$maestro = $Maestros -> find_first("id = ".$nomina);
$maestroDivision = $MaestroDivisiones -> find_first("maestro_id = ".$nomina);
$division = $Divisiones -> find_first("id = ".$maestroDivision -> division_id);

?>
<table cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="29" bgcolor="#f9ac42" style="color:#000000">
			<img width="120" src="http://ase.ceti.mx/tecnologo/public/img/cira/logo.jpg"><center><h2>CENTRO DE ENSEÑANZA TÉCNICA INDUSTRIAL</h2></center>
		</td>
	</tr>
	<tr>
		<td colspan="29" bgcolor="#003399" style="color:#ffffff">
			<center><h3>PROGRAMA DE TRABAJO ACADÉMICO</h3></center>
		</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr class="gris">
		<th colspan="2">
			PLANTEL:
		</th>
		<td colspan="1">
			COLOMOS
		</td>
		<th>
			DIVISION:
		</th>
		<td colspan="12">
			<?= $division -> nombre ?>
		</td>
		<th colspan="3">
			ACADEMIA:
		</th>
		<td colspan="6">
			&nbsp;
		</td>
		<th colspan="2">
			PERIODO:
		</th>
		<td colspan="2">
			FEB - JUN 2009
		</td>		
	</tr>
	<tr class="gris">
		<th colspan="2">
			PROFESOR
		</th>
		<td colspan="12">
			<?= $maestro -> nombre ?>
		</td>
		<th colspan="4">
			NOMINA
		</th>
		<td colspan="5">
			<center><?= $nomina ?></center>
		</td>
		<th colspan="4">
			HORAS NOMBRAMIENTO
		</th>
		<td colspan="2">
			<?= $cuantasHoras ?> Hrs.
		</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr class="gris">
		<th rowspan="2"  width="35">
			CLAVE
		</th>
		<th rowspan="2" width="60">
			ACTIVIDAD
		</th>
		<th rowspan="2"  width="60">
			OBJETIVO
		</th>
		<th rowspan="2"  width="60">
			META
		</th>
		<th colspan="18">
			SEMANA
		</th>
		<th rowspan="2">
			TOTAL<BR>HORAS			
		</th>
		<th rowspan="2">
			EVALUACION<BR>
			1er PARCIAL
		</th>
		<th rowspan="2">
			%<BR>
			AVANCE
		</th>
		<th rowspan="2">
			EVALUACION<BR>
			2do PARCIAL
		</th>
		<th rowspan="2">
			%<BR>
			AVANCE
		</th>
		<th rowspan="2">
			EVALUACION<BR>
			3ro PARCIAL
		</th>
		<th rowspan="2">
			%<BR>
			AVANCE
		</th>
	</tr>
	<tr class="gris">
		<?php for($i=1;$i<19;$i++){ ?><th  style="font-size:6px"><?= $i ?></th><?php } ?>
	</tr>
	<?php
	$Horas = new Horas();
	$Actividad = new Actividades();	
	$ActividadClase = new ActividadClase();	
	$ActividadesMaestro = new ActividadMaestro();
	$ActividadesMaestroEspecial = new ActividadMaestroEspecial();
	
	$Actividad -> find_first("id = 1");	
	$horas = $Horas -> count("maestro_id = ".$nomina." and periodo = ".$periodo);	
	?>	
	<tr class="borde">
		<td  class="centrado"><?= $Actividad -> numero ?></td>
		<td><?= $Actividad -> categoria." - ".$Actividad -> actividad ?></td>
		<td>ATENDER CON CALIDAD, ETICA Y PROFESIONALISMO LOS GRUPOS ASIGNADOS EN EL HORARIO OFICIAL DE CLASES RESPETANDO LOS LINEAMIENTOS ESTABLECIDOS POR LA ACADEMIA EN CADA ASIGNATURA.</td>
		<td>CUBRIR CON EL 100% DE LOS CONTENIDOS TEMATICOS, CON EL 0% DE INCIDENCIAS EN CLASES.</td>		<?	
		for($i=1;$i<19;$i++){ 			
			$totalSemana[$i]=$totalSemana[$i]+$horas;		
		?>
		<td class="centrado"  style="font-size:6px"><?= $horas ?></td>
		<?php 		
		} 
		$totalSemana[19]=$totalSemana[19]+(($horas)*18);
		?>
		<td class="centrado" style="font-size:6px"><?= ($horas)*18 ?></td>		
		<?php		
		if($ActividadClase -> find_first("maestro_id = ".$nomina)){
		?>		
		<td><?=  $ActividadClase -> autoevaluacion1 ?></td>
		<td><?=  $ActividadClase -> avance1 ?></td>
		<td><?=  $ActividadClase -> autoevaluacion2 ?></td>
		<td><?=  $ActividadClase -> avance2 ?></td>
		<td><?=  $ActividadClase -> autoevaluacion3 ?></td>
		<td><?=  $ActividadClase -> avance3 ?></td>
		<?php }else{?>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<?php } ?>
	</tr>
	<?php
	if($actividadesMaestro = $ActividadesMaestro -> find("maestro_id = ".$nomina." and periodo = ".$periodo)){
		foreach($actividadesMaestro as $am){ 
			if($Actividad -> find_first("id = ".$am -> actividad_id)){
	?>
	<tr class="borde">
		<td  class="centrado"><?= $Actividad -> numero ?></td>
		<td><?= $Actividad -> categoria." - ".$Actividad -> actividad ?></td>
		<td><?= utf8_decode($am -> objetivo) ?></td>
		<td><?= utf8_decode($am -> meta) ?></td>		
		<?php 
		$totalHrs=0;		
		for($i=1;$i<19;$i++){ 
			$var = "s".$i;
			$totalSemana[$i] = $totalSemana[$i] + $am -> $var;
			$totalHrs = $totalHrs + $am -> $var;
		?>
		<td class="centrado"><?= $am -> $var ?></td>
		<?php 		
		} 
		$totalSemana[19]=$totalSemana[19]+$totalHrs;
		?>
		<td class="centrado"><?= $totalHrs ?></td>
		<td><?= $am -> autoevaluacion1 ?></td>
		<td class="centrado"><?= $am -> avance1 ?></td>
		<td><?= $am -> autoevaluacion2 ?></td>
		<td class="centrado"><?= $am -> avance2 ?></td>
		<td><?= $am -> autoevaluacion3 ?></td>
		<td class="centrado"><?= $am -> avance3 ?></td>
	</tr>
	<?php 
			}
		}
	} 
	
	if($actividadesMaestro = $ActividadesMaestroEspecial -> find("maestro_id = ".$nomina." and periodo = ".$periodo)){
		foreach($actividadesMaestro as $am){ 		
	?>
	<tr class="borde">
		<td  class="centrado"><?= $am -> id ?></td>
		<td><?= utf8_decode($am -> nombre) ?></td>
		<td><?= utf8_decode($am -> objetivo) ?></td>
		<td><?= utf8_decode($am -> meta) ?></td>		
		<?php 
		$totalHrs=0;
		for($i=1;$i<19;$i++){ 
			$var = "s".$i;
			$totalSemana[$i] = $totalSemana[$i] + $am -> $var;
			$totalHrs = $totalHrs + $am -> $var;
		?>
		<td class="centrado"><?= $am -> $var ?></td>
		<?php 
		} 
		$totalSemana[19]=$totalSemana[19]+$totalHrs;
		?>
		<td class="centrado"><?= $totalHrs ?></td>
		<td><?= $am -> autoevaluacion1 ?></td>
		<td class="centrado"><?= $am -> avance1 ?></td>
		<td><?= $am -> autoevaluacion2 ?></td>
		<td class="centrado"><?= $am -> avance2 ?></td>
		<td><?= $am -> autoevaluacion3 ?></td>
		<td class="centrado"><?= $am -> avance3 ?></td>
	</tr>
	<?php 
		}
	} ?>
	<tr class="gris">
		<td colspan="3">&nbsp;</td>
		<th>TOTALES</th>
		<?php 		
		for($i=1;$i<20;$i++){ 
		?>
		<th class="centrado"><?= $totalSemana[$i] ?></th>
		<?php
		}
		?>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<th colspan="3">ELABORÓ</th>
		<td colspan="8">&nbsp;</td>
		<th colspan="11">Vo.Bo.</th>
		<td colspan="2">&nbsp;</td>		
		<th colspan="4">AUTORIZÓ</th>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="3" class="lineaAbajo">&nbsp;</td>		
		<td colspan="8">&nbsp;</td>
		<td colspan="11" class="lineaAbajo">&nbsp;</td>
		<td colspan="2">&nbsp;</td>
		<td colspan="4" class="lineaAbajo">&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<th colspan="3"><?= $maestro -> nombre ?></th>
		<td colspan="8">&nbsp;</td>
		<?php		
		$coordinador = $Maestros -> find_first("id = ".$division -> maestro_id);
		?>
		<td colspan="11"  class="centrado"><b><?= $coordinador -> nombre ?></b><br><span class="sinNegrita">COORDINACIÓN DE <?= $division -> nombre ?></span></td>
		<td colspan="2">&nbsp;</td>
		<td colspan="4" class="centrado"><b>ING. CARLOS JESAHEL VEGA GOMEZ</b><br>JEFATURA DE NIVEL TECNÓLOGO</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="29">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<th colspan="3">FR-02-DI-MN-200-05-01</th>		
		<th colspan="21">&nbsp;</th>		
		<th colspan="4">REV. B</th>
		<td>&nbsp;</td>
	</tr>	
</table>
</center>
<?php

?>
