<div class="menu">
	<a href="<?= KUMBIA_PATH ?>tgoprofesor/index">Entrar como Profesor</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgotutor/asignacion">Asignacion</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgotutor/busqueda">Busqueda</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgotutor/estadisticas">Estadisticas</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgotutor/salir">Salir</a>
<div>