<div class="menu">
	<a href="<?= KUMBIA_PATH ?>tgoprofesor/informacion" onmouseover="toolTip('Entrar al modulo de Profesor',this)" >Entrar como Prof.</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;	
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/profesores" onmouseover="toolTip('Listado de profesores asignados a su división',this)">Profesores</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/infraestructura" onmouseover="toolTip('Salones disponibles en todo<br>CETI Plantel Colomos',this)">Salones</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;	
	<a href="<?= KUMBIA_PATH ?>salones/infraestructura" onmouseover="toolTip('Horario de Salones para prefectura',this)">Prefectura</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;	
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/grupos" onmouseover="toolTip('Listado de Grupos disponibles para esta división',this)">Grupos</a><!--
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/horarios" onmouseover="toolTip('Modulo de Asignación de Horarios<br>a Profesores de la División',this)">Horarios</a>-->
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>irregular/asignarIrregular/830001" onmouseover="toolTip('Modulo de asignación de<br>Matrias a alumnos',this)">Asignacion</a>	
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/apoyo" onmouseover="toolTip('Modulo de tickets enviados<br> por los alumnos',this)">Apoyo Académico</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/buscar" onmouseover="toolTip('Buscador de alumnos, aqui podras<br>entrar a la sesión del alumno',this)">Buscar Alumnos</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/salir" onmouseover="toolTip('Salir del Sistema de Control Escolar',this)">Salir</a>
<div>