<center>
	<table border="1" style="font-size: 10px;" bordercolor="#003399">
		<tr>
			<td width="75" height="20" class="naranja">&nbsp;Nomina: </td>
			<td width="50" class="gris" align="center">&nbsp;<?= Session::get_data('registro') ?>&nbsp;</td>
			<td width="75" class="naranja">&nbsp;Nombre: </td>
			<td width="300" class="gris" align="center">&nbsp;<?= Session::get_data('nombre') ?>&nbsp;</td>
			<td width="75" height="20" class="naranja">&nbsp;División: </td>
			<td class="gris" align="center">&nbsp;<?= Session::get_data('coordinacion') ?>&nbsp;</td>
		</tr>
	</table>
</center>