<?php echo form_remote_tag("tgocoordinador/buscando", "update: listado") ?>
<center>
<table class="bordeAzul" style="font-size:11px;">
	<tr class="naranja">
		<th colspan="3">BUSCADOR DE ALUMNOS</th>
	</tr>
	<tr class="azul">
		<th>REGISTRO</th>
		<th>y/o</th>
		<th>NOMBRE</th>
	</tr>
	<tr>
		<th><?= text_field_tag("registro") ?></th>
		<th class="grisClaro">&nbsp;</th>
		<th><?= text_field_tag("nombre") ?></th>
	</tr>
	<tr class="grisClaro">
		<td colspan="3">
			<center>
				<?php echo submit_tag("Buscar") ?>
			</center>
		</td>
	</tr>	
</table>
<?php echo end_form_tag() ?>
</center>
<br />
<div id='listado'>
</div>
