<style type="text/css">
	a img{
		display: block;
		text-align: center;
	}
</style>
<?= render_partial("info"); ?>
<br>
<div id="encabezado">
	<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	CONTROL DE GRUPOS
	<br><br>
	<table border="0">
		<tr>
			<td width="440" valign="top">
				<?= form_remote_tag("tgocoordinador/agregarcurso","update: listado") ?>
				<table border="1" class="bordeazul" style="font-size:10px;">
					<tr>
						<th width="440" height="20" class="naranja" colspan="2">
							AGREGAR GRUPOS
						</th>
					</tr>
					<tr>
						<th class="azul">
							Nombre
						</th>
						<th class="azul">
							Especialidad
						</th>
					</tr>
					<tr>
						<th>
							<input type="text" name="nombre" style="width:50px; text-align:center; text-transform:uppercase;" MAXLENGTH="3">
						</th>
						<th>
							<select name="especialidad" style="width:290px;">
								<option value=""></option>
								<?php if($especialidades) foreach($especialidades as $especialidad) { ?>
									<option value="<?= $especialidad -> id ?>"><?= $especialidad -> id ?> - <?= $especialidad -> nombre ?></option>
								<?php } ?>
							</select>
							<!-- DESACTIVAR EL BOTON AGREGAR <input type="submit" value="Agregar" DISABLED> -->
							<input type="submit" value="Agregar" DISABLED />
						</th>
					</tr>
				</table>
				<?= end_form_tag() ?>
				<div id="listado">
					<table border="1" style="font-size:10px;" class="bordeazul">
					<tr>
						<th width="440" colspan="5" class="naranja">
							GRUPOS REGISTRADOS PARA ESTE SEMESTRE
						</th>
					</tr>
					<tr>
						<th width="50" class="azul">
							Nombre
						</th>
						<th class="azul">
							Especialidad
						</th>
						<th width="20" height="20" class="gris">
							<center>
							<?= link_to_remote('<img src="'.KUMBIA_PATH.'public/img/prev.gif" border=0>',"update: listado","action: tgocoordinador/gruposajax/".$p1); ?>
							<center>
						</th>						
						<th width="20" height="20" class="gris">
							<center>
							<?= link_to_remote('<img src="'.KUMBIA_PATH.'public/img/next.gif" border=0>',"update: listado","action: tgocoordinador/gruposajax/".$p2); ?>
							<center>
						</th>
					</tr>
					<?php if($listado) foreach($listado as $grupo){ ?>
					<tr>
						<td width="50" height="20" align="center">
							<?= $grupo -> nombre ?>
						</td>
						<td width="340">
							<?php if($especialidades) foreach($especialidades as $especialidad) { ?>
								<?php if($especialidad -> id == $grupo -> especialidad_id){?>&nbsp;<?= $especialidad -> nombre ?><?php } ?>
							<?php } ?>
							
						</td>
						<th width="20" height="20">
							<center>
							<?= link_to_remote('<img src="'.KUMBIA_PATH.'public/img/calendar.gif" border=0>',"update: jornada","action: tgocoordinador/jornadagrupo/".$grupo -> id); ?>
							</center>
						</th>
						<th width="20" height="20">
							<!-- 
								Para desactuvar el borrar
							<img src="<?= KUMBIA_PATH ?>public/img/delete.png" border=0>
							--> 
							<center>
							<?php //echo link_to_remote('<img src="'.KUMBIA_PATH.'public/img/delete.png" border=0>',"update: listado","action: tgocoordinador/quitargrupo/".$grupo -> id, "confirm: Estas seguro que quieres borrar este grupo?"); 
							?>
							</center>
						</th>
					</tr>
					<?php } ?>
				</table>
				</div>
			</td>
			<td width="50">&nbsp;</td>
			<td width="460" valign="top">
				<div id="jornada">
					<?= render_partial("horario"); ?>
				</div>
			</td>
		</tr>
	</table>