<?= render_partial("info"); ?>
<?php
	$x=1;
	
	function horario($maestro, $auxiliar){
		$horarios = new Horarios();
		
		if($horarios -> count("maestro_id=".$maestro." AND auxiliar=".$auxiliar)==0){
			return '';
		}
		else{
			$horario = $horarios -> find_first("maestro_id=".$maestro." AND auxiliar=".$auxiliar);
			return $horario;
		}
	}
	
	function materia($maestro, $auxiliar){		
		$horarios = new Horarios();
		$Periodo = new Periodos();
		if($Periodo -> find_first("activo = 1")){			
			$periodo = $Periodo -> periodo;
		}else{ echo "No se encontro ningun periodo activo<br />"; }
		
		if($horarios -> count("maestro_id=".$maestro." AND periodo=".$periodo)>0){
			$horarios = $horarios -> find("maestro_id=".$maestro." AND periodo=".$periodo);
			if($horarios) foreach($horarios as $horario){
				$horas = new Horas();
				if($horas -> count("periodo = ".$periodo." and horario_id=".$horario -> id." AND auxiliar=".$auxiliar)){
					$hora = $horas -> find_first("horario_id=".$horario -> id." and periodo = ".$periodo." AND auxiliar=".$auxiliar);
					
					$materias = new MateriasHorarios();
					$materia = $materias -> find_first("id=".$hora -> materia_id);
					
					return $materia -> nombre;
				}
			}
		}
		
		return '-';
	}
	
	function grupo($maestro, $auxiliar){
		$horarios = new Horarios();		
		$Periodo = new Periodos();
		if($Periodo -> find_first("activo = 1")){			
			$periodo = $Periodo -> periodo;
		}else{ echo "No se encontro ningun periodo activo<br />"; }
		
		if($horarios -> count("maestro_id=".$maestro." AND periodo=".$periodo)>0){
			$horarios = $horarios -> find("maestro_id=".$maestro." AND periodo=".$periodo);
			if($horarios) foreach($horarios as $horario){
				$horas = new Horas();
				if($horas -> count("horario_id=".$horario -> id." and periodo = ".$periodo." AND auxiliar=".$auxiliar)){
					$hora = $horas -> find_first("horario_id=".$horario -> id." and periodo = ".$periodo." AND auxiliar=".$auxiliar);
					
					$grupos = new Grupos();
					$grupo = $grupos -> find_first("id=".$hora -> grupo_id);
					return $grupo -> nombre;
				}
			}
		}
		
		return '-';
	}
	
	function salon($maestro, $auxiliar){
		$horarios = new Horarios();		
		$Periodo = new Periodos();
		if($Periodo -> find_first("activo = 1")){			
			$periodo = $Periodo -> periodo;
		}else{ echo "No se encontro ningun periodo activo<br />"; }
		
		if($horarios -> count("maestro_id=".$maestro." AND periodo=".$periodo)>0){
			$horarios = $horarios -> find("maestro_id=".$maestro." AND periodo=".$periodo);
			if($horarios) foreach($horarios as $horario){
				$horas = new Horas();
				if($horas -> count("horario_id=".$horario -> id." and periodo = ".$periodo." AND auxiliar=".$auxiliar)){
					$hora = $horas -> find_first("horario_id=".$horario -> id." and periodo = ".$periodo." AND auxiliar=".$auxiliar);
					
					$salones = new Salones();
					$salon = $salones -> find_first("id=".$hora -> salon_id);
					return $salon -> corto;
				}
			}
		}
		
		return '-';
	}
	
?>
<br>
<style type="text/css">
	SELECT, INPUT{
		font-size:10px;
	}
	.actasCargadas a{
		display: block;
		color: #000000;		
		text-decoration: none;
	}
	.actasCargadas a:hover{		
		background-color: #990000;		
		color: #ffffff;
	}
</style>
<div id="encabezado">
	<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	ADMINISTRACIÓN DE HORARIOS
</div>
<div align="right">
	<form method="POST" action="<?= KUMBIA_PATH ?>tgocoordinador/horarios">
		<select name="profesor">
			<?php if($maestros) foreach($maestros as $maestro1){ ?>
				<option value="<?= $maestro1 -> id ?>"><?= utf8_encode($maestro1 -> nombre) ?></option>
			<?php } ?>
		</select>
		<input type="submit" value="Horario">
	</form>
</div>
<div class="cargarActas" id="cargarActas">
	<?php		
	$Materias = new MateriasHorarios();
	$Grupos = new Grupos();	
	$Periodo = new Periodos();
	if($Periodo -> find_first("activo = 1")){			
		$periodo = $Periodo -> periodo;
	}else{ echo "No se encontro ningun periodo activo<br />"; }	
	
	$Divisiones = new Divisiones();
	if($Divisiones -> find_first("maestro_id = ".Session::get_data('registro'))){
			if($Divisiones -> id == 160 || $Divisiones -> id == 110){
				$divisiong_id = "";
			}else{
				$divisiong_id = " and especialidad_id = ".$Divisiones -> id." ";		
			}
			$division_id = $Divisiones -> id;		
	}else{
		echo "no se hayo la division";
		$division_id = 999;
	}
	
	if($grupos = $Grupos -> find("periodo = ".$periodo." ".$divisiong_id." order by nombre ASC")){
		if($materias = $Materias -> find("division_id = ".$division_id,"order: division_id ASC, plan ASC, clave ASC")){		
		//if($materias = $Materias -> find("order: division_id ASC, clave ASC, plan ASC")){
			echo "<center>";
			echo form_remote_tag("tgocoordinador/agregarActa", "update: actasCargadas");
			echo '<table cellpadding="" cellspacing="" class="bordeAzul" style="font-size:10px" width="500">';
			echo '<tr><th colspan="4" class="naranja">Agregar Acta al profesor '.utf8_encode($propietario).' '.$maestro -> id.'</th></tr>';
			echo '<tr class="azul"><th>Materia</th><th>Grupo</th><th>&nbsp;</th></tr>';
			echo '<tr>';
				echo '<th><select name="materia_id">';
					foreach($materias as $materia){
						echo '<option value="'.$materia -> id.'">'.$materia -> clave.' - '.$materia -> nombre.' - '.$materia -> plan.'</option>';
					}
				echo '</select></th>';
				echo '<th><select name="grupo_id">';
					foreach($grupos as $grupo){
						echo '<option value="'.$grupo -> id.'">'.$grupo -> nombre.'</option>';
					}
				echo '</select></th>';
				echo '<th>';
					echo '<input type="hidden" name="maestro_id" value="'.$maestro -> id.'" />';					
					if(Session::get_data('registro') == 2351 || Session::get_data('registro') == 2351 ){
						echo submit_tag("Agregar");
					}else{
						echo submit_tag("Agregar", "disabled: disabled");
					}
				echo '</th>';
			echo '</tr>';
			echo '</table>';
			echo end_form_tag();
			echo "</center>";
		}else{ echo "No se encontro ninguna Materia"; }
	}else{ echo "No se encontro ningun Grupo "; }
	
	?>

</div>
<div class="actasCargadas" id="actasCargadas">
<?= render_partial("actasCargadas") ?>
</div>
<?php 
	$horas = array("7:00 - 7:55","7:55 - 8:50","9:30 - 10:25","10:25 - 11:20","11:20 - 12:15","12:15 - 13:10","13:10 - 14:05","14:05 - 15:00","15:00 - 15:55","15:55 - 16:50","16:50 - 17:45","17:45 - 18:40","18:40 - 19:35","19:35 - 20:30"); 
	if($turno=='M'){ 
?>
		<table border="1" style="font-size:10px;" class="bordeazul">
			<th height="20" class="naranja" colspan="7">
				<?= utf8_encode($propietario) ?>
			</th>
			<tr>
				<td width="100" align="center" class="azul">&nbsp;</td>
				<th width="150" align="center" class="azul">Lunes</th>
				<th width="150" align="center" class="azul">Martes</th>
				<th width="150" align="center" class="azul">Miercoles</th>
				<th width="150" align="center" class="azul">Jueves</th>
				<th width="150" align="center" class="azul">Viernes</th>
				<th width="150" align="center" class="azul">Sábado</th>
			</tr>
			<?php for($i=0;$i<2;$i++){ ?>
			<tr>
				<th height="125" class="naranja"><?= $horas[$i] ?></th>
				<?php for($j=1;$j<7;$j++){ ?>
				<?= form_remote_tag("tgocoordinador/abrirhorario/".$x."/".$maestro -> id,"update: horario".$x) ?>
					<?php if(materia($maestro -> id, $x)=="-"){	?>
						<td bgcolor="#FFFFFF" align="center" style="font-weight:none;">
					<?php } else { ?>
						<th bgcolor="#CCCCCC">
					<?php }	?>
							<div id="horario<?= $x ?>">
								<?php if(materia($maestro -> id, $x)=="-"){	?>
									&nbsp;
								<?php } else { ?>
									<?= materia($maestro -> id, $x); ?><br><br><?= grupo($maestro -> id, $x); ?> - <?= salon($maestro -> id, $x); ?><br><br>
								<?php }	?>
								<?php $x++; ?>
								<input type="submit" name="boton" value="Modificar">
							</div>
						</td>
				<?= end_form_tag() ?>
				<?php } ?>
			</tr>
			<?php } ?>
			<tr>
				<th height="10" class="naranja">8:50 - 9:30</th>
				<th colspan="6" class="negro">RECESO</th>
			</tr>
			<?php for($i=2;$i<8;$i++){ ?>
			<tr>
				<th height="125" class="naranja"><?= $horas[$i] ?></th>
				<?php for($j=1;$j<7;$j++){ ?>
				<?= form_remote_tag("tgocoordinador/abrirhorario/".$x."/".$maestro -> id,"update: horario".$x) ?>
					<?php if(materia($maestro -> id, $x)=="-"){	?>
						<td bgcolor="#FFFFFF" align="center" style="font-weight:none;">
					<?php } else { ?>
						<th bgcolor="#CCCCCC">
					<?php }	?>
							<div id="horario<?= $x ?>">
								<?php if(materia($maestro -> id, $x)=="-"){	?>
									&nbsp;
								<?php } else { ?>
									<?= materia($maestro -> id, $x); ?><br><br><?= grupo($maestro -> id, $x); ?> - <?= salon($maestro -> id, $x); ?><br><br>
								<?php }	?>
								<?php $x++; ?>
								<input type="submit" name="boton" value="Modificar">
							</div>
						</td>
				<?= end_form_tag() ?>
				<?php } ?>
			</tr>
			<?php } ?>
			<tr>
				<th height="10" class="naranja">TARDE</th>
				<th colspan="6" class="negro">TURNO VESPERTINO</th>
			</tr>
			<?php for($i=8;$i<14;$i++){ ?>
			<tr>
				<th height="125" class="naranja"><?= $horas[$i] ?></th>
				<?php for($j=1;$j<7;$j++){ ?>
				<?= form_remote_tag("tgocoordinador/abrirhorario/".$x."/".$maestro -> id,"update: horario".$x) ?>
					<?php if(materia($maestro -> id, $x)=="-"){	?>
						<td bgcolor="#FFFFFF" align="center" style="font-weight:none;">
					<?php } else { ?>
						<th bgcolor="#CCCCCC">
					<?php }	?>
							<div id="horario<?= $x ?>">
								<?php if(materia($maestro -> id, $x)=="-"){	?>
									&nbsp;
								<?php } else { ?>
									<?= materia($maestro -> id, $x); ?><br><br><?= grupo($maestro -> id, $x); ?> - <?= salon($maestro -> id, $x); ?><br><br>
								<?php }	?>
								<?php $x++; ?>
								<input type="submit" name="boton" value="Modificar">
							</div>
						</td>
				<?= end_form_tag() ?>
				<?php } ?>
			</tr>
			<?php } ?>
		</table>
		<br>
<?php
	} 
 ?>