<?= render_partial("info"); ?>
<br>
<div id="encabezado">
	<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	INFORMACIÓN IMPORTANTE
</div>
<BR>
<div>
<h2>AVISO IMPORTANTE</h2>
<p>
Se les comunica a todos los profesores que para mejores resultados en la captura de calificaciones se les recomienda el uso de exploradores WEB de ultima generaci&oacute;n, es decir Internet Explorer 8, y las ultimas versiones de Firefox, Safari, Opera o Chrome.
</p>
<br />
<p>
<h3>Agredecemos de antemano su colaboraci&oacute;n.</h3>
</p>
</div>
