<?php
	$x=1;
	
	function horario($grupo, $auxiliar){
		$horarios = new Horarios();
		
		if($horarios -> count("grupo_id=".$grupo." AND auxiliar=".$auxiliar)==0){
			return '';
		}
		else{
			$horario = $horarios -> find_first("grupo_id=".$grupo." AND auxiliar=".$auxiliar);
			return $horario;
		}
	}
	
	function materia($grupo, $auxiliar){
		$horarios = new Horarios();
		$Periodo = new Periodos();
		if($Periodo -> find_first("activo = 1")){			
			$periodo = $Periodo -> periodo;
		}else{ echo "No se encontro ningun periodo activo<br />"; }
		
		if($horarios -> count("grupo_id=".$grupo." AND periodo=".$periodo)>0){
			$horarios = $horarios -> find("grupo_id=".$grupo." AND periodo=".$periodo);
			if($horarios) foreach($horarios as $horario){
				$horas = new Horas();
				if($horas -> count("horario_id=".$horario -> id." AND auxiliar=".$auxiliar)){
					$hora = $horas -> find_first("horario_id=".$horario -> id." AND auxiliar=".$auxiliar);
					
					$materias = new MateriasHorarios();
					$materia = $materias -> find_first("id=".$hora -> materia_id);
					
					return $materia -> nombre;
				}
			}
		}
		
		return '-';
	}
	
	function grupo($grupo, $auxiliar){
		$horarios = new Horarios();
		$Periodo = new Periodos();
		if($Periodo -> find_first("activo = 1")){			
			$periodo = $Periodo -> periodo;
		}else{ echo "No se encontro ningun periodo activo<br />"; }
		
		if($horarios -> count("grupo_id=".$grupo." AND periodo=".$periodo)>0){
			$horarios = $horarios -> find("grupo_id=".$grupo." AND periodo=".$periodo);
			if($horarios) foreach($horarios as $horario){
				$horas = new Horas();
				if($horas -> count("horario_id=".$horario -> id." AND auxiliar=".$auxiliar)){
					$hora = $horas -> find_first("horario_id=".$horario -> id." AND auxiliar=".$auxiliar);
					
					$grupos = new Grupos();
					$grupo = $grupos -> find_first("id=".$hora -> grupo_id);
					return $grupo -> nombre;
				}
			}
		}
		
		return '-';
	}
	
	function salon($grupo, $auxiliar){
		$horarios = new Horarios();
		
		if($horarios -> count("grupo_id=".$grupo." AND periodo=".$periodo)>0){
			$horarios = $horarios -> find("grupo_id=".$grupo." AND periodo=".$periodo);
			if($horarios) foreach($horarios as $horario){
				$horas = new Horas();
				if($horas -> count("horario_id=".$horario -> id." AND auxiliar=".$auxiliar)){
					$hora = $horas -> find_first("horario_id=".$horario -> id." AND auxiliar=".$auxiliar);
					
					$salones = new Salones();
					$salon = $salones -> find_first("id=".$hora -> salon_id);
					return $salon -> corto;
				}
			}
		}
		
		return '-';
	}
	
?>
<br>
<style type="text/css">
	SELECT, INPUT{
		font-size:10px;
	}
</style>
<div id="encabezado">
	<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	ADMINISTRACIÓN DE HORARIOS
	<br><br>
	<?php 
		$ok = 0;
		$horas = array("7:00 - 7:55","7:55 - 8:50","9:30 - 10:25","10:25 - 11:20","11:20 - 12:15","12:15 - 13:10","13:10 - 14:05","14:05 - 15:00","15:00 - 15:55","15:55 - 16:50","16:50 - 17:45","17:45 - 18:40","18:40 - 19:35","19:35 - 20:30"); 
		?>
		
					<table border="1" style="font-size:10px;" class="bordeazul">
						<th height="20" class="naranja" colspan="7">
							<?= utf8_encode($especialidad) ?>
						</th>
						<tr>
							<td width="100" align="center" class="azul">&nbsp;</td>
							<th width="150" align="center" class="azul">Lunes</th>
							<th width="150" align="center" class="azul">Martes</th>
							<th width="150" align="center" class="azul">Miercoles</th>
							<th width="150" align="center" class="azul">Jueves</th>
							<th width="150" align="center" class="azul">Viernes</th>
							<th width="150" align="center" class="azul">Sábado</th>
						</tr>
						<?php for($i=0;$i<8;$i++){ ?>
						<tr>
							<th height="125" class="naranja"><?= $horas[$i] ?></th>
							<?php for($j=1;$j<7;$j++){ ?>
								<?php if(materia($grupoid, $x)=="-" && materia($grupobasicasid, $x) =="-"){	?>
									<td bgcolor="#FFFFFF" align="center" style="font-weight:none;">
								<?php } else { ?>
									<th bgcolor="#CCCCCC">
								<?php }	?>
										<div id="horario<?= $x ?>">
											<?php if(materia($grupoid, $x)=="-"){	?>
												<?php if(materia($grupobasicasid, $x)=="-"){	?>
													&nbsp;
												<?php } else { ?>
													<?= materia($grupobasicasid, $x); ?><br><br><?= grupo($grupobasicasid, $x); ?> - <?= salon($grupobasicasid, $x); ?><br><br>
												<?php }	?>
											<?php } else { ?>
												<?= materia($grupoid, $x); ?><br><br><?= grupo($grupoid, $x); ?> - <?= salon($grupoid, $x); ?><br><br>
											<?php }	?>
											<?php $x++; ?>
										</div>
									</td>
							<?php } ?>
						</tr>
						<?php } ?>
					</table><br>
					<?php if($xcurso==0){ ?>
						<center>
							<form method="POST" action="<?= KUMBIA_PATH ?>grupo/autorizar/<?= $gpo ?>">
								<input type="submit" value="AUTORIZAR HORARIO">
							</form>
						</center>
					<?php } ?>
					<br>
			