<div class="menu">	
	<a href="<?= KUMBIA_PATH ?>ventanilla/aspirantes">Aspirantes</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>ventanilla/calificaciones">Boletas de Calificaciones</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>ventanilla/kardex">Kardexs</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>ventanilla/salir">Salir</a>
<div>