<script language="JavaScript1.2">

function validateFields(){
	
	var err = "";
	var i;
	var j;
		
	for( i = 7; i < 22; i++ ){
		for( j = 1; j < 7; j++ ){
			// if( document.Formulario1.elements["salon"+"["+i+"]["+j+"]"].value == null ){
			if( document.Formulario1.elements["flag1"+"["+i+"]["+j+"]"].value == 0 ){
				
			}
			else if( document.Formulario1.elements["salon"+"["+i+"]["+j+"]"].value != -1 ){
				aux++;
			}
		}
	}
	
	if( err != "" ){
		alert(err);
		return false;
	}
	else{
		return true;
	}
	
</script>
		<style type="text/css">
			.linknegrita a:hover{
				font-weight: bold;
				text-decoration: none;
				color:#000000;
			}
			.linknegrita a{
				font-weight: none;
				text-decoration: none;
				color:#000000;
			}
		</style>
<script type='text/javascript'>
</script>
			<table  border="1" cellpadding="1" cellspacing="1" style="font-size: 10px;">
		<table border="0" cellpadding="0" cellspacing="0" align="center">
			<tr>
				<td style="font-family: Verdana;" align="center">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>ASPIRANTES - PANEL DE CONTROL</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<form name="Formulario1" id="Formulario1" 
						action="<?= KUMBIA_PATH ?>aspirantes/creandoAlumno" method="post" >
							<!-- onSubmit="return validateFields();" > -->
					<br />
						<br /><br />
						<div style="color: #000000; font-size: 20px;" align="center">
						</div>
						<br />
						<div id="datos">
						<div style="color: #000000; font-size: 20px;" align="center">
							<b><?= $periodoo ?></b></div>
						<br />
						<br />
						<center>
						<table border="0" style="font-size:12px;" align="center">
						<tr>
							<th width="50" class="fondoazul" align="center">
								<b>FICHA</b>
							</th>
							<th width="50" class="fondoazul" align="center">
								<b>FOLIO</b>
							</th>
							<th width="150" class="fondoazul" align="center">
								<b>TIPO ASPIRANTE</b>
							</th>
							<th width="50" class="fondoazul" align="center">
								<b>CARRERA</b>
							</th>
							<th width="50" class="fondoazul" align="center">
								<b>PLANTEL</b>
							</th>
							<th width="300" class="fondoazul" align="center">
								<b>NOMBRE</b>
							</th>
							<th width="100" class="fondoazul" align="center">
								<b>AGREGAR REGISTRO</b>
							</th>
						</tr>
						<?php
							for( $i = 0; $i < $iiii; $i++ ){
						?>
							<tr>
								<td width="50" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $ficha[$i] ?>
								</td>
								<td width="50" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $folio[$i] ?>
								</td>
								<td width="150" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<?
									if( $tipoAspirante[$i] == 1 )
										echo "Pago de Derecho";
									else if( $tipoAspirante[$i] == 2 )
										echo "Continuaci&oacute;n de Estudios";
									else if( $tipoAspirante[$i] == 0 || 
												$tipoAspirante[$i] == "" || 
													$tipoAspirante[$i] == null )
										echo "NO DISPONIBLE";
									?>
								</td>
								<td width="50" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $carrera[$i] ?>
								</td>
								<td width="50" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo strtoupper(substr($plantel[$i], 0, 1)); ?>
								</td>
								<td width="300" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo substr(utf8_encode($nombre[$i]." ".$paterno[$i]." ".$materno[$i]), 0, 45);  ?>
								</td>
								<td width="150" valign="center" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<input type="text" style="width:125px; text-align:center; 
											color:#000;" name="registro<?echo "[$i]" ?>" 
												id="registro<?echo "[$i]" ?>" value="<?= $registro[$i] ?>"
												class="cielo" <? if( $registro[$i] != 0 ) echo "DISABLED" ?>>
									<input type="hidden" name="idAspirante<?echo "[$i]" ?>" 
										id="idAspirante<?echo "[$i]" ?>"
											value="<? echo $idAspirante[$i] ?>">
								</td>
							</tr>
						<?
							}
						?>
						</table>
						</div>
						</center>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="7" valign="center" 
						style="vertical-align:top;" class="fondonaranja" align="center">
					<input type="submit" value="Agregar Registros">
				</td>
				</form>
			</tr>
		</table>
		<br><br>
		
<?
	print "<script type=\"text/javascript\">
	new Event.observe(\"periodo\", \"change\", function(){
	var periodo = document.Formulario1.periodo.value;
	if( periodo == -1 )
		return;
	
	new AJAX.viewRequest({
		action: \"aspirantes/listaConsulta2/\"+".periodo."+\"\",
		container: \"datos\"
	})
	})
	</script>";
	/*
	"new AJAX.viewRequest({
		action: \"profesorselecc/pkardex/".$registro.
			"/\"+".materia."+\"/\"+".periodo."+\"/\"+".tipo."+\"\",
		container: \"datos2\"
	})
	})"
	*/
	
?>