		<style type="text/css">
			.linknegrita a:hover{
				font-weight: bold;
				text-decoration: none;
				color:#000000;
			}
			.linknegrita a{
				font-weight: none;
				text-decoration: none;
				color:#000000;
			}
		</style>
<script type='text/javascript'>
function registro() {
	var folio = prompt("Introduce el número de FOLIO de la solicitud de aspirante");
	window.location.href = '<?= KUMBIA_PATH ?>aspirantes/registro/'+folio;
}
function modificacion() {
	var folio = prompt("Introduce el número de FOLIO de la solicitud de aspirante");
	window.location.href = '<?= KUMBIA_PATH ?>aspirantes/modificacion/'+folio;
}
function consulta() {
	var folio = prompt("Introduce el número de FOLIO de la solicitud de aspirante");
	window.location.href = '<?= KUMBIA_PATH ?>aspirantes/consulta/'+folio;
}

</script>
		<table border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>ASPIRANTES - PANEL DE CONTROL</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<br>
						En esta sección una secretaría podrá dar de alta y consultar cada uno de
						los aspirantes, así como consultar distintos reportes y estadísticas sobre
						este rubro.
						<br/><br/>
						<div style="color: #000000; font-size: 20px;" align="center"><b>FEBRERO - JUNIO, 2010</b></div>
						<br/>
						<center>
						<table border="0" style="font-size:12px;">
						<tr>
							<th width="225" class="fondoazul">
								<b>ASPIRANTES</b>
							</th>
							<td width="20">
								&nbsp;
							</td>
							<th width="225" class="fondoazul">
								<b>CONFIGURACION</b>
							</th>
							<td width="20">
								&nbsp;
							</td>
							<th width="225" class="fondoazul">
								<b>ESTADÍSTICAS</b>
							</th>
						</tr>
						<tr>
						<td width="225" valign="top" style="vertical-align:top;" class="fondonaranja">
							<ul>
								<li class="linknegrita">
									<a href="#" onClick="registro()">REGISTRAR ASPIRANTE</a>
								</li><br/>
								<li class="linknegrita">
									<a href="#" onClick="consulta()">CONSULTAR EXPEDIENTE</a>
								</li><br/>
								<li class="linknegrita">
									<a href="#" onClick="modificacion()">MODIFICAR EXPEDIENTE</a>
								</li>
							</ul>
						</td>
						<td width="20">
							&nbsp;
						</td>
						<td width="225" valign="top" style="vertical-align:top;"  class="fondonaranja">
							<ul>
								<li class="linknegrita">
									<a href="#" style="text-decoration:line-through">TALLER DE ORIENTACIÓN</a>
								</li><br/>
								<li class="linknegrita">
									<a href="<?= KUMBIA_PATH ?>aspirantes/config_exani">LLENADO HOJA EXANI</a>
								</li><br/>
								<li class="linknegrita">
									<a href="<?= KUMBIA_PATH ?>aspirantes/config_ceneval">EXAMEN DE ADMISIÓN</a>
								</li>
							</ul>
						</td>
						<td width="20">
							&nbsp;
						</td>
						<td width="225" valign="top" style="vertical-align:top;"  class="fondonaranja">
							<ul>
								<li class="linknegrita">
									<a href="<?= KUMBIA_PATH ?>aspirantes/estadisticas">NUMERO DE ASPIRANTES</a>
								</li><br/>
								<li class="linknegrita">
									<a href="<?= KUMBIA_PATH ?>aspirantes/reporte">REPORTE DE ASPIRANTES</a>
								</li><br/>
								<li class="linknegrita">
									<a href="<?= KUMBIA_PATH ?>aspirantes/admitidos">DICTAMEN DE ADMITIDOS</a>
								</li>
							</ul>
						</td>
						</tr>
						</table>
						</center>
					</div>
				</td>
			</tr>
		</table>
		<br><br>