		<style type="text/css">
			.linknegrita a:hover{
				font-weight: bold;
				text-decoration: none;
				color:#000000;
			}
			.linknegrita a{
				font-weight: none;
				text-decoration: none;
				color:#000000;
			}
		</style>
<script type='text/javascript'>
</script>
			<table  border="1" cellpadding="1" cellspacing="1" style="font-size: 10px;">
		<table border="0" cellpadding="0" cellspacing="0" align="center">
			<tr>
				<td style="font-family: Verdana;" align="center">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>ASPIRANTES - PANEL DE CONTROL</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<br>
						<br/><br/>
						<div style="color: #000000; font-size: 20px;" align="center">
						<form name="Formulario1" id="Formulario1" action="" method="">
							<select name="periodo" id="periodo" class="lista">
								<option value="-1">
									- - Seleccionar Periodo - -
								</option>
								<option value="12010">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									- - 12010 - -
								</option>
								<option value="32010">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									- - 32010 - -
								</option>
								<option value="12011">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									- - 12011 - -
								</option>
								<option value="32011">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									- - 32011 - -
								</option>
								<option value="12012">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									- - 12012 - -
								</option>
								<option value="32012">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									- - 32012 - -
								</option>
							</select>
						</form>
						</div>
						<br />
						<div id="datos">
						<div style="color: #000000; font-size: 20px;" align="center">
							<b><?= $periodoo ?></b></div>
						<br/>
						<br />
						<center>
						<table border="0" style="font-size:12px;" align="center">
						<tr>
							<th width="50" class="fondoazul" align="center">
								<b>FICHA</b>
							</th>
							<th width="50" class="fondoazul" align="center">
								<b>FOLIO</b>
							</th>
							<th width="150" class="fondoazul" align="center">
								<b>TIPO ASPIRANTE</b>
							</th>
							<th width="150" class="fondoazul" align="center">
								<b>CARRERA</b>
							</th>
							<th width="100" class="fondoazul" align="center">
								<b>PLANTEL</b>
							</th>
							<th width="300" class="fondoazul" align="center">
								<b>NOMBRE</b>
							</th>
							<th width="100" class="fondoazul" align="center">
								<b>CONSULTAR</b>
							</th>
						</tr>
						<?php
							for( $i = 0; $i < $iiii; $i++ ){
						?>
							<tr>
								<td width="50" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $ficha[$i] ?>
								</td>
								<td width="50" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $folio[$i] ?>
								</td>
								<td width="150" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<?
									if( $tipoAspirante[$i] == 1 )
										echo "Pago de Derecho";
									else if( $tipoAspirante[$i] == 2 )
										echo "Continuaci&oacute;n de Estudios";
									else if( $tipoAspirante[$i] == 0 )
										echo "NO DISPONIBLE";
									?>
								</td>
								<td width="150" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $carrera[$i] ?>
								</td>
								<td width="100" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo $plantel[$i] ?>
								</td>
								<td width="300" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<? echo utf8_encode($nombre[$i]." ".$paterno[$i]." ".$materno[$i]);  ?>
								</td>
								<td width="100" valign="top" 
										style="vertical-align:top;" class="fondonaranja" align="center">
									<form method="POST" 
											action="<?= KUMBIA_PATH ?>aspirantes/consulta/
												<? echo $folio[$i] ?>/<? echo $tipoAspirante[$i] ?>">
										<input type="submit" value="consultar">
										<input type="hidden" value="<?= $periodoNumero ?>" name="periodoNumero" id="periodoNumero">
									</form>
								</td>
							</tr>
						<?
							}
						?>
						</table>
						</div>
						</center>
					</div>
				</td>
			</tr>
		</table>
		<br><br>
<?php
	render_partial("regresar");
?>
<?
	print "<script type=\"text/javascript\">
	new Event.observe(\"periodo\", \"change\", function(){
	var periodo = document.Formulario1.periodo.value;
	if( periodo == -1 )
		return;
	
	new AJAX.viewRequest({
		action: \"aspirantes/listaConsulta2/\"+".periodo."+\"\",
		container: \"datos\"
	})
	})
	</script>";
	/*
	"new AJAX.viewRequest({
		action: \"profesorselecc/pkardex/".$registro.
			"/\"+".materia."+\"/\"+".periodo."+\"/\"+".tipo."+\"\",
		container: \"datos2\"
	})
	})"
	*/
	
?>