<style type="text/css">
	.cielo{
		background:#EFEFEF;
		text-transform:uppercase;
		font-weight:bold;
	}
</style>
<script type='text/javascript'>
function validar( ) {

	var err = "";
	
	if (document.Formulario1.curp.value=="") {
		err += "El campo carrera no debe quedar vacio\n";
  	}
	
	//var curp = document.Formulario1.elements['curp'];
	//alert(curp.size);
	if( document.Formulario1.curp.value.length < 18 ){
		err += "La CURP debe tener 18 caracteres\n";
	}
	
	var fecha_actual = new Date();
	if( (fecha_actual.getFullYear() - document.Formulario1.anioo.value) < 18 ){
		if( !confirm("El alumno es menor de edad, se desea proseguir para la captura de su información?") ){
			return false;
		}
	}
	// Si es numero me devuelve false.
	// Si es cadena me devuelve true.
	if( isNaN(document.Formulario1.exterior.value) ){
		err += "El campo de número exterior debe contener sólo caracteres numéricos\n";
	}
	
	if (document.Formulario1.plantelorigen.value== -1) {
		err += "Favor de seleccionar de que plantel viene el alumno\n"
		"En caso de no venir de ningún plantel favor de seleccionar 'NO APLICA'\n";
  	}
	if (document.getElementById("sexo").value== -1) {
		err += "Seleccione el sexo del alumno\n";
  	}
	
	if (isNaN(document.getElementById("registro_tecnologo").value)) {
		err += "El registro solo está formado por números enteros\n";
  	}
	
	if( err != "" ){
		alert(err);
		return false;
	}
	else{
		return true;
	}
	
  	// document.Formulario1.presencial.value
	/*
	if (document.Formulario1.carrera.value=="") {
		alert("El campo carrera no debe quedar vacio");
		document.Formulario1.carrera.focus();
		return false;
  	}
	*/
	/*
	if (document.Formulario1.paterno.value=="") {
		alert("El campo apellido paterno no debe quedar vacio");
		document.Formulario1.paterno.focus();
		return false;
  	}
	
	if (document.Formulario1.materno.value=="") {
		alert("El campo apellido materno no debe quedar vacio");
		document.Formulario1.materno.focus();
		return false;
  	}
	
	if (document.Formulario1.nombre.value=="") {
		alert("El campo nombre no debe quedar vacio");
		document.Formulario1.nombre.focus();
		return false;
  	}
		
	if (document.Formulario1.sexo.value=="") {
		alert("Debes elegir un genero");
		document.Formulario1.sexo.focus();
		return false;
  	}
	
	if (document.Formulario1.curp.value=="") {
		alert("El campo curp de nacimiento no debe quedar vacio");
		document.Formulario1.curp.focus();
		return false;
  	}
	*/
	/*
	if (document.Formulario1.calle.value=="") {
		alert("El campo calle no debe quedar vacio");
		document.Formulario1.calle.focus();
		return false;
  	}
	
	if (document.Formulario1.exterior.value=="") {
		alert("El campo exterior no debe quedar vacio");
		document.Formulario1.exterior.focus();
		return false;
  	}
	
	if (document.Formulario1.cp.value=="") {
		alert("El campo codigo postal no debe quedar vacio");
		document.Formulario1.cp.focus();
		return false;
  	}
	
	if (document.Formulario1.municipio.value=="") {
		alert("El campo municipio no debe quedar vacio");
		document.Formulario1.municipio.focus();
		return false;
  	}
	
	if (document.Formulario1.estado.value=="") {
		alert("El campo estado no debe quedar vacio");
		document.Formulario1.estado.focus();
		return false;
  	}
	
	if (document.Formulario1.telefono.value=="") {
		alert("El campo telefono no debe quedar vacio");
		document.Formulario1.telefono.focus();
		return false;
  	}
	
	if (document.Formulario1.correo.value=="") {
		alert("El campo correo electrónico no debe quedar vacio");
		document.Formulario1.correo.focus();
		return false;
  	}
	
	if (document.Formulario1.nacimiento.value=="") {
		alert("El campo lugar de nacimiento no debe quedar vacio");
		document.Formulario1.nacimiento.focus();
		return false;
  	}
	
	if (document.Formulario1.curp.value=="") {
		alert("El campo curp de nacimiento no debe quedar vacio");
		document.Formulario1.curp.focus();
		return false;
  	}
	
	*/
}



</script>

<form method="POST" action="<?= KUMBIA_PATH.$controller_name ?>/registrar/<?= $folio ?>/<?= $tipoAspirante ?>"  
	onSubmit="return validar();" name="Formulario1" id="Formulario1">
<table border="1" align="center" width="550">
	<br />
	<tr>
		<th colspan="5" class="fondoazul" height="25" style="font-size:14px;">DATOS ACADÉMICOS</font></th>
	</tr>
	<tr>
		<th class="fondonaranja">
			Folio
		</th>
		<th class="fondonaranja">
			Ficha
		</th>
		<th class="fondonaranja">
			Periodo
		</th>
	</tr>
	<tr>
		<th>
			<input type="text" style="width:150px; text-align:center; color:#000;" name="folio" value="<?= $folio ?>" class="cielo" disabled>
		</th>
		<th>
			<input type="text" style="width:200px; text-align:center; color:#000;" name="ficha" value="<?= $ficha ?>" class="cielo" disabled>
		</th>
		<th>
			<input type="text" style="width:200px; text-align:center; color:#000;" name="periodo" value="<?= $periodo ?>" class="cielo" disabled>
		</th>
	</tr>
	<tr>
		<th class="fondonaranja">
			Carrera Opc1
		</th>
		<th colspan="2">
			<select name="carreraa1" id="carreraa1" style="width:500px; font-weight:none;" class="cielo" >
				<option value="0"></option>
				<optgroup label="NIVEL INGENIERÍA">
				<?
				foreach( $carrerasDisp as $carrDisp ){
				?>
				<option value="<?= $carrDisp -> id ?>">
					<?= $carrDisp -> idcarrera ?> - <?= $carrDisp -> nombre ?> - 
					<? if( $carrDisp -> plantel == "C" ){ echo "Colomos"; } else if( $carrDisp -> plantel == "T" ){ echo "Tonala"; } else{ echo ""; } ?> - 
					<? if( $carrDisp -> turno == "V" ){ echo "Vespertino"; } else if( $carrDisp -> turno == "M" ){ echo "Matutino"; } else{ echo ""; }?>
				</option>
				<?
				}
				?>
			</select>
		</th>
	</tr>
	<tr>
		<th class="fondonaranja">
			Carrera Opc2
		</th>
		<th colspan="2">
		<?
			echo "<script type=\"text/javascript\">
			function cambiar1(opcion){
				var aBorrar = document.forms[\"Formulario1\"][\"carreraa2\"].options[opcion];
				aBorrar.parentNode.removeChild(aBorrar);
			}
			</script>";
		/*
			echo "<script type=\"text/javascript\">
			new Event.observe(\"carreraa1\", \"change\", function(){
			var idcarrera = document.Formulario1.carreraa1.value;
			new AJAX.viewRequest({
				action: \"aspirantes/agregarCarreraSegunCarrera/\"+".idcarrera."+\"/2\",
				container: \"carreradiv2\"
			})
			})
			</script>";
		*/
		?>
			<div id="carreradiv2">
			<select name="carreraa2" id="carreraa2" style="width:500px; font-weight:none;" class="cielo" DISABLED>
				<option value="0"></option>
				<optgroup label="NIVEL INGENIERÍA">
				<?
				foreach( $carrerasDisp as $carrDisp ){
				?>
				<option value="<?= $carrDisp -> id ?>">
					<?= $carrDisp -> idcarrera ?> - <?= $carrDisp -> nombre ?> - 
					<? if( $carrDisp -> plantel == "C" ){ echo "Colomos"; } else if( $carrDisp -> plantel == "T" ){ echo "Tonala"; } else{ echo ""; } ?> - 
					<? if( $carrDisp -> turno == "V" ){ echo "Vespertino"; } else if( $carrDisp -> turno == "M" ){ echo "Matutino"; } else{ echo ""; }?>
				</option>
				<?
				}
				?>
			</select>
			</div>
		</th>
	</tr>
	<tr>
		<th class="fondonaranja">
			Carrera Opc3
		</th>
		<th colspan="2">
		<?
		// aBorrar.parentNode.removeChild(aBorrar);
			echo "<script type=\"text/javascript\">
			function cambiar2(opcion){
				var aBorrar = document.forms[\"Formulario1\"][\"carreraa3\"].options[opcion];
				aBorrar.parentNode.disableChild(aBorrar);
			}
			</script>";
		// action: \"aspirantes/agregarCarreraSegunCarrera2/\"+".idcarrera."+\"/\"+".idcarrera2."+\"/2\",
		/*
			print "<script type=\"text/javascript\">
			new Event.observe(\"carreraa1\", \"change\", function(){
				var idcarrera = document.Formulario1.carreraa1.value;
				new AJAX.viewRequest({
					action: \"aspirantes/agregarCarreraSegunCarrera/\"+".idcarrera."+\"/3\",
					container: \"carreradiv3\"
				})
			})
			</script>";
		*/
		?>
			<div id="carreradiv3">
			<select name="carreraa3" id="carreraa3" style="width:500px; font-weight:none;" class="cielo" DISABLED>
				<option value="0"></option>
				<optgroup label="NIVEL INGENIERÍA">
				<?
				foreach( $carrerasDisp as $carrDisp ){
				?>
				<option value="<?= $carrDisp -> id ?>">
					<?= $carrDisp -> idcarrera ?> - <?= $carrDisp -> nombre ?> - 
					<? if( $carrDisp -> plantel == "C" ){ echo "Colomos"; } else if( $carrDisp -> plantel == "T" ){ echo "Tonala"; } else{ echo ""; } ?> - 
					<? if( $carrDisp -> turno == "V" ){ echo "Vespertino"; } else if( $carrDisp -> turno == "M" ){ echo "Matutino"; } else{ echo ""; }?>
				</option>
				<?
				}
				?>
			</select>
			</div>
		</th>
	</tr>
</table><br><br>
<table border="1" align="center">
	<tr>
		<th colspan="5" class="fondoazul" height="25" style="font-size:14px;">DATOS PERSONALES</font></th>
	</tr>
	<tr>
		<td rowspan="2" width="150" class="fondoazul">
			<b>&nbsp;Nombre:</b>
		</td>
		<th class="fondonaranja">
			Apellido paterno
		</th>
		<th class="fondonaranja">
			Apellido materno
		</th>
		<th colspan="2" class="fondonaranja">
			Nombre(s)
		</th>
	</tr>
	<tr>
		<th>
			<input type="text" style="width:125px" name="paterno" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="materno" class="cielo">
		</th>
		<th colspan="2">
			<input type="text" style="width:260px" name="nombre" class="cielo">
		</th>
	</tr>
	<tr>
		<td rowspan="6" class="fondoazul">
			<b>&nbsp;Domicilio:</b>
		</td>
		<th colspan="2" class="fondonaranja">
			Calle
		</th>
		<th class="fondonaranja">
			Número Exterior
		</th>
		<th class="fondonaranja">
			Número Interior
		</th>
		
	</tr>
	<tr>
		<th colspan="2">
			<input type="text" style="width:262px;" name="calle" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="exterior" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="interior" class="cielo">
		</th>
	</tr>
	<tr>
		<th class="fondonaranja">
			Colonia
		</th>
		<th class="fondonaranja">
			Código postal
		</th>
		<th class="fondonaranja">
			Municipio
		</th>
		<th class="fondonaranja">
			Estado
		</th>
		
	</tr>
	<tr>
		<th>
			<input type="text" style="width:125px" name="colonia" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="cp" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="municipio" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="estado" class="cielo">
		</th>
	</tr>
	<tr>
		<th class="fondonaranja" colspan="2">
			Lugar de Nacimiento
		</th>
		<th class="fondonaranja" colspan="2">
			Fecha Nacimiento
		</th>
	</tr>
	<tr>
		<th colspan="2">
			<input type="text" style="width:258px" name="lugarNacimiento" class="cielo">
		</th>
		<th colspan="2">
			<select id="diaa" name="diaa" class="cielo">
			<?
				for( $i = 1; $i < 32; $i++ ){
					echo "<option value=\"$i\">$i</option>";
				}
			?>
			</select>
			<select id="mess" name="mess" class="cielo">
				
				<option value="1">ENERO</option>
				<option value="2">FEBRERO</option>
				<option value="3">MARZO</option>
				<option value="4">ABRIL</option>
				<option value="5">MAYO</option>
				<option value="6">JUNIO</option>
				<option value="7">JULIO</option>
				<option value="8">AGOSTO</option>
				<option value="9">SEPTIEMBRE</option>
				<option value="10">OCTUBRE</option>
				<option value="11">NOVIEMBRE</option>
				<option value="12">DICIEMBRE</option>
			</select>
			<select id="anioo" name="anioo" class="cielo">
			<?
				for( $i = 1940; $i < 2012; $i++ ){
					echo "<option value=\"$i\">$i</option>";
				}
			?>
			</select>
		</th>
	</tr>
	<tr>
		<td rowspan="4" class="fondoazul">
			<b>&nbsp;Contacto:</b>
		</td>
		<th class="fondonaranja">
			Teléfono
		</th>
		<th class="fondonaranja">
			Celular
		</th>
		<th colspan="2" class="fondonaranja">
			E-mail
		</th>
	</tr>
	<tr>
		<th>
			<input type="text" style="width:125px" name="telefono" class="cielo">
		</th>
		<th>
			<input type="text" style="width:125px" name="celular" class="cielo">
		</th>
		<th colspan="2">
			<input type="text" style="width:260px" name="correo" class="cielo">
		</th>
	</tr>
	<tr style="display:none;">
		<td rowspan="4" class="fondoazul">
			<b>&nbsp;Información:</b>
		</td>
		<th colspan="2" class="fondonaranja">
			Genero
		</th>
		<th colspan="2" class="fondonaranja">
			Estado civil
		</th>
	</tr>
	<tr style="display:none;">
		<th colspan="2">
			<select name="sexo" style="width:265px" class="cielo">
				<option value="H">Hombre</option>
				<option value="M">Mujer</option>
			</select>
		</th>
		<th colspan="2">
			<select name="estadocivil" style="width:265px" class="cielo">
				<option value="SOLTERO">Soltero(a)</option>
				<option value="CASADO">Casado(a)</option>
				<option value="DIVORCIADO">Divorciado(a)</option>
				<option value="VIUDO">Viudo(a)</option>
				<option value="UNION LIBRE">Unión libre</option>
			</select>
		</th>
	</tr>
	<tr style="display:none;">
		<th colspan="2" class="fondonaranja">
			Fecha de nacimiento
		</th>
		<th colspan="2" class="fondonaranja">
			Lugar de nacimiento
		</th>
	</tr>
	<tr>
		<th colspan="2" class="fondonaranja">
			Pais Nacimiento
		</th>
		<th colspan="2" class="fondonaranja">
		</th>
	</tr>
	<tr>
		<th colspan="2" style="text-align: left;">
			<input type="text" style="width:260px" name="paisnacimiento" 
				id="paisnacimiento" class="cielo">
		</th>
		<th colspan="2" class="fondonaranja">
		</th>
	</tr>
	<tr style="display:none;">
		<th colspan="2">
			<select name="d" style="width:60px" class="cielo">
				<?php for($i=1;$i<32;$i++){ ?>
					<option value="<?php if($i<10) { echo '0'; } ?><?= $i ?>"><?= $i ?></option>
				<?php } ?>
			</select>
			<select name="m" style="width:130px" class="cielo">
				<option value="01">Enero</option>
				<option value="02">Febrero</option>
				<option value="03">Marzo</option>
				<option value="04">Abril</option>
				<option value="05">Mayo</option>
				<option value="06">Junio</option>
				<option value="07">Julio</option>
				<option value="08">Agosto</option>
				<option value="09">Septiembre</option>
				<option value="10">Octubre</option>
				<option value="11">Noviembre</option>
				<option value="12">Diciembre</option>
			</select>
			<select name="a" style="width:68px" class="cielo">
				<?php for($i=1995;$i>1960;$i--){ ?>
					<option value="<?php if($i<10) { echo '0'; } ?><?= $i ?>"><?= $i ?></option>
				<?php } ?>
			</select>
		</th>
		<th colspan="2">
			<input value="" type="text" style="width:260px" name="nacimiento" class="cielo">
		</th>
	</tr>
	<tr>
		<td rowspan="10" width="150" class="fondoazul">
			<b>&nbsp;DOCUMENTACION:</b>
		</td>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="checkbox" name="fotos" value="si"> Fotografias<br>
		</th>		
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="checkbox" name="constanciae" value="si"> Constancia de Estudios<br>
		</th>
	</tr>
	<tr>		
		<th colspan="2" class="fondonaranja" style="text-align: center;">
			<!-- <input type="checkbox" name="certificadoo" value="si"> -->
			Certificado Original<br />
			<select name="certificadoo" class="lista">
				<option value="no">- - No - -</option>
				<option value="si">- - Si - -</option>
			</select>
			<br />
			Certificado Copia<br />
			<select name="certificadoc" class="lista">
				<option value="no">- - No - -</option>
				<option value="si">- - Si - -</option>
			</select>
		</th>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="checkbox" name="certificadom" value="si"> Certificado Médico<br>
		</th>
	</tr>
	<tr>		
		<th colspan="2" class="fondonaranja" style="text-align: center;">
			<!-- <input type="checkbox" name="certificadoo" value="si"> -->
			Acta de Nacimiento Original<br />
			<select name="acta" class="lista">
				<option value="no">- - No - -</option>
				<option value="si">- - Si - -</option>
			</select>
			<br />
			Acta de Nacimiento Copia<br />
			<select name="actac" class="lista">
				<option value="no">- - No - -</option>
				<option value="si">- - Si - -</option>
			</select>
		</th>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="checkbox" name="constanciab" value="si"> Constancia de Buena Conducta<br>
		</th>
	</tr>
	<tr>		
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="checkbox" name="curpcopia" value="si">CURP Copia<br>
		</th>		
		<th colspan="2" class="fondonaranja" style="text-align: left;">
		</th>
	</tr>
	<tr>		
		<th colspan="2" class="fondonaranja" style="text-align: left;">
<!--		<input type="checkbox" name="curp" value="si">  -->
			&nbsp;&nbsp;&nbsp;CURP<br />
			&nbsp;&nbsp;&nbsp;<input type="text" maxlength="18" style="width:225px" name="curp" id="curp" class="cielo"><br />
		</th>		
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="checkbox" name="ayuda" value="si"> Ayuda<br>
		</th>
	</tr>
	<tr>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			&nbsp;&nbsp;&nbsp;ESCUELA PROCEDENCIA<br />
			&nbsp;&nbsp;&nbsp;<input type="text" style="width:225px" name="procedencia" class="cielo"><br>
		</th>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			&nbsp;&nbsp;&nbsp;PROMEDIO BACHILLERATO<br />
			&nbsp;&nbsp;&nbsp;<input type="text" style="width:75px" name="promedioprepa" class="cielo"><br>
		</th>
	</tr>
	<tr>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<select name="plantel" id="plantel" class="fondonaranja">
				<option value="-1" style='text-align:center;'>- - Plantel - -</option>
				<option value="1" style='text-align:center;'>Ingenieria Colomos</option>
				<option value="2" style='text-align:center;'>Ingenieria Tonala</option>
			</select>
		</th>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<select name="sexo" id="sexo" class="fondonaranja">
				<option value="-1" style='text-align:center;'>- - Sexo - -</option>
				<option value="H" style='text-align:center;'>Masculino</option>
				<option value="M" style='text-align:center;'>Femenino</option>
			</select>
		</th>
	</tr>
	<tr>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<select name="plantelorigen" id="plantelorigen" class="fondonaranja">
				<option value="-1" style='text-align:center;'>- - Plantel De Origen - -</option>
				<option value="1" style='text-align:center;'>Ingenieria Colomos</option>
				<option value="2" style='text-align:center;'>Ingenieria Tonala</option>
				<option value="3" style='text-align:center;'>NO APLICA</option>
			</select>
		</th>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			Registro Tecn&oacute;logo: <input type="text" id="registro_tecnologo" name="registro_tecnologo" maxlength="12"/>
		</th>
	</tr>
	<tr>
		<th colspan="2" class="fondonaranja">
			Folio Ceneval
		</th>
		<th colspan="2" class="fondonaranja">
			Estado Prepa
		</th>
	</tr>
	<tr>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="text" style="width:260px; text-align:center; color:#000;" 
				name="folioceneval" id="folioceneval" class="cielo">
		</th>
		<th colspan="2" class="fondonaranja" style="text-align: left;">
			<input type="text" style="width:260px; text-align:center; color:#000;" 
				name="estadoprepa" id="estadoprepa" class="cielo">
		</th>
	</tr>
	<tr>
		<td colspan ="5" height ="50" align="center" valign="center">
			<input type="submit" value="Registrar Aspirante" style="text-transform:uppercase; background:#EEE;">
		</td>
	</tr>
</table>
<br>
<br><br>
<?= end_form_tag() ?>

<?php
	render_partial("regresar");
?>