<center>
<table>
	<tr>
		<td width="750"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>KARDEX DEL ALUMNO</b></div>
			<hr><br>
			<div style="font-size: 11px;">
				El kardex es un reporte donde se muestran todas las materias acreditadas por el alumno, así como la calificación obtenida y la modalidad en que fue acreditada.
			</div>
			<br>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
				<tr>
					<td width="150" height="25" bgcolor="#FFCA5B">&nbsp;<b>Nombre del alumno: </b></td>
					<td width="400" colspan="3" bgcolor="#EEEEEE">&nbsp;<?= $alumno ?> (<?= $registro ?>)</td>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Promedio: </b></td>
					<td width="100" bgcolor="#EEEEEE">&nbsp;<?= $promedio ?></td>
				</tr>
				<tr>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Especialidad: </b></td>
					<td width="400" colspan="3" bgcolor="#EEEEEE">&nbsp;<?= $especialidad ?></td>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Número de créditos: </b></td>
					<td width="100" bgcolor="#EEEEEE">&nbsp;<?= $ncreditos ?></td>
				</tr>
			</table>
			<br>
			<?php if($kardexs>0){ ?>
			<?php foreach($periodos as $periodo){ $i++; $bg = "#FFFFFF"; if(!$kardex[$i]) { break; }?>
			<table border="1" cellpadding="1" cellspacing="1" style="font-size: 10px;" >
				
				<tr class="fondoazul">
					<th align="center" height="25" colspan="6">PERIODO (<?php if($periodo[0]==1){ echo "FEB - JUN ".substr($periodo,1,4); } else { echo "AGO - DIC ".substr($periodo,1,4); } ?>)</th>
				</tr>
				<tr class="fondonaranja" align="center">
					<th width="50" height="25">Nivel</th>
					<th width="50" height="25">Clave</th>
					<th width="300">Nombre de la Materia</th>
					<th width="200">Calificación</th>
					<th width="150">Tipo</th>
					<th width="50">Créditos</th>
				</tr>
				<?php $j=0; foreach($kardex[$i] as $k){ ?>
				<tr style="font-size: 10px;" bgcolor="<?= $bg ?>"> 
					<td width="50" height="25" align="center"><?= $i ?></td>
					<td width="50" align="center" bgcolor="<?= $bg ?>" height="25"><?= $kardex[$i][$j] -> clavemat ?></td>
					<td width="300" align="left" bgcolor="<?= $bg ?>">&nbsp;<?= $materias[$i][$j] ?>&nbsp;</td>
					<td width="200" align="left" bgcolor="<?= $bg ?>">&nbsp;<?= $kardex[$i][$j] -> promedio ?> - <?= $calificaciones[$i][$j] ?>&nbsp;</td>
					<td width="150" align="center" bgcolor="<?= $bg ?>">
						<?= $kardex[$i][$j] -> tipo_de_ex ?>
					</td>
					<td width="50" align="center" bgcolor="<?= $bg ?>"><?= $creditos[$i][$j] ?></td>
				</tr>
				<?php $j++; } ?>
			</table><br>
			<?php } ?>
			<?php } else { ?>
				<br><b><center><h3>NO TIENES CURSOS REGISTRADOS PARA ESTE PERIODO</h3></center></b><br>
			<?php } ?>
		</td>
	</tr>
</table>
</center>