<div class="menu">
	<a href="<?= KUMBIA_PATH ?>tgocoordinador/index" onmouseover="toolTip('Volver al modulo de Coordinador',this)">Volver al Modulo Coordinador</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>irregular/asignarIrregular/830001" onmouseover="toolTip('Asignador de materias a alumnos.<br><br>Recuerda poner en la direccion<br>como ultimo dato el numero de registro.<br> Por default tiene el registro 830001',this)">Asignar Materias</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>grupo/vergrupo2/1a1/OK" onmouseover="toolTip('Ver el estado de un grupo en particular.<br>Por default en la dirección se coloca<br>el grupo 1A1, y como ultimo parametro OK.',this)">Estado de Grupo</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>grupo/ver/200" onmouseover="toolTip('Ver la cantidad de alumnos registrados<br>por materias de cada una de las divisiones<br>Como ultimo parametro va el numero de división,<br> default 200',this)">Materias de la división</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<!--<a href="<?= KUMBIA_PATH ?>grupos/asignarMaterias/0" onmouseover="toolTip('Asignar Materias a grupos por Semestre, Especialidad, Turno',this)">Asignar Mat. Por especialidad</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;-->
	<a href="<?= KUMBIA_PATH ?>tgoprofesor/salir" onmouseover="toolTip('Salir del Sistema de Control Escolar',this)">Salir</a>
<div>