<table width="899" border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 10px;" >
  <tr>
    <th width="92" height="25" bgcolor="#FFCA5B">&nbsp;Nombre:</th>
    <th colspan="3" bgcolor="#EEEEEE">&nbsp;
      <?php
			if( isset($buscaralumno) ) echo utf8_encode($alumno -> vcNomAlu." ".( $alumno -> miReg ));
			else echo $alumno -> vcNomAlu." ".( $alumno -> miReg );
		?>
    </th>
    <th width="87" height="25" bgcolor="#FFCA5B"><b>&nbsp;N&uacute;mero de <br />
      &nbsp;cr&eacute;ditos:</th>
    <th colspan="2" bgcolor="#EEEEEE"><?= $ncreditos ?></th>
    <th height="25" colspan="2" bgcolor="#FFCA5B">&nbsp;&nbsp;Turno:</th>
    <th width="80" bgcolor="#EEEEEE">&nbsp;
      <?= $turno ?></th>
  </tr>
  <tr>
    <th width="92" height="25" bgcolor="#FFCA5B">&nbsp;Carrera:</th>
    <th width="210" bgcolor="#EEEEEE">&nbsp;
      <?php
		
		if( $alumno -> areadeformacion_id != 0 ){
			if( isset($buscaralumno) ) echo utf8_encode($career -> nombre." ".$career -> nombreareaformacion);
			echo $career -> nombre;
		}
		else{
			if( isset($buscaralumno) ) echo utf8_encode($career -> nombre);
			else echo $career -> nombre;
		}
		?>
    </th>
    <th width="74" height="25" bgcolor="#FFCA5B">&nbsp;Plantel:</th>
    <th width="62" bgcolor="#EEEEEE">&nbsp;
      <?= utf8_encode($plantel) ?></th>
    <th width="87" height="25" bgcolor="#FFCA5B">&nbsp;Promedio:</th>
    <th width="55" bgcolor="#EEEEEE"><?php if( $promedio == 0 ) echo "0"; else echo $promedio; ?></th>
    <th width="64" bgcolor="#FFCA5B">Estado:</th>
    <th width="63" bgcolor="#EEEEEE"><?= $alumno -> stSit ?>
      &nbsp;</th>
    <th width="51" height="25" bgcolor="#FFCA5B"><b>Tipo:</th>
    <th width="80" bgcolor="#EEEEEE">&nbsp;
      <?php
			switch($alumno -> enTipo){
				case "R": echo "REGULAR"; break;
				case "I": echo "IRREGULAR"; break;
				case "P": echo "PROCESO"; break;
				case "C": echo "CONDICIONADO"; break;
			}
		?>
    </th>
  </tr>
	<tr>
		<th width="91" height="25" align="left" bgcolor="#FFCA5B">Area de formaci&oacute;n:</th>
		<th width="211" align="center" bgcolor="#EEEEEE"><? if ($alumno->areadeformacion_id!=0){echo $career -> nombreareaformacion;}else{echo "sin asignar";} ?></th>
		<th width="117" height="25" align="left" bgcolor="#FFCA5B">&nbsp;Correo Instituticional:</th>
		<th width="172" align="center" bgcolor="#EEEEEE">&nbsp;<?= $alumno->correoOficial ?></th>
		<th width="65" height="25" align="left" bgcolor="#FFCA5B">&nbsp;Pago:</th>
		<th width="209" align="center" bgcolor="#EEEEEE">&nbsp;<?php if( $alumno->pago == 1 || $alumno->condonado==1 ) echo "Pago ".$periodo_letra; else echo "Sin Pago"; ?></th>
		<th width="65" height="25" align="left" bgcolor="#FFCA5B">&nbsp;Tipo de Plan:</th>
		<th width="209" align="center" bgcolor="#EEEEEE" colspan="3">&nbsp;<?php if( $alumno->chGpo == '**' ) echo "Plan R&iacute;gido"; else echo "Plan Cr&eacute;ditos"; ?></th>
  </tr>
</table>
<br />
<br />
