<script type='text/javascript'>
function validar( formulario ) {
  	if (formulario.nombre.value=="") {
		alert("El campo nombre no debe quedar vacio");
		formulario.nombre.focus();
		return false;
  	}
	
	if (formulario.paterno.value=="") {
		alert("El campo apellido paterno no debe quedar vacio");
		formulario.paterno.focus();
		return false;
  	}
	
	if (formulario.materno.value=="") {
		alert("El campo apellido materno no debe quedar vacio");
		formulario.materno.focus();
		return false;
  	}
	
	if (formulario.sexo.value=="") {
		alert("Debes elegir un genero");
		formulario.sexo.focus();
		return false;
  	}
	
	if (formulario.domicilio.value=="") {
		alert("El campo domicilio no debe quedar vacio");
		formulario.domicilio.focus();
		return false;
  	}
	
	if (formulario.cp.value=="") {
		alert("El campo codigo postal no debe quedar vacio");
		formulario.cp.focus();
		return false;
  	}
	
	if (formulario.ciudad.value=="") {
		alert("El campo ciudad no debe quedar vacio");
		formulario.ciudad.focus();
		return false;
  	}
	
	if (formulario.telefono.value=="") {
		alert("El campo telefono no debe quedar vacio");
		formulario.telefono.focus();
		return false;
  	}
	
	if (formulario.correo.value=="") {
		alert("El campo correo electrónico no debe quedar vacio");
		formulario.correo.focus();
		return false;
  	}
	alert("Muchas gracias por actualizar tus datos");
}


</script>

<style type="text/css">	
	.infoalumno{
		text-align:justify;
		font-size:13px;
	}
	.infoalumno td{
		padding:0 10px 0 10px;
	}
	.infoalumno th{
		padding:0 10px 0 10px;
		font-size:14px;
	}
</style>
	
<center>
<table>
	<tr>
		<td width="900" bgcolor="#FFFFFF"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>ACTUALIZACION DE DATOS</b></div>
			<hr><br>
			<div style="font-size: 11px;">
			El proceso de actualización de datos es recopilar los datos personales de cada uno de los alumnos, 
			los cuales deberán estar escritos correctamente para poder agilizar los diferentes procesos que se 
			realizan en el departamento de apoyo académico.
			<br><br>
			Este proceso es <b>obligatorio</b> y será necesario para poder consultar tus calificaciones del primer 
			parcial. La información proporcionada es confidencial y solo utilizada para procesos académicos.
			</div>
			<br />
			<?= render_partial("alumno/info_alumno"); ?>
			<br />
			</div>
		</div></td>
	</tr>
	<tr>
		<td align="center">
			<div align="center">
	<style type="text/css">
		.forma{
			width:275px;
			text-transform: uppercase;
		}
	</style>
<form method="POST" action="<?= KUMBIA_PATH ?>ingalumno/actualizar" onSubmit="return validar(this);">
<table border="1" cellpadding="1" cellspacing="1" style="font-size:11px;">
	<tr>
		<th colspan="2" height="20" bgcolor="#1569C7" style="color:#FFFFFF">
			MODULO DE ACTUALIZACIÓN
		</th>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Nombre: </b></td>
		<td width="280" align="left"><input type="text" name="nombre" class="forma" value="<?= $nombre ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Apellido paterno: </b></td>
		<td width="280" align="left"><input type="text" name="paterno" class="forma" value="<?= $paterno ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Apellido materno: </b></td>
		<td width="280" align="left"><input type="text" name="materno" class="forma" value="<?= $materno ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Fecha de nacimiento: </b></td>
		<td width="280" align="left">
			<select name="d">
				<?php
				for($i=1;$i<32;$i++){
					$seleccionado = "";
					if( $dia == $i )
						$seleccionado = "selected";
					
					echo "<option value=\"$i \" $seleccionado>$i</option>";
					?>
				<?php } ?>
			</select>
			<select name="m">
				<option value="01"<? if( $mes == 01 ) echo "selected"; ?>>Enero&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
				<option value="02"<? if( $mes == 02 ) echo "selected"; ?>>Febrero</option>
				<option value="03"<? if( $mes == 03 ) echo "selected"; ?>>Marzo</option>
				<option value="04"<? if( $mes == 04 ) echo "selected"; ?>>Abril</option>
				<option value="05"<? if( $mes == 05 ) echo "selected"; ?>>Mayo</option>
				<option value="06"<? if( $mes == 06 ) echo "selected"; ?>>Junio</option>
				<option value="07"<? if( $mes == 07 ) echo "selected"; ?>>Julio</option>
				<option value="08"<? if( $mes == 08 ) echo "selected"; ?>>Agosto</option>
				<option value="09"<? if( $mes == 09 ) echo "selected"; ?>>Septiembre</option>
				<option value="10"<? if( $mes == 10 ) echo "selected"; ?>>Octubre</option>
				<option value="11"<? if( $mes == 11 ) echo "selected"; ?>>Noviembre</option>
				<option value="12"<? if( $mes == 12 ) echo "selected"; ?>>Diciembre</option>
			</select>
			<select name="y">
				<?php
				for($i=1994;$i>=1960;$i--){
					$seleccionado = "";
					if( $anio == $i )
						$seleccionado = "selected";
					?>
						<option value="<?= $i ?>" <?= $seleccionado ?>><?= $i ?></option>
				<?php } ?>
			</select>
		</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Genero: </b></td>
		<td width="280" align="left"><input type="radio" name="sexo" value="H" <? if( $sexo == "H" ) echo "checked"; ?>> Hombre
		<input type="radio" name="sexo" value="M" <? if( $sexo == "M" ) echo "checked"; ?>> Mujer</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;Estado civil: </b></td>
		<td width="280" align="left">
			<select name="civil">
				<option value="SOLTERO" <? if( $estadocivil == "SOLTERO" ) echo "selected"; ?>>Soltero(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
				<option value="CASADO" <? if( $estadocivil == "CASADO" ) echo "selected"; ?>>Casado(a)</option>
				<option value="DIVORCIADO" <? if( $estadocivil == "DIVORCIADO" ) echo "selected"; ?>>Divorciado(a)</option>
				<option value="VIUDO" <? if( $estadocivil == "VIUDO" ) echo "selected"; ?>>Viudo(a)</option>
				<option value="UNION LIBRE">Unión Libre</option>
			</select>
		</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Tipo de sangre: </b></td>
		<td width="280" align="left">
			<select name="sangre">
				<option value="O+" <? if( $sangre == "O+" ) echo "selected"; ?>>O Positivo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
				<option value="A+" <? if( $sangre == "A" ) echo "selected"; ?>>A Positivo</option>
				<option value="B+"<? if( $sangre == "B+" ) echo "selected"; ?>>B Positivo</option>
				<option value="AB+"><? if( $sangre == "AB+" ) echo "selected"; ?>AB Positivo</option>
				<option value="O-" <? if( $sangre == "O-" ) echo "selected"; ?>>O Negativo</option>
				<option value="A-" <? if( $sangre == "A-" ) echo "selected"; ?>>A Negativo</option>
				<option value="B-" <? if( $sangre == "B-" ) echo "selected"; ?>>B Negativo</option>
				<option value="AB-" <? if( $sangre == "AB-" ) echo "selected"; ?>>AB Negativo</option>
			</select>
		</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Domicilio: </b></td>
		<td width="280" align="left"><input type="text" name="domicilio" class="forma" value="<?= $domicilio ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;Colonia: </b></td>
		<td width="280" align="left"><input type="text" name="colonia" class="forma" value="<?= $colonia ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Código postal: </b></td>
		<td width="280" align="left"><input type="text" name="cp" class="forma" value="<?= $cp ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Ciudad: </b></td>
		<td width="280" align="left"><input type="text" name="ciudad" class="forma" value="<?= $ciudad ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Teléfono: </b></td>
		<td width="280" align="left"><input type="text" name="telefono" class="forma" value="<?= $telefono ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;* Correo Electrónico: </b></td>
		<td width="280" align="left"><input type="text" name="correo" class="forma" value="<?= $correo ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;CURP: </b></td>
		<td width="280" align="left"><input type="text" name="curp" class="forma" value="<?= $curp ?>"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;&iquest;Cuentas con alg&uacute;n tipo de seguridad social? </b></td>
		<td width="280" align="left">
		<input type="radio" name="seguridad_social" id="seguridad_social" value="SI" <? if( $seguridad_social == "SI" ) echo "checked"; ?>> Si
		<input type="radio" name="seguridad_social" id="seguridad_social_" value="NO" <? if( $seguridad_social == "NO" ) echo "checked"; ?>> No</td>
	</tr>
</table>
<br />
<div id="seguridad_container" name="seguridad_container">
</div>
<br />
<input type="submit" value="ACEPTAR" style="font-size:20px; text-transform: uppercase;">
<input type="hidden" name="registro" value="<?= $registro ?>">
</form>
		</td>
	</tr>
</table>

<?
	print "<script type=\"text/javascript\">
	new Event.observe(\"seguridad_social\", \"click\", function(){
	var seguridad_social = document.getElementById(\"seguridad_social\").value;
	new AJAX.viewRequest({
		action: \"alumno/seguridad_mostrar_container/\"+".seguridad_social."+\"\",
		container: \"seguridad_container\"
	})
	})
	</script>";
	print "<script type=\"text/javascript\">
	new Event.observe(\"seguridad_social_\", \"click\", function(){
	var seguridad_social = document.getElementById(\"seguridad_social_\").value;
	new AJAX.viewRequest({
		action: \"alumno/seguridad_mostrar_container/\"+".seguridad_social."+\"\",
		container: \"seguridad_container\"
	})
	})
	</script>";
?>