<center><br><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>MÓDULO DE COORDINADOR: </b></div>
				<br>
				Este será el módulo exclusivo para los coordinadores, aún no esta disponible en cuanto lo este les informaremos para que realicen los procesos a los que estaban acostumbrados.
				<br><br>
				<?= $coordinacion; ?>
			</div>
		</div></td>
	</tr>
</table>
</center>