<center>
<table>
	<tr>
		<td width="900">
			<div align="justify">
			
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>CETI - Evaluacion de Profesores</title>
<style type="text/css">
<!--
.Blanca10 {	color: #FFFFFF;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
}
.Blanca12 {font-family: Arial, Helvetica, sans-serif; font-weight: bold; font-size: 12px; color: #FFFFFF; }
.Italica10 {	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
	font-style: italic;
}
.Negritas12 {	font-family: Arial, Helvetica, sans-serif;
	font-weight: bold;
	font-size: 12px;
}
-->
</style>
<link href="../estilos.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="750" border="0" align="center" cellpadding="2">
  <tr>
    <td><table width="750" border="0" cellpadding="2">

      <tr>
        <td width="750"><p align="center" class="Negritas12">EVALUACION DE PROFESORES </p></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td><form id="frmInicio" name="frmInicio" method="post" action="http://evaluaciondocente.ceti.mx/index.php" target="_blank">
      <table width="400" border="0" align="center" cellpadding="2"> 
        <tr>
          <td colspan="2" bgcolor="#004487"><div align="justify"><span class="Blanca10">.Tu información será usada SOLAMENTE para encontrar los profesores que tienes que evaluar, no sera usado para dar seguimiento de las respuestas que des. Tecnicamente no hay ninguna relacion entre tu registro y la evaluación de los profesores. </span></div></td>

        </tr>
        <tr>
          <td><span class="preguntaNegritas">Registro:          </span></td>
          <td><span class="preguntaNegritas">
            <input name="txtRegistro" type="text" id="txtRegistro"  value="<?= $alumno -> registro ?>"/>
          </span></td>
        </tr>
        <tr>

          <td><div align="center" class="preguntaNegritas">
            <div align="left">Contrase&ntilde;a:            </div>
          </div></td>
          <td><input name="txtPassword" type="text" id="txtPassword" size="50" value="<?= $alumno -> password ?>"/></td>
        </tr>
        <tr>
          <td colspan="2"><div align="center">
              <input type="submit" name="Submit" value="Entrar y Evaluar" style="color: #000000;background: #FFCA5B;font-size: 20px;font-weight: bold;height: 40px;text-transform: uppercase;" />

          </div></td>
        </tr>
        <tr>
          <td colspan="2"><div align="center" class="Negritas12"><a href="http://evaluaciondocente.ceti.mx/manual.pdf">Manual para la evaluaci&oacute;n docente </a></div></td>
        </tr>
        <tr>
          <td colspan="2">&nbsp;</td>
        </tr>

        <tr>
          <td colspan="2" bgcolor="#FFFFFF" class="Negritas12">&nbsp;</td>
        </tr>
        <tr>
          <td colspan="2" bgcolor="#FFFF99" class="Negritas12"><div align="center">!SE AMPLIA EL PERIODO DE CAPTURA, HASTA NUEVO AVISO!
EN CASO DE TENER PROBLEMAS EN EL PROCESO DE EVALUACION, COMUNICARSE A
desarrollo.curricular@ceti.mx</div></td>

        </tr>
      </table>
     </form>
    </td>
  </tr>
</table>
</body>
</html>

			
			</div>
		</td>
	</tr>
</table>
</center><br>