<center>
<table>
	<tr>
		<td width="900"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>EVALUACION DE PROFESORES (<?= $periodo ?>)</b></div>
			<hr><br>
			<div style="font-size: 11px;">
			<b>OBJETIVO:</b> El presente instrumento tiene como objetivo evaluar la actividad docente con respecto a la atención de los alumnos en las asignaturas que imparte, así como tener una retroalimentación de su desempeño con el fin de mejorar la calidad académica del CETI.
			<br><br>
			<i><b>Agradecemos tu sinceridad y la mayor objetividad al evaluar a cada uno de tus profesores.</b></i>
			</div>
			<br>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#999999" style="font-size: 11px;" >
				<tr>
					<td width="175" height="25" bgcolor="#FFCA5B"><b>&nbsp;Número de registro: </b></td>
					<td width="75" bgcolor="#EEEEEE">&nbsp;<?= $registro ?></td>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Especialidad: </b></td>
					<td width="350" bgcolor="#EEEEEE">&nbsp;<?= $especialidad ?></td>
				</tr>
				<tr>
					<td width="175" height="25" bgcolor="#FFCA5B">&nbsp;<b>Nombre del alumno: </b></td>
					<td width="500" colspan="3" bgcolor="#EEEEEE">&nbsp;<?= $alumno ?></td>
				</tr>
			</table>
			<br>
			<?php if($cursos>0){ ?>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#999999" style="font-size: 10px;" >
				<tr bgcolor="#FFCA5B">
					<th width="30" height="25">&nbsp;</th>
					<th width="50" align="center">Curso</th>
					<th width="225" align="center">Materia</th>
					<th width="225" align="center">Profesor</th>
					<th width="200" align="center">Situación</th>
				</tr>
				
				<?php foreach($mihorario as $horario){ $i++; if($i%2==0){ $bg = "#EEEEEE"; }else{ $bg = "#FFFFFF"; } ?>
				<?php
						if($horario -> id <100 && $horario -> id >= 10){
							$horario -> id = "0".$horario -> id;
						}
				
						if($horario -> id < 10){
							$horario -> id = "00".$horario -> id;
						}
					?>
				<form method="POST" action="<?= KUMBIA_PATH ?>alumno/evaluando/<?= $horario -> division ?><?= $horario -> id ?>">
				<tr>
					<td width="30" height="50" align="center" bgcolor="<?= $bg ?>"><?= $i ?></td>
					<td width="50" align="center" bgcolor="<?= $bg ?>">
					<?= $horario -> division ?><?= $horario -> id ?>
					</td>
					<td width="225" align="center" bgcolor="<?= $bg ?>"><?= $horario -> materia ?><br><?= $materia[$horario -> materia] ?></td>
					<td width="225" align="center" bgcolor="<?= $bg ?>"><?= $profesor[$i-1] -> nombre ?></td>
					<td width="200" align="center" bgcolor="<?= $bg ?>">
						<?php
							
						?>
						<?php 
							if($evaluacion[$horario -> division.$horario -> id]==1){
							?>
								<input type="submit" value="Profesor Evaluado" DISABLED>
							<?php
							} else{
							?>
								<input type="submit" value="Evaluar profesor">
							<?php
							}
						?>
						
					</td>
				</tr>
				</form>
				<?php } ?>
			</table><br><br>
			<div style="font-size: 14px;">
			Agradeceremos que cualquier observación o comentario acerca del presente instrumento  y/o proceso de evaluación sea dirigido a:  <b>desarrollo.curricular@ceti.mx.</b>
			</div><br>
			<div style="font-size: 16px; text-align:center;">
			GRACIAS POR TU COLABORACIÓN,<br>
			RUMBO A LA CERTIFICACIÓN DEL PROCESO DE ENSEÑANZA - APRENDIZAJE<br>
			<b><i>&iexcl;VAMOS POR UNA BUENA CALIDAD Y LA MEJORA CONTINUA!</i></b>
			</div><br>
			<?php } else { ?>
				<br><b><center><h3>NO TIENES CURSOS REGISTRADOS PARA ESTE PERIODO</h3></center></b><br>
			<?php } ?>
		</td>
	</tr>
</table>
</center>