<center><br><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			<<br><br>
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>IMPRESIÓN Y PAGO DE LA FICHA</b></div>
				<br>
					Por el momento no esta disponible la ficha de pago, consulta esta sección más adelante.
					Si exisitierá un problema o inquietud deberás pasar a el Departamento de Apoyo Académico para más información.
				<br><br>
			</div>
		</div></td>
	</tr>
</table>
</center>