		<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left"><b><?= img_tag("adorno.gif","border: 0") ?> PRECURSOS DISPONIBLES</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
						<br>
						A continuación se muestra una lista con los cursos registrados en este periodo para la materia consultada, un grupo tiene un profesor asignado, un horario y los alumnos en su momento se inscribirán en el.
						<br><br>
					</div>
					POR EL MOMENTO LA PAGINA NO ESTA DISPONIBLE
				</td>
			</tr>
		</table>
	
		<br><br>
	