<style type="text/css">	
	.infoalumno{
		text-align:justify;
		font-size:13px;
	}
	.infoalumno td{
		padding:0 10px 0 10px;
	}
	.infoalumno th{
		padding:0 10px 0 10px;
		font-size:14px;
	}
</style>

<center>
<?php if(Session::get('statusAlumno') == "SinPago" ){ ?>
  <p style="font-size:20px; font-family:arial;">
    <b>Aviso estudiantes Ingenier&iacute;a</b><br/><br/>
  </p>
  <p style="font-size:17px; text-align: justify; width:700px; font-family:arial;line-height: 24px;">
    
    Les informamos que de acuerdo al reglamento vigente de estudiantes de Educaci&oacute;n Superior, tu status de alumno es baja administrativa, debido a falta de pago de inscripci&oacute;n o reinscripci&oacute;n del semestre Feb-Jun 2013.
	<br/><br/>
    Favor de presentarse en la ventanilla de Depto. de Servicios de Apoyo Acad&eacute;mico  en horario de lunes a viernes de 8:00 a 20:00 hrs.
	<br/><br/>
	Cualquier duda o aclaraci&oacute;n favor de enviar un correo <a href="mailto:apoyo.academico.col@ceti.mx">apoyo.academico.col@ceti.mx</a> o al tel&eacute;fono 36413250 ext. 229 y 501.
	<br/><br/>
   </p>
   <p style="font-size:17px; font-family:arial;">
	<b>Atte.</b>
	<br/>
    <b>Depto. de Servicios de Apoyo Acad&eacute;mico</b>
  </p>
  
   <p style="font-size:17px; font-family:arial; text-align:left;">
    <br/><br/><br/><br/>
	 <u><font style="color:#9B0C0C; font-weight:bold; margin-left:20px;">NOTA :</font> Si desea generar la ficha de pago ingresa a la opci&oacute;n de caja y selecciona solicitar pagos.</u>
	<br/>
  </p>
<?php }else{ ?>
<table>
	<tr>
		<td width="971" bgcolor="#FFFFFF"><div align="justify">
			<br>
           	<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>INFORMACIÓN DEL ALUMNO</b></div>
			<hr><br>
            <!--
             <?
			if ($octavos=="si"){
			?>
           
			<div style="font-size: 14px; background-color:#CC3300; padding-left:15px; padding-right:15px; font-weight:bold;"><br />
			Si eres posible egresado favor de pasar a Ventanillas de Octavo con Cinthya de 3:00 a 7:30 para empezar tus tramites de graduación y no tengas ningun problema al egresar. <br /><br />
			</div>
            <? 
			}
			?>
            <br />
			<div style="font-size: 11px;">
			La información del alumno deberá estar actualizada en todo momento,
			para modificar la información aquí presentada da click en alguno de
			los botones presentados en la parte inferior.
			</div>
			<br />-->
			<?php
			/*
				$foto = "fotos/".$registro.".JPG";
				$foto1 = "fotos/".$registro.".jpg";					
				if(file_exists("/sitios/htdocs/ingenieria/public/img/".$foto)){					
					echo img_tag($foto, "width: 100");
					$entro=1;
				}
				if(file_exists("/sitios/htdocs/ingenieria/public/img/".$foto1)){					
					echo img_tag($foto1, "width: 100");
					$entro=1;
				}
				if ($entro == 0){
					echo "Sin Foto";
				}
			*/
			?>
			<?= render_partial("alumno/info_alumno"); ?>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#999999" style="font-size: 11px;" >
				<tr>
					<td width="200" height="25" bgcolor="#FFCA5B">&nbsp;<b>Tutor asignado: </b></td>
					<td width="550" colspan="3" bgcolor="#EEEEEE">&nbsp;<?= $tutor ?></td>
				</tr>
			</table>
			<br><br>

			</div>
		</div></td>
	</tr>
	<tr>
		<td align="right" valign="middle">
			<div class="infoalumno">
				<div style="padding: 10px 20px 10px 20px; font-size:14px; border-color:#FF6633; border:2px;">
				   <?php
				     $cajaTramites = new CajaTramites();
				     $cajaConceptos = new CajaConceptos();
					 //Obtiene la informacion del conceto solicitado
					 $cajaConceptos -> find_first("id = 4");
					 
					 //Cambiamos el formato de la fecha de pago
					list($anio,$mes,$dia)=split("-", $cajaConceptos -> fecha_pago);
					$fechaDesde = $dia."-".$mes."-".$anio;
					//Esta funcion sirve para obtener la fecha limite de pago, el primer para metro es la fecha inicio de pago y el segundo la cantidad de dias que se suman a esa fecha
					$fechaHasta = $cajaTramites -> create_fecha_limite_pago($fechaDesde,$cajaConceptos -> diasActivos);	
						
					//if($fechaDesde <= date('d-m-Y') && $fechaHasta >= date('d-m-Y')){
				   ?>
						<!--<form method="POST" action="<?= KUMBIA_PATH ?>alumno/fichaPago" >
							<input type="submit" style="font-weight:bold; font-famili:arial;" value="GENERAR FICHA DE PAGO" name="Ficha" target="_blank">	   
						</form>-->
					<?php
					// }
					?>
					<!--
					<h1 style="color: #AA0000">Encuestas</h1>
                     <a style="font-size: 14px" href="<?= KUMBIA_PATH ?>files/ComoDescargarFichaIngenieria.pdf">&iexcl;Ayuda!, Como Descargar Ficha Ingenier&iacute;a</a>
					-->
					<table width="663" height="160" border="1" align="center" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 14px;"">
				      <tr  height="4px" bgcolor="#FFCA5B">
				        <td width="786" align="center" valign="middle"><strong>&iexcl;AVISO IMPORTANTE!</strong></td>
			          </tr>
				      <tr height="40px">
				        <td valign="middle">&nbsp;&nbsp;
				          <p>&bull;Se les informa a todo  el alumnado del Plantel Colomos Tecn&oacute;logo e<br />
				            Ingenier&iacute;a que con la finalidad de brindar un mejor servicio, el periodo de  pago de reinscripci&oacute;n al semestre Feb-Jun 2013, se extender&aacute;:&nbsp;&nbsp; </p>
				          <table border="1" align="center" cellpadding="0" cellspacing="0" style="font-size: 12px;">
				            <tr>
				              <td width="288" valign="top"><p align="center"><strong>CONCEPTOS</strong></p></td>
				              <td width="288" valign="top"><p align="center"><strong>FECHAS</strong></p></td>
			                </tr>
				            <tr>
				              <td width="288" valign="top"><p>Periodo de pago    ordinario<strong></strong></p></td>
				              <td width="288" valign="top"><p><strong>15 de Enero al 9 de Febrero de 2013</strong></p></td>
			                </tr>
				            <tr>
				              <td width="288" valign="top"><p>Periodo de pago 1er    recargo<strong></strong></p></td>
				              <td width="288" valign="top"><p><strong>11 al 23 de Febrero de 2013</strong></p></td>
			                </tr>
				            <tr>
				              <td width="288" valign="top"><p>Periodo de pago 2do    recargo<strong></strong></p></td>
				              <td width="288" valign="top"><p><strong>25 de Febrero al 6 de Marzo de 2013</strong></p></td>
			                </tr>
			              </table>
				          <p> *<em>Consulta los pasos para imprimir el <strong>formato de pago</strong>.</em><strong> </strong><strong> </strong><a href="<?= KUMBIA_PATH ?>files/ComoDescargarFichaIngenieria.pdf" target="blank">Como Descargar Ficha de Pago para Inscripcion</a></p>
				          <p><br />
				            <strong>Nota importante:</strong> <br />
				            Al alumno/a que no realice el pago de la reinscripci&oacute;n en las  fechas se&ntilde;aladas, se le aplicar&aacute; una baja administrativa de acuerdo al  reglamento vigente. <br />
				            <br />
				            Cualquier duda o  aclaraci&oacute;n favor de enviar un correo <a href="mailto:apoyo.academico.col@ceti.mx">apoyo.academico.col@ceti.mx</a>&nbsp;o al tel&eacute;fono 36413250 ext. 229 y 501 en
				            horario de lunes a viernes de 8:00 a 20:00 hrs.<br />
				            <img src="index_clip_image002.gif" alt="" width="2" height="2" border="0" /></p>
				          <p>&nbsp;</p></td>
			          </tr>
			      </table>
		          <p><br/>
		            <?
					/*if( $status == 2 ){
					?>
						<h1 style="color: #AA0000">Reinscripción</h1>
						<span style="color: #FF8D0F"></span><b>Favor de Imprimir su ficha
						para poder pagar su reinscripción en Banorte.
						<br /><span style="color: #AA0000"></b></span>
						<br />
						<form method="POST"
							action="<?= KUMBIA_PATH ?>
							pagos/fichaReinscripcion/">
							<input type="hidden" name="registro" id="registro" value="<?= $registro ?>">
							<input type="hidden" name="NumConcepto" id="NumConcepto" value="201">
							<input type="submit" name="Ficha" value="Imprimir Ficha">
						</form>
						
					<?
					}
					else if( $status == 1 ){
					?>
						<h1 style="color: #AA0000">Inscripci&oacute;n</h1>
						<span style="color: #FF8D0F"></span><b>Favor de Imprimir su ficha
						de inscripci&oacute;n para poder realizar su pago,
						la ficha se paga en Banorte.
						<br /><span style="color: #AA0000"></b></span>
						<br />
						<form method="POST"
							action="<?= KUMBIA_PATH ?>
							pagos/fichaReinscripcion/">
							<input type="hidden" name="registro" id="registro" value="<?= $registro ?>">
							<input type="hidden" name="NumConcepto" id="NumConcepto" value="101">
							<input type="submit" name="Ficha" value="Imprimir Ficha">
						</form>
					<?
					}*/
					?>
			          <!--
					<h1 style="color: #AA0000">Selección de Cursos</h1>
					<p>
						<span style="color: #FF8D0F"></span><b>Se les comunica a todos los alumnos de ingenier&iacute;a que el
						calendario para captura de horarios correspondiente al semestre 
						<br /><span style="color: #AA0000">*Agosto - Diciembre 2010, será de
						la siguiente manera:</b></span>
						<ul>
							<li>Alumnos Regulares: 05 al 20 de Julio de 2010</li>
							<li>Alumnos Irregulares: 20 al 28 de Julio de 2010</li>
							<li>Alumnos Condicionados: 04 al 11 de Agosto de 2010</li>
						</ul>

						Recuerda que la apertura se realiza en base al promedio obtenido en el semestre
						inmediato posterior, es necesario	que respetes las fechas establecidas para dicha
						captura, de lo contrario deberas tomar solo las asignaturas que cuenten
						con lugares disponibles al igual que los horarios.
					</p>
					-->
  <!--
					<p>
						<b>
						Debido a problemas de logística en el armado de los grupos y corredores, estamos aplazando el inicio de la selección de cursos al Jueves, esto para tener un proceso de selección sin contingencias.
						<br><br>
						Consulta la página antes del día antes mencionado para que verifiques la hora en la que te tocara capturar.
						</b>
					</p>
-->
	              </p>
		         
		      </div>
				<br />
				<!---
				<h2>Mensaje importante para los alumnos que toman optativas.</h2>
				<p>El CETI ha convenido con la CANIETI (CÁMARA NACIONAL DE LA INDUSTRIA ELECTRÓNICA DE TELECOMUNICACIONES Y TECNOLOGÍAS DE LA INFORMACIÓN), la participación de empresas en el proceso de enseñanza - aprendizaje de este centro de estudios mediante la participación activa del personal directivo de diferentes empresas afiliadas a esta cámara, ofreciendo cursos a profesores y alumnos para facilitar la incorporación de estos últimos al sector productivo.</p>
				<p>Los requisitos para como alumno de del nivel de licenciatura de CETI puedas participar son: lectura y comprensión del idioma inglés (algunas tareas son sobre bibliografía en inglés), y ser un alumno responsable y con alto grado de cumplimiento en los trabajos asignados en el estudio de este curso.  </p>
				<p>Si cubres los requisitos, deberás seleccionar en tu horario el curso "MCT271" para tomar "Electrónica Automotriz", y "MCT280" para "Manufactura Electrónica". Estos cursos se podrán seleccionar por los alumnos de las carreras de Mecatrónica y Electrónica (solo "Manufactura electrónica") dados los contenidos que pueden ser aplicables a asignaturas similares en sus respectivos planes de estudio.</p>
				<p>Cualquier duda o aclaración a este respecto comunicarse con: M. en C. Francisco Javier Medina en el Departamento de Estudios de Nivel Licenciatura de CETI.</p>
				<p><b>Contenidos de los cursos:</b></p>
				<?= link_to('files/Materia.doc','Manufactura en la Industria Electrónica')?>
				<?= link_to('files/Continental.doc','Electrónica Automotriz')?>
				-->
			</div>
		</td>
	</tr>
</table>
<?php } ?>
</center>