<center>
<table>
	<tr>
		<td width="900" bgcolor="#FFFFFF"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>OFERTA DE CURSOS</b></div>
			<hr><br>
			<div style="font-size: 11px;">
				Los cursos elegibles para el siguiente ciclo obedecen exclusivamente a lo previsto en el plan de estudios de la carrera. Las posibilidades reales de elección dependerán de la oferta.
				<br><br>
				La cursos disponible para este semestre se presentan a continuación, para tener una mejor organización, hemos filtrado solo los cursos que puedes tomar de acuerdo al plan de estudios, además se muestran los cursos que actualmente estas tomando por si existierá la posibilidad de tener que repetir alguna materia.
				
				<br><br><br>
				<center><h3>ESTA SECCION NO ESTA DISPONIBLE POR EL MOMENTO</h3></center>
			</div>
		</div></td>
	</tr>
</table>
</center>