<style type="text/css">	
	.nada{
		padding-left:10px;
	}
	select{
		width:500px;
	}
</style>
<center>
<table>
	<tr>
		<td width="900"><div align="justify">
			<br>
			<div style="font-size: 14px;">
			<?= img_tag("adorno.gif","border: 0") ?><b style="color: #1569C7;">SELECCIÓN DE CURSOS: </b>
			<i style="color:#FF0000;"><b>PASO 3</b>, SELECCIÓN DE MATERIAS</i>
			<hr><br>
			<div style="font-size: 11px;">
				El <b>tercer y último paso</b>
                consiste en seleccionar los grupos donde quieres cursar las materias 
                seleccionadas en el paso 2, es necesario mencionar que los grupos que selecciones <b>DEBERÁN tener lugares disponibles</b>.
                <br>
                <br>
                Un punto muy importante es este proceso de selección, es que <b>NO deben existir cruces</b>
                con los grupos que selecciones.
                <br>
                <br>
                Una vez terminado este paso, la selección esta terminada y deberás imprimir tu horario de cursos para 
                cualquier posible aclaración en el futuro.				
			</div>
			<br>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;">
				<tr>
					<td width="150" height="25" bgcolor="#FFCA5B">&nbsp;<b>Nombre del alumno: </b></td>
					<td width="400" colspan="3" bgcolor="#EEEEEE">&nbsp;<?= $alumno ?> (<?= $registro ?>)</td>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Promedio: </b></td>
					<td width="100" bgcolor="#EEEEEE">&nbsp;<?= $promedio ?></td>
				</tr>
				<tr>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Especialidad: </b></td>
					<td width="400" colspan="3" bgcolor="#EEEEEE">&nbsp;<?= $especialidad ?></td>
					<td width="150" height="25" bgcolor="#FFCA5B"><b>&nbsp;Número de créditos: </b></td>
					<td width="100" bgcolor="#EEEEEE">&nbsp;<?= $ncreditos ?></td>
				</tr>
			</table>
			<br>
			<?
				$xsalonsitos = new Xsalones();
			?>
			<?php if($mensaje){ ?>
			<center class="fondoamarillo">
				<h2><?= $mensaje ?></h2>
			</center>
			<?php } ?>
				<?php if($seleccion) ?>
				<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;">										
				<?php
					foreach($seleccion as $sel){
				?>									
					<tr class="fondoazul">
						<th colspan="10" align="center" style="font-size:14px;" height="25"><?= $sel -> curso ?>, <?= $seleccionados[$sel -> curso] -> materia ?> - <?= $materiales[$seleccionados[$sel -> curso] -> materia] ?></th>
					</tr>
					<tr bgcolor="#FFCA5B">
						<th align="center">&nbsp;</th>
						<th align="center">Profesor</th>
						<th align="center">LUN</th>
						<th align="center">MAR</th>
						<th align="center">MIE</th>
						<th align="center">JUE</th>
						<th align="center">VIE</th>
						<th align="center">SAB</th>
					</tr>
					<tr>
						<form action="<?= KUMBIA_PATH ?>alumno/deseleccionar" method="post">
							<input type="hidden" name="idcurso" value="<?= $sel -> id ?>">
							<td rowspan="2"><input type="submit" value="Deseleccionar" class="boton"></td>
						</form>
						<td rowspan="2" width="340" align="center" bgcolor="<?= $bg ?>"><?= $maestros[$seleccionados[$sel -> curso] -> nomina ]; ?></td>
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
							if( $seleccionados[$sel -> curso] -> lunesi !=0 || $seleccionados[$sel -> curso] -> lunesf != 0){
						?>
								<?= $seleccionados[$sel -> curso] -> lunesi ?>:00<br><?= $seleccionados[$sel -> curso] -> lunesf ?>:00
						<?php
								if( $seleccionados[$sel -> curso] -> lunesi2 !=0 || $seleccionados[$sel -> curso] -> lunesf2 != 0){
						?>
									<br />
									<?= $seleccionados[$sel -> curso] -> lunesi2 ?>:00<br><?= $seleccionados[$sel -> curso] -> lunesf2 ?>:00
						<?
								}
							}
							else{
								echo "&nbsp;";
							}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
							if( $seleccionados[$sel -> curso] -> martesi !=0 || $seleccionados[$sel -> curso] -> martesf != 0){
						?>
								<?= $seleccionados[$sel -> curso] -> martesi ?>:00<br><?= $seleccionados[$sel -> curso] -> martesf ?>:00
						<?php
								if( $seleccionados[$sel -> curso] -> martesi2 !=0 || $seleccionados[$sel -> curso] -> martesf2 != 0){
						?>
									<br />
									<?= $seleccionados[$sel -> curso] -> martesi2 ?>:00<br><?= $seleccionados[$sel -> curso] -> martesf2 ?>:00
						<?
								}
							}
							else{
								echo "&nbsp;";
							}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
							if( $seleccionados[$sel -> curso] -> miercolesi !=0 || $seleccionados[$sel -> curso] -> miercolesf != 0){
						?>
								<?= $seleccionados[$sel -> curso] -> miercolesi ?>:00<br><?= $seleccionados[$sel -> curso] -> miercolesf ?>:00
						<?php
								if( $seleccionados[$sel -> curso] -> miercolesi2 !=0 || $seleccionados[$sel -> curso] -> miercolesf2 != 0){
						?>
									<br />
									<?= $seleccionados[$sel -> curso] -> miercolesi2 ?>:00<br><?= $seleccionados[$sel -> curso] -> miercolesf2 ?>:00
						<?
								}
							}
							else{
								echo "&nbsp;";
							}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
							if( $seleccionados[$sel -> curso] -> juevesi !=0 || $seleccionados[$sel -> curso] -> juevesf != 0){
						?>
								<?= $seleccionados[$sel -> curso] -> juevesi ?>:00<br><?= $seleccionados[$sel -> curso] -> juevesf ?>:00
						<?php
								if( $seleccionados[$sel -> curso] -> juevesi2 !=0 || $seleccionados[$sel -> curso] -> juevesf2 != 0){
						?>
									<br />
									<?= $seleccionados[$sel -> curso] -> juevesi2 ?>:00<br><?= $seleccionados[$sel -> curso] -> juevesf2 ?>:00
						<?
								}
							}
							else{
								echo "&nbsp;";
							}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
							if( $seleccionados[$sel -> curso] -> viernesi !=0 || $seleccionados[$sel -> curso] -> viernesf != 0){
						?>
								<?= $seleccionados[$sel -> curso] -> viernesi ?>:00<br><?= $seleccionados[$sel -> curso] -> viernesf ?>:00
						<?php
								if( $seleccionados[$sel -> curso] -> viernesi2 !=0 || $seleccionados[$sel -> curso] -> viernesf2 != 0){
						?>
									<br />
									<?= $seleccionados[$sel -> curso] -> viernesi2 ?>:00<br><?= $seleccionados[$sel -> curso] -> viernesf2 ?>:00
						<?
								}
							}
							else{
								echo "&nbsp;";
							}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
							if( $seleccionados[$sel -> curso] -> sabadoi !=0 || $seleccionados[$sel -> curso] -> sabadof != 0){
						?>
								<?= $seleccionados[$sel -> curso] -> sabadoi ?>:00<br><?= $seleccionados[$sel -> curso] -> sabadof ?>:00
						<?php
								if( $seleccionados[$sel -> curso] -> sabadoi2 !=0 || $seleccionados[$sel -> curso] -> sabadof2 != 0){
						?>
									<br />
									<?= $seleccionados[$sel -> curso] -> sabadoi2 ?>:00<br><?= $seleccionados[$sel -> curso] -> sabadof2 ?>:00
						<?
								}
							}
							else{
								echo "&nbsp;";
							}
						?>
						</th>
					</tr>
					<!-- --><!-- --><!-- --><!-- --><!-- --><!-- --><!-- --><!-- --><!-- --><!-- -->
					<tr>
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
						if($seleccionados[$sel -> curso] -> lunesi!=0 || $seleccionados[$sel -> curso] -> lunesf != 0){
							if ( $salones2 = $xsalonsitos -> find_first 
									("id = ".$salones[$seleccionados[$sel -> curso] -> luness]) ){
								echo $salones2 -> edificio.":".$salones2 -> nombre;
							}
						}
						else{
							echo "&nbsp;";
						}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
						if($seleccionados[$sel -> curso] -> martesi!=0 || $seleccionados[$sel -> curso] -> martesf != 0){
							if ( $salones2 = $xsalonsitos -> find_first 
									("id = ".$salones[$seleccionados[$sel -> curso] -> martess]) ){
								echo $salones2 -> edificio.":".$salones2 -> nombre;
							}
						}
						else{
							echo "&nbsp;";
						}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
						if($seleccionados[$sel -> curso] -> miercolesi!=0 || $seleccionados[$sel -> curso] -> miercolesf != 0){
							if ( $salones2 = $xsalonsitos -> find_first 
									("id = ".$salones[$seleccionados[$sel -> curso] -> miercoless]) ){
								echo $salones2 -> edificio.":".$salones2 -> nombre;
							}
						}
						else{
							echo "&nbsp;";
						}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
						if($seleccionados[$sel -> curso] -> juevesi!=0 || $seleccionados[$sel -> curso] -> juevesf != 0){
							if ( $salones2 = $xsalonsitos -> find_first 
									("id = ".$salones[$seleccionados[$sel -> curso] -> juevess]) ){
								echo $salones2 -> edificio.":".$salones2 -> nombre;
							}
						}
						else{
							echo "&nbsp;";
						}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
						if($seleccionados[$sel -> curso] -> viernesi!=0 || $seleccionados[$sel -> curso] -> viernesf != 0){
							if ( $salones2 = $xsalonsitos -> find_first 
									("id = ".$salones[$seleccionados[$sel -> curso] -> vierness]) ){
								echo $salones2 -> edificio.":".$salones2 -> nombre;
							}
						}
						else{
							echo "&nbsp;";
						}
						?>
						</td>
						
						<td width="45" align="center" bgcolor="<?= $bg ?>">
						<?php
						if($seleccionados[$sel -> curso] -> sabadoi!=0 || $seleccionados[$sel -> curso] -> sabadof != 0){
							if ( $salones2 = $xsalonsitos -> find_first 
									("id = ".$salones[$seleccionados[$sel -> curso] -> sabados]) ){
								echo $salones2 -> edificio.":".$salones2 -> nombre;
							}
						}
						else{
							echo "&nbsp;";
						}
						?>
						</td>
					</tr>
				<?php
					}
				?>
				</table><br>
			<?php
			$i=0;
			$pendientes = 0;
			if($matelocas)
			foreach($matelocas as $mat){
				$i++;
				$bandera=0;
				if($seleccion){
					foreach($seleccion as $sel){
						if(substr($mat,0,strlen($seleccionados[$sel -> curso] -> materia)) ==
								$seleccionados[$sel -> curso] -> materia){
							$bandera=1;
							break;
						}
					}
				}
				
				if($bandera==1)
					continue;
				
				$pendientes = 1;
			?>
				<form action="<?= KUMBIA_PATH ?>alumno/seleccionar" method="post">
				<table border="1" cellpadding="1" cellspacing="1" bordercolor="#999999" style="font-size: 10px;">
					<tr class="fondoazul">
						<th colspan="10" align="center" style="font-size:14px;" height="25"><?= $mat ?></th>
					</tr>
			<?php
				$jj=0;
				if ($grupos[$i-1]){
					foreach($grupos[$i-1] as $grupo){
						$jj++
						?>
						<tr bgcolor="#FFCA5B">
							<th align="center">&nbsp;</th>
							<th align="center">Profesor</th>
							<th align="center">CUPO</th>					
							<th align="center">DISP</th>					
							<th align="center">LUN</th>
							<th align="center">MAR</th>
							<th align="center">MIE</th>
							<th align="center">JUE</th>
							<th align="center">VIE</th>
							<th align="center">SAB <? echo "grupo ".count($grupos) ?></th>
						</tr>
						<?php
							if($i%2==0){
								$bg = "#F6F6F6";
							}
							else{
								$bg = "#EEEEEE";
							}
						?>				
						<tr>					
							<?php 
							if ($grupo -> disponibilidad <= 0){
									$idcolor="rojo";
							}else{
								$idcolor="verde";
							} 
							?>
							<td rowspan="2">
								<?php
									if ($grupo -> disponibilidad > 0){
								?>
										<input type="radio" name="grupo" value="<?= $grupo -> id ?>"<?php if($jj==1){ echo 'Checked'; }?>>
										<input type="hidden" name="materia" value="<?= $grupo -> materia ?>">
								<?php
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
							<td width="340" align="center" bgcolor="<?= $bg ?>">
								<?= $maestros[$grupo -> nomina]; ?>
							</td>
							<td width="100" align="center" bgcolor="<?= $bg ?>">
								<?= $grupo -> cupo ?>
							</td>
							<td width="100" align="center" bgcolor="<?= $bg ?>">
								<strong><div id="<?= $idcolor ?>" style="font-size:13px;"><?= $grupo -> disponibilidad ?></div></strong>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
								<?php
									if( $grupo -> lunesi !=0 || $grupo -> lunesf != 0){
								?>
										<?= $grupo -> lunesi ?>:00<br><?= $grupo -> lunesf ?>:00
								<?php
										if( $grupo -> lunesi2 != 0 || $grupo -> lunesf2 != 0 ){
								?>
											<br />
											<?= $grupo -> lunesi2 ?>:00<br><?= $grupo -> lunesf2 ?>:00
								<?
										}
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
								<?php
									if( $grupo -> martesi !=0 || $grupo -> martesf != 0){
								?>
										<?= $grupo -> martesi ?>:00<br><?= $grupo -> martesf ?>:00
								<?php
										if( $grupo -> martesi2 != 0 || $grupo -> martesf2 != 0 ){
								?>
											<br />
											<?= $grupo -> martesi2 ?>:00<br><?= $grupo -> martesf2 ?>:00
								<?
										}
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
								<?php
									if( $grupo -> miercolesi !=0 || $grupo -> miercolesf != 0){
								?>
										<?= $grupo -> miercolesi ?>:00<br><?= $grupo -> miercolesf ?>:00
								<?php
										if( $grupo -> miercolesi2 != 0 || $grupo -> miercolesf2 != 0 ){
								?>
											<br />
											<?= $grupo -> miercolesi2 ?>:00<br><?= $grupo -> miercolesf2 ?>:00
								<?
										}
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
								<?php
									if( $grupo -> juevesi !=0 || $grupo -> juevesf != 0){
								?>
										<?= $grupo -> juevesi ?>:00<br><?= $grupo -> juevesf ?>:00
								<?php
										if( $grupo -> juevesi2 != 0 || $grupo -> juevesf2 != 0 ){
								?>
											<br />
											<?= $grupo -> juevesi2 ?>:00<br><?= $grupo -> juevesf2 ?>:00
								<?
										}
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
								<?php
									if( $grupo -> viernesi !=0 || $grupo -> viernesf != 0){
								?>
										<?= $grupo -> viernesi ?>:00<br><?= $grupo -> viernesf ?>:00
								<?php
										if( $grupo -> viernesi2 != 0 || $grupo -> viernesf2 != 0 ){
								?>
											<br />
											<?= $grupo -> viernesi2 ?>:00<br><?= $grupo -> viernesf2 ?>:00
								<?
										}
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
								<?php
									if( $grupo -> sabadoi !=0 || $grupo -> sabadof != 0){
								?>
										<?= $grupo -> sabadoi ?>:00<br><?= $grupo -> sabadof ?>:00
								<?php
										if( $grupo -> sabadoi2 != 0 || $grupo -> sabadof2 != 0 ){
								?>
											<br />
											<?= $grupo -> sabadoi2 ?>:00<br><?= $grupo -> sabadof2 ?>:00
								<?
										}
									}
									else{
										echo "&nbsp;";
									}
								?>
							</td>
						</tr>
						<tr>
							<td colspan="3" width="480" align="center" bgcolor="<?= $bg ?>">&nbsp;</th>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
							<?php
								if($grupo -> lunesi!=0 || $grupo -> lunesf != 0){
									if ( $salones = $xsalonsitos -> find_first ("id = ".$grupo -> luness) ){
										echo $salones -> edificio.":".$salones -> nombre;
									}
								}
								else{
									echo "&nbsp;";
								}
							?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
							<?php
								if($grupo -> martesi!=0 || $grupo -> martesf != 0){
									if ( $salones = $xsalonsitos -> find_first ("id = ".$grupo -> martess) ){
										echo $salones -> edificio.":".$salones -> nombre;
									}
								}
								else{
									echo "&nbsp;";
								}
							?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
							<?php
								if($grupo -> miercolesi!=0 || $grupo -> miercolesf != 0){
									if ( $salones = $xsalonsitos -> find_first ("id = ".$grupo -> miercoless) ){
										echo $salones -> edificio.":".$salones -> nombre;
									}
								}
								else{
									echo "&nbsp;";
								} 
							?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
							<?php
								if($grupo -> juevesi!=0 || $grupo -> juevesf != 0){
									if ( $salones = $xsalonsitos -> find_first ("id = ".$grupo -> juevess) ){
										echo $salones -> edificio.":".$salones -> nombre;
									}
								}
								else{
									echo "&nbsp;";
								}
							?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
							<?php
								if($grupo -> viernesi!=0 || $grupo -> viernesf != 0){
									if ( $salones = $xsalonsitos -> find_first ("id = ".$grupo -> vierness) ){
										echo $salones -> edificio.":".$salones -> nombre;
									}
								}
								else{
									echo "&nbsp;";
								}
							?>
							</td>
							<td width="45" align="center" bgcolor="<?= $bg ?>">
							<?php
								if($grupo -> sabadoi!=0 || $grupo -> sabadof != 0){
									if ( $salones = $xsalonsitos -> find_first ("id = ".$salones[$grupo -> sabados]) ){
										echo $salones -> edificio.":".$salones -> nombre;
									}
								}
								else{
									echo "&nbsp;";
								}
							?>
							</td>
						</tr>
						<?php
					}
					?>
					<tr>
					
					<td colspan="10" width="480" align="center" bgcolor="<?= $bg ?>">
					<br>
						<input type="submit" value="Seleccionar grupo" class="boton">
					<br><br>
					</td>
					
				</tr>
				
			</table>
			</form>
			<br><br>
			<?php
				}
				else{
					?>
					<tr>
						<td width="750" class="fondoamarillo" id="rojo">
							<center><h2>NO HAY GRUPOS DE ESTA MATERIA</h2></center>
						</td>
					</tr>
					</table>
					</form>
					<br><br>
					<?php
				}
			}
			
			if( $pendientes == 0 ){
			?>
				<center>
					<form method="post" action="<?= KUMBIA_PATH ?>alumno/horario">
						<input type="submit" value="Terminar Selección" class="boton" style="font-size:20px; height:40px;">
					</form>
					<br/>
				</center>
			<?php
			}
			?>
		</td>
	</tr>
</table>
<br />
			<table>
				<tr>					
					<form method="post" action="<?= KUMBIA_PATH ?>alumno/seleccion2">
					<td width="50">						
						<input type="submit" value="<< Paso 2" class="boton">
					</td>
					</form>
					<td width="50">&nbsp;</td>
					<td width="650">&nbsp;</td>
				</tr>
			</table>
</center>
<br />&nbsp;