<script type='text/javascript'>
function validar( formulario ) {
  	if (formulario.nombre.value=="") {
		alert("El campo nombre no debe quedar vacio");
		formulario.nombre.focus();
		return false;
  	}
	
	if (formulario.paterno.value=="") {
		alert("El campo apellido paterno no debe quedar vacio");
		formulario.paterno.focus();
		return false;
  	}
	
	if (formulario.materno.value=="") {
		alert("El campo apellido materno no debe quedar vacio");
		formulario.materno.focus();
		return false;
  	}
	
	if (formulario.sexo.value=="") {
		alert("Debes elegir un genero");
		formulario.sexo.focus();
		return false;
  	}
	
	if (formulario.domicilio.value=="") {
		alert("El campo domicilio no debe quedar vacio");
		formulario.domicilio.focus();
		return false;
  	}
	
	if (formulario.cp.value=="") {
		alert("El campo codigo postal no debe quedar vacio");
		formulario.cp.focus();
		return false;
  	}
	
	if (formulario.ciudad.value=="") {
		alert("El campo ciudad no debe quedar vacio");
		formulario.ciudad.focus();
		return false;
  	}
	
	if (formulario.telefono.value=="") {
		alert("El campo telefono no debe quedar vacio");
		formulario.telefono.focus();
		return false;
  	}
	
	if (formulario.correo.value=="") {
		alert("El campo correo electrónico no debe quedar vacio");
		formulario.correo.focus();
		return false;
  	}
	alert("Muchas gracias por actualizar tus datos");
}


</script>
<center>
<h1>Modulo de Actualización</h1>
<form method="POST" action="<?= KUMBIA_PATH.$controller_name ?>/actualizar" onSubmit="return validar(this);">
<table border="1" cellpadding="1" cellspacing="1" style="font-size:11px;">
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Nombre: </b></td>
		<td width="300"><input type="text" name="nombre" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Apellido paterno: </b></td>
		<td width="300"><input type="text" name="paterno" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Apellido materno: </b></td>
		<td width="300"><input type="text" name="materno" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Fecha de nacimiento: </b></td>
		<td width="300">
			<select name="d">
				<?php for($i=1;$i<32;$i++){ ?>
					<option value="<?= $i ?>"><?= $i ?></option>
				<?php } ?>
			</select>
			<select name="m">
				<option value="1">Enero&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
				<option value="2">Febrero</option>
				<option value="3">Marzo</option>
				<option value="4">Abril</option>
				<option value="5">Mayo</option>
				<option value="6">Junio</option>
				<option value="7">Julio</option>
				<option value="8">Agosto</option>
				<option value="9">Septiembre</option>
				<option value="10">Octubre</option>
				<option value="11">Noviembre</option>
				<option value="12">Diciembre</option>
			</select>
			<select name="y">
				<?php for($i=1995;$i>=1960;$i--){ ?>
					<?php if($i==1991){ ?>
						<option value="<?= $i ?>" SELECTED><?= $i ?></option>
					<?php } else { ?>
						<option value="<?= $i ?>"><?= $i ?></option>
					<?php } ?>
				<?php } ?>
			</select>
		</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Genero: </b></td>
		<td width="300"><input type="radio" name="sexo" value="H"> Hombre <input type="radio" name="sexo" value="M"> Mujer</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Estado civil: </b></td>
		<td width="300">
			<select name="civil">
				<option value="SOLTERO">Soltero(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
				<option value="CASADO">Casado(a)</option>
				<option value="DIVORCIADO">Divorciado(a)</option>
				<option value="VIUDO">Viudo(a)</option>
				<option value="UNION LIBRE">Unión Libre</option>
			</select>
		</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Tipo de sangre: </b></td>
		<td width="300">
			<select name="sangre">
				<option value="O+">O Positivo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
				<option value="A+">A Positivo</option>
				<option value="B+">B Positivo</option>
				<option value="AB+">AB Positivo</option>
				<option value="O-">O Negativo</option>
				<option value="A-">A Negativo</option>
				<option value="B-">B Negativo</option>
				<option value="AB-">AB Negativo</option>
			</select>
		</td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Domicilio: </b></td>
		<td width="300"><input type="text" name="domicilio" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Colonia: </b></td>
		<td width="300"><input type="text" name="colonia" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Código postal: </b></td>
		<td width="300"><input type="text" name="cp" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Ciudad: </b></td>
		<td width="300"><input type="text" name="ciudad" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Teléfono: </b></td>
		<td width="300"><input type="text" name="telefono" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;Correo Electrónico: </b></td>
		<td width="300"><input type="text" name="correo" size="50"></td>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B"><b>&nbsp;CURP: </b></td>
		<td width="300"><input type="text" name="curp" size="50"></td>
	</tr>
</table>
<br>
<input type="submit" value="ACEPTAR" style="font-size:20px; text-transform: uppercase;">
<input type="hidden" name="registro" value="<?= $registro ?>">
</form>