<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<head>
	<meta http-equiv='Content-type' content='text/html; charset=<?=Kumbia::get_active_app_charset()?>' />
	<title>Kumbia PHP Framework</title>
	<style type="text/css">
		body { background: #434343; font-family: "Lucida Grande",Verdana; }
		#contenido { background-color: #fff; border: #999 1px solid; padding: 10px ; width: 70%; margin:3em auto; }
		#logo { float: left; }
		#version {float: right; font-size: 14pt; color: #900; margin: 1.5em 3em 0 0;}
		#info { padding: 3em; clear:both; }
		#info h1 { font-size: 2em; color: #900; margin: 0; text-align:center }
		#info p,li { color: #900; font-size: 15px; }
		#footer a { text-decoration: none; font-weight: bold; font-size: 14px; }
		#footer a:hover { color: #FF6600; }
		#footer ul.links { text-align: center; list-style: none inside; padding: 0; }
		#footer ul.links li { display: inline; }
	</style>
</head>
<body>
<div id="contenido">
	<?php echo img_tag('site_logo.gif','id: logo','alt: KumbiaPHP') ?>				
	<h1 id="version">VERSI&Oacute;N <?php echo Kumbia::KUMBIA_VERSION?> </h1>
			
		<div id="info">
			<h1>Bienvenido a Kumbia PHP Framework</h1>
			<p>Ya puedes empezar a usar el mejor framework para desarrollar aplicaciones web con PHP.</p>
			<p>Kumbia es un web framework libre escrito en PHP5. Basado en las mejores pr&aacute;cticas
				de desarrollo web, usado en software comercial y educativo, Kumbia fomenta la velocidad	
				y eficiencia en la creaci&oacute;n y mantenimiento de aplicaciones web, reemplazando t&aacute;reas de
				codificaci&oacute;n repetitivas por poder, control y placer.</p>	
			<p>Si ha visto a Ruby-Rails/Python-Django encontrar&aacute; a Kumbia una alternativa para proyectos en PHP con caracter&iacute;sticas como:</p>
			<ul>
				<li>Sistema de Plantillas sencillo</li>
				<li>Administraci&oacute;n de Cache</li>
				<li>Scaffolding Avanzado</li>
				<li>Programaci&oacute;n Modular</li>
				<li>Modelo de Objetos y Separaci&oacute;n MVC</li>
				<li>Soporte para AJAX</li>
				<li>Generaci&oacute;n de Formularios</li>
				<li>Componentes Gr&aacute;ficos</li>
				<li>Seguridad</li>
			</ul>
			<p>y muchas cosas m&aacute;s. Kumbia puede ser la soluci&oacute;n que esta buscando. </p>
		</div>
		<div id="footer">
			<ul class="links">
				<li><a href='http://www.kumbiaphp.com/blog/'>Web</a> |</li>
				<li><a href='http://www.kumbiaphp.com/foro/'>Foro</a> |</li>
				<li><a href='http://groups.google.com/group/kumbia'>Grupo</a> |</li>
				<li><a href='http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt'>Licencia GPL</a></li>
			</ul>
		</div>
</div>
</body>
</html>