<center>
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionListado"><? echo "Listado" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionCurso"><? echo "Por Curso" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionMateria"><? echo "Por Materia" ?></a>
			</td>
		<?
		if( Session::get_data('coordinacion') == "MCT" || Session::get_data('coordinacion') == "TCB" || Session::get_data('registro') == 1965 ){
		?>
		</tr>
		<tr>
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionListadoT"><? echo "Listado Tonal&aacute;" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionCursoT"><? echo "Por Curso  Tonal&aacute;" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionMateriaT"><? echo "Por Materia  Tonal&aacute;" ?></a>
			</td>
		<?
		}
		?>
		</tr>
	</table>
	<?php render_partial("estadisticas/periodoLetra"); ?>
</center>