<div class="menu">
	<a href="<?= KUMBIA_PATH ?>salones/index" onmouseover="toolTip('Modulo para sacar horarios de Infraestructura',this)" >Infraestructura</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;	
	<a href="<?= KUMBIA_PATH ?>salones/infraestructura" onmouseover="toolTip('Modulo para sacar horarios de <br>prefectura de los salones por divisiones',this)">Prefectura</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
<div>



