<!--Se llaman los archivos css y js-->
<?= javascript_library_tag('jquery-1.4.4.min'); ?>
<?= javascript_library_tag('jquery.ui.core'); ?>
<?= javascript_library_tag('jquery.ui.datepicker'); ?>

<?= stylesheet_link_tag('smoothness/jquery-ui-1.7.2.custom'); ?>
<?= stylesheet_link_tag('dialog_box'); ?>
<!--Termina llamado de archivos-->


<script type='text/javascript'>
function validar( formulario ) {
  	if (formulario.nombre.value=="") {
		alert("El campo nombre no debe quedar vacio");
		formulario.nombre.focus();
		return false;
  	}
	
	if (formulario.paterno.value=="") {
		alert("El campo apellido paterno no debe quedar vacio");
		formulario.paterno.focus();
		return false;
  	}
	
	if (formulario.materno.value=="") {
		alert("El campo apellido materno no debe quedar vacio");
		formulario.materno.focus();
		return false;
  	}
	
	if (formulario.sexo.value=="") {
		alert("Debes elegir un genero");
		formulario.sexo.focus();
		return false;
  	}
	
	if (formulario.domicilio.value=="") {
		alert("El campo domicilio no debe quedar vacio");
		formulario.domicilio.focus();
		return false;
  	}
	
	if (formulario.cp.value=="") {
		alert("El campo codigo postal no debe quedar vacio");
		formulario.cp.focus();
		return false;
  	}
	
	if (formulario.ciudad.value=="") {
		alert("El campo ciudad no debe quedar vacio");
		formulario.ciudad.focus();
		return false;
  	}
	
	if (formulario.telefono.value=="") {
		alert("El campo telefono no debe quedar vacio");
		formulario.telefono.focus();
		return false;
  	}
	
	if (formulario.correo.value=="") {
		alert("El campo correo electrónico no debe quedar vacio");
		formulario.correo.focus();
		return false;
  	}
	alert("Muchas gracias por actualizar tus datos");
}


</script>

<style type="text/css">	
	.infoalumno{
		text-align:justify;
		font-size:13px;
	}
	.infoalumno td{
		padding:0 10px 0 10px;
	}
	.infoalumno th{
		padding:0 10px 0 10px;
		font-size:14px;
	}
</style>
	
<center>
<table>
	<tr>
		<td width="900" bgcolor="#FFFFFF"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>Seguro Medico</b></div>
			<hr><br>
			<div style="font-size: 11px;">
			El proceso de actualización de datos es recopilar los datos personales de cada uno de los alumnos, 
			los cuales deberán estar escritos correctamente para poder agilizar los diferentes procesos que se 
			realizan en el departamento de apoyo académico.
			<br><br>
			Este proceso es <b>obligatorio</b> y será necesario para poder consultar tus calificaciones del primer 
			parcial. La información proporcionada es confidencial y solo utilizada para procesos académicos.
			</div>
			<br />
			<?= render_partial("alumno/info_alumno"); ?>
			<br />
			</div>
		</div></td>
	</tr>
	<tr>
		<td align="center">
			<div align="center">
	<style type="text/css">
		.forma{
			width:275px;
			text-transform: uppercase;
		}
	</style>
<form method="POST" action="<?= KUMBIA_PATH ?>servicio_medico/actualizar_seguro_medico" onSubmit="return validar(this);">
<table border="1" cellpadding="1" cellspacing="1" style="font-size:11px;">
	<tr>
		<th colspan="2" height="20" bgcolor="#1569C7" style="color:#FFFFFF">
			MODULO DE ACTUALIZACIÓN
		</th>
	</tr>
	<tr>
		<td width="200" bgcolor="#FFCA5B" align="left"><b>&nbsp;&iquest;Cuentas con alg&uacute;n tipo de seguridad social? </b></td>
		<td width="280" align="left">
		<input type="radio" name="seguridad_social" id="seguridad_social" value="SI" <? if(isset($xalumnosPersonal->seguridad_social) && $xalumnosPersonal->seguridad_social == "SI" ) echo "checked"; ?>> Si
		<input type="radio" name="seguridad_social" id="seguridad_social_" value="NO" <? if(isset($xalumnosPersonal->seguridad_social) && $xalumnosPersonal->seguridad_social == "NO" ) echo "checked"; ?>> No</td>
	</tr>
</table>
<br />
<div id="seguridad_container" name="seguridad_container">
</div>
<br />
<input type="submit" value="ACEPTAR" style="font-size:20px; text-transform: uppercase;">
<input type="hidden" name="registro" id="registro" value="<?= $registro ?>">
</form>
		</td>
	</tr>
</table>

<?
	print "<script type=\"text/javascript\">
	new Event.observe(\"seguridad_social\", \"click\", function(){
	var seguridad_social = document.getElementById(\"seguridad_social\").value;
	var registro = document.getElementById(\"registro\").value;
	new AJAX.viewRequest({
		action: \"servicio_medico/seguridad_mostrar_container/\"+".seguridad_social."+\"/\"+".registro."+\"\",
		container: \"seguridad_container\"
	})
	})
	</script>";
	print "<script type=\"text/javascript\">
	new Event.observe(\"seguridad_social_\", \"click\", function(){
	var seguridad_social = document.getElementById(\"seguridad_social_\").value;
	var registro = document.getElementById(\"registro\").value;
	new AJAX.viewRequest({
		action: \"servicio_medico/seguridad_mostrar_container/\"+".seguridad_social."+\"/\"+".registro."+\"\",
		container: \"seguridad_container\"
	})
	})
	</script>";
?>

<?php
if($xalumnosPersonal->seguridad_social=="SI"){
	print "<script type=\"text/javascript\">
	var seguridad_social = document.getElementById(\"seguridad_social\").value;
	var registro = document.getElementById(\"registro\").value;
	new AJAX.viewRequest({
		action: \"servicio_medico/seguridad_mostrar_container/\"+".seguridad_social."+\"/\"+".registro."+\"\",
		container: \"seguridad_container\"
	})
	</script>";
}
?>