	
	<tr>
        <td>
			<table border="0" cellpadding="0" cellspacing="0" width="800">
				<tr>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/index" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c1','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c1_f2.gif',1);"><img name="evaluacion_r1_c1" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c1.gif" width="99" height="30" border="0" id="evaluacion_r1_c1" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/alumnos" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c2','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c2_f2.gif',1);"><img name="evaluacion_r1_c2" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c2.gif" width="100" height="30" border="0" id="evaluacion_r1_c2" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/evaluaciones" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c3','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c3_f2.gif',1);"><img name="evaluacion_r1_c3" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c3.gif" width="100" height="30" border="0" id="evaluacion_r1_c3" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/cuestionario" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c4','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c4_f2.gif',1);"><img name="evaluacion_r1_c4" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c4.gif" width="100" height="30" border="0" id="evaluacion_r1_c4" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/rubros" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c5','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c5_f2.gif',1);"><img name="evaluacion_r1_c5" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c5.gif" width="100" height="30" border="0" id="evaluacion_r1_c5" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/reportes" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c6','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c6_f2.gif',1);"><img name="evaluacion_r1_c6" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c6.gif" width="100" height="30" border="0" id="evaluacion_r1_c6" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/estadisticas" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c7','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c7_f2.gif',1);"><img name="evaluacion_r1_c7" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c7.gif" width="100" height="30" border="0" id="evaluacion_r1_c7" alt="" /></a></td>
					<td><a href="<?= KUMBIA_PATH ?>evaluacion/salir" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('evaluacion_r1_c8','','<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c8_f2.gif',1);"><img name="evaluacion_r1_c8" src="<?= KUMBIA_PATH ?>/public/img/evaluacion/evaluacion_r1_c8.gif" width="101" height="30" border="0" id="evaluacion_r1_c8" alt="" /></a></td>
				</tr>
			</table>
		</td>
      </tr>
	  <tr>
		<td height="1">
		</td>
	  </tr>
	  <tr>
		<td align="center">
		<?= content(); ?>
		</td>
	  </tr>