<ul>
	<li class="li_inicio"><a>Alumnos</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/problemas_alumnos">Problemas Alumnos</a></li>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/correcionKardex">Correcci&oacute;n Kardex</a></li>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/correcionCalificaciones">Correcci&oacute;n Calif</a></li>
			<li><a href="<?=KUMBIA_PATH?>apoyo/cambiarEstado">Cambiar Estado</a></li>
			<li><a href="<?=KUMBIA_PATH?>apoyo/becas">Becas</a></li>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/condicionados">Condicionados</a></li>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/promocion_alumno">Promoci&oacute;n de Alumnos</a></li>
		</ul>
	</li>

	<li><a>Selecci&oacute;n Materias</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/abrirSeleccionAlumno">Abrir Seleccion</a></li>
			<li><a href="<?=KUMBIA_PATH?>ingcalculo/seleccionar_materias">Cargar Materias</a></li>
			<li><a href="<?= KUMBIA_PATH ?>capturarcursos/cupo_en_cursos_plan_rigido">Estad&iacute;sticas de Cursos</a></li>
		</ul>
	</li>
	
	<li><a href="<?=KUMBIA_PATH?>profesor/buscarAlumno">Buscar Alumno</a></li>
	
	<li><a href="<?=KUMBIA_PATH?>ingcalculo/cambiarContrasena">Cambiar Contrase&ntilde;a</a></li>
	
	<li><a href="<?=KUMBIA_PATH?>apoyo/cambiarEstado">Cambiar Estado</a>
	
	<li class="floatright">
		<a href="<?=KUMBIA_PATH?>seguridad/terminarsesion">
			<image src="<?=KUMBIA_PATH?>img/log_off.jpg" class="log_off" />
		</a>
	</li>
</ul>