<ul>
	<li class="li_inicio"><a>Inicio</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Informaci&oacute;n</a></li>
		</ul>
	</li>

	<li><a>Captura</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/captura">Captura Calificaciones</a></li>
			<li><a href="<?=KUMBIA_PATH?>profesor/tutorados">Tutorados</a></li>
		</ul>
	</li>

	<li><a>Horarios</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/horario">Horario</a></li>
			<li><a href="<?=KUMBIA_PATH?>profesor/listas">Listas</a></li>
			<li><a href="<?=KUMBIA_PATH?>profesor/capturarListaActividad">Asignarse Actividades</a></li>
		</ul>
	</li>
	<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Configuraci&oacute;n</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/cambiarContrasena">Cambiar Contrase&ntilde;a</a></li>
			<li><a href="<?=KUMBIA_PATH?>profesor/cambiarCorreo">Cambiar Correo</a></li>
		</ul>
	</li>
	<li class="floatright">
		<a href="<?=KUMBIA_PATH?>seguridad/terminarsesion">
			<image src="<?=KUMBIA_PATH?>img/log_off.jpg" class="log_off" />
		</a>
	</li>
</ul>