<ul>
	<li class="li_inicio"><a>Inicio</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>administrador/index">Inicio</a></li>
		</ul>
	</li>
	
	<li><a>Administraci&oacute;n General</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>administrador/planteles">Planteles</a></li>
			<li><a href="<?=KUMBIA_PATH?>administrador/carreras">Carreras</a></li>
			<li><a href="<?=KUMBIA_PATH?>administrador/materias">Materias</a></li>
			<li><a href="<?=KUMBIA_PATH?>administrador/planes">Planes de Estudio</a></li>
		</ul>
	</li>
	<?php if(Session::get('registro') == 8108 || Session::get('registro') == 1861){ ?>
		<li><a>Alumnos</a>
			<ul>
				<li><a href="<?=KUMBIA_PATH?>actualizacioning/modificainformacion">Modificar informaci&oacute;n personal</a></li>
				<?php if(Session::get('registro') == 8108){ ?>
					<li><a href="<?=KUMBIA_PATH?>cambiosalumno/index">Modificar Contrase&ntilde;a de Alumno</a></li>
					<li><a href="<?=KUMBIA_PATH?>cambiosalumno/correccioncalificaciones">Correcci&oacute;n de Calificaciones</a></li>
				<?php }?>
			</ul>
		</li>
	<?php }?>
	
	<li><a>Aspirantes</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>ventanilla/aspirantes/">Aspirantes</a></li>
			<li><a href="<?=KUMBIA_PATH?>aspirantes/listaConsulta">Consultar Expediente</a></li>
			<li><a href="<?=KUMBIA_PATH?>ventanilla/documentacion">Documentaci&oacute;n Aspirantes</a></li>
		</ul>
	</li>
	<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Administraci&oacute;n Alumnos</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>administrador/buscarAlumno">Buscar Alumno</a></li>
			<li><a href="<?=KUMBIA_PATH?>ventanilla/reactivarActualizacion">Reactivar Formulario</a></li>
			<li><a href="<?=KUMBIA_PATH?>ventanilla/checarContra">Ver Contrase&ntilde;a</a></li>
			<li><a href="<?=KUMBIA_PATH?>ventanilla/checarEstado">Checar Estado</a></li>
			<li><a href="<?=KUMBIA_PATH?>calificaciones/buscar">Ver Calificaciones</a></li>
			<li><a href="<?=KUMBIA_PATH?>administrador/checarPagos">Checar Pagos</a></li>
			<li><a href="<?=KUMBIA_PATH?>apoyo/cambiarEstado">Cambiar Estado</a></li>
			<li><a href="<?=KUMBIA_PATH?>apoyo/becas">Becas</a></li>
		</ul>
	</li>
	<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Configuraci&oacute;n</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>administrador/cambiar_contrasena">Cambiar Contrase&ntilde;a</a></li>
		</ul>
	</li>
	<?php if(Session::get('registro') == 2374 || Session::get('registro') == 1833 || Session::get('registro') == 2448 || Session::get('registro') == 9131 || Session::get('registro') == 9124 || Session::get('registro') == 9192 || Session::get('registro') == 2465){?>
		<li><a>CAJA</a>
			<ul>
				<li><a href="<?=KUMBIA_PATH?>caja/index">Solicitar Pagos</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/periodosAlumnos">Periodos Alumnos</a></li>
			</ul>
		</li>
	<?php
	  }
	 else if(Session::get('registro') == 8108 || Session::get('registro') == 2307){?>
		<li><a>CAJA</a>
			<ul>
				<li><a href="<?=KUMBIA_PATH?>caja/actualizarPagos">Actualizar Pagos</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/adminConceptos">Cambiar Conceptos</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/fechasConceptos">Fechas Conceptos</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/guardarReferencia">Guardar Referencia</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/periodosAlumnos">Periodos Alumnos</a></li>
				<li><a href="<?= KUMBIA_PATH ?>caja/reportes">Reporte Caja</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/index">Solicitar Pagos</a></li>
			</ul>
		</li>
	<?php }
	  else if(Session::get("tipousuario") == "VENTANILLA"){?>
		<li><a>CAJA</a>
			<ul>
			  <li><a href="<?=KUMBIA_PATH?>caja/periodosAlumnos">Periodos Alumnos</a></li>
			  <?php if(Session::get('registro') == 1861){?>
			    <li><a href="<?=KUMBIA_PATH?>caja/fechasConceptos">Fechas Conceptos</a></li>
				<li><a href="<?= KUMBIA_PATH ?>caja/reportes">Reporte Caja</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/index">Solicitar Pagos</a></li>
				<li><a href="<?=KUMBIA_PATH?>caja/verTramites">Ver Tramites</a></li>
			  <?php } ?>
			</ul>
		</li>
	<?php }?>
	<?php if(Session::get('registro') == 2551 || Session::get('registro') == 1861 || Session::get('registro') == 2465 || Session::get('registro') == 2734 || Session::get('registro') == '2717' || Session::get('registro') == 'yael' || Session::get('registro') == 'akira' || Session::get('registro') ==  2087){?>
		<li><a>Credenciales</a>
			<ul>
				<li><a href="<?=KUMBIA_PATH?>credenciales/actualizarDatos">Actualizar Datos</a></li>
				<li><a href="<?=KUMBIA_PATH?>credenciales/generarReporte">Generar Reporte</a></li>
				<li><a href="<?=KUMBIA_PATH?>credenciales/imprimirProvicional">Imprimir Provisional</a></li>
				<li><a href="<?=KUMBIA_PATH?>credenciales/subirfotos">Subir Fotos</a></li>
			</ul>
		</li>
	<?php }?>
	
	<?php if(Session::get('registro') == 1861 || Session::get('registro') == 2286  || Session::get('registro') == 1833){?>
		<li><a>Servicio Medico</a>
			<ul>
				<li><a href="<?=KUMBIA_PATH?>servicio_medico/index">Servicio Medico</a></li>
			</ul>
		</li>
	<?php }?>
	
	<?php if(Session::get('registro') == 1861 || Session::get('registro') == 8108){?>
		<li><a>Comentarios Alumnos</a>
		  <ul>
			<li><a href="<?= KUMBIA_PATH ?>ventanilla/comentariosAlumnos">Comentarios Alumnos</a></li>
		  </ul>
		</li>
	<?php }?>
	
	<?php
	if(Session::get("SERVICIOMEDICO") == "SERVICIOMEDICO" && Session::get('registro') != 1861){
		include("menu_servicio_medico.phtml");
	}
	?>
	<li class="floatright">
		<a href="<?=KUMBIA_PATH?>profesor/salir">
			<image src="<?=KUMBIA_PATH?>img/log_off.jpg" class="log_off" />
		</a>
	</li>
</ul>
