<ul>
	<li class="li_inicio"><a>Inicio</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Informaci&oacute;n</a></li>
		</ul>
	</li>

	<li><a>Horarios</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesoreshorario/horarioPorProfesor">Imprimir Horarios Profesor</a></li>
		</ul>
	</li>
	<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Administraci&oacute;n Alumnos</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/buscarAlumno">Buscar Alumno</a></li>
		</ul>
	</li>
	<li><a href="<?=KUMBIA_PATH?>profesor/informacion">Configuraci&oacute;n</a>
		<ul>
			<li><a href="<?=KUMBIA_PATH?>profesor/cambiarContrasena">Cambiar Contrase&ntilde;a</a></li>
		</ul>
	</li>
	<li class="floatright">
		<a href="<?=KUMBIA_PATH?>profesor/salir">
			<image src="<?=KUMBIA_PATH?>img/log_off.jpg" class="log_off" />
		</a>
	</li>
</ul>