<ul>
	<li class="li_inicio"><a href="<?=KUMBIA_PATH?>profesor/informacion">Informaci&oacute;n</a></li>
			
	<li><a href="<?=KUMBIA_PATH?>profesor/buscarAlumno">Buscar Alumno</a></li>
	
	<li><a href="<?=KUMBIA_PATH?>estadisticas/indicesReprobacionListado">Estad&iacute;sticas de Captura</a></li>
	
	<li><a href="<?=KUMBIA_PATH?>profesor/cambiarContrasena">Cambiar Contrase&ntilde;a</a></li>
	
	<li class="floatright">
		<a href="<?=KUMBIA_PATH?>profesor/salir">
			<image src="<?=KUMBIA_PATH?>img/log_off.jpg" class="log_off" />
		</a>
	</li>
</ul>