<tr>
    <th background="/ingenieria/public/img/cira/barraIng.jpg" class="barra_menu">
		<?= link_to('profesor/index','Entrar como Profesor') ?> <span style="color: rgb(242, 120, 34);">|</span> 
		<?= link_to('tutor/asignacion','Asignacion') ?> <span style="color: rgb(242, 120, 34);">|</span> 
		<?= link_to('tutor/busqueda','Busqueda') ?> <span style="color: rgb(242, 120, 34);">|</span> 
		<?= link_to('tutor/estadisticas','Estadisticas') ?> <span style="color: rgb(242, 120, 34);">|</span> 
		<?= link_to('profesor/buscarAlumno','Buscar Alumno') ?> <span style="color: rgb(242, 120, 34);">|</span> 
		<?= link_to('profesor/salir','Salir') ?>
    </th>
</tr>
<tr>
	<td height="1"></td>
</tr>
<tr>
	<td align="center">
		<?= content(); ?>
	</td>
</tr>