<script language="JavaScript1.2">
function validateFieldAreaDeFormacion(){
	var intersemestral = document.Formulario.elements['intersemestral'];
	var flag = 0;
	var radioLength = intersemestral.length;
	
	var err = "";
	for(var i = 0; i < radioLength; i++) {
		if(intersemestral[i].checked) {
			flag = 1;
		}
	}
	if (flag == 0){
		err+="Favor de especificar si desea tomar un intersemestral\n";
	}
	
	
	var idareadeformacion = document.Formulario.elements['idareadeformacion'];
	var flag2 = 0;
	var radioLength2 = idareadeformacion.length;
	
	for(var i = 0; i < radioLength2; i++) {
		if(idareadeformacion[i].checked) {
			flag2 = 1;
		}
	}
	if (flag2 == 0){	
		err+="Favor de especificar un Área de Formación desee tomar\n";
	}
	
	if (err.length != 0){
		alert (err);
		return false;
	}
	alert("¡Gracias por su cooperación!");
	return true;
}
</script>

<form action="<?= KUMBIA_PATH ?>alumnoselecc/guardandoAreaDeFormacion" 
	method = "post" onSubmit="return validateFieldAreaDeFormacion();" name="Formulario" id="Formulario">
	
<h2>ÁREAS DE FORMACIÓN DISPONIBLES DE SU CARRERA</h2><br />
Debido a que está apunto de empezar a tomar materias de Áreas de Formación,
favor de escojer un Área de Formación de acuerdo sus preferencias.<br /><br />
Esto servirá para poder realizar su preselección con la correcta seriación de su Area de Formación.<br /><br />
<div style="display: table; margin-left: auto; margin-right: auto; width: 950px; text-align: left; height: 200px;">
<?
	$i = 0;
	foreach( $posiblesAreasDeFormacion as $posibles ){
?>
		<div style="width: 220px; height: 20px; float: left; margin: 0px 3px 0px 3px;">
		<h2 align="center"><?= $posibles ?></h2><br />
<?
		foreach( $arrayConMateriasDeSuArea[$i] as $m ){
			echo substr($m, 0, 25).'<br />';
		}
		$i++;
?>
		 <input  type="radio" id="idareadeformacion" name="idareadeformacion" value="<? echo $i ?>" /><br />
	  </div>
<?
	}
?>
</div>
<input type="submit" value="Seleccionar"><br />
<br /><br />