<center><br><br>
<table align="center">
	<tr>
		<td width="750" align="left">
			<form method="POST" action="<?= KUMBIA_PATH ?>calculo/hacerConsultas2/" onSubmit="return validar(this);">
				<h3>Query a ejecutar</h3>
				<input type ="text" name="query" id ="query" size="90">
				<br />
				<br />
				<h3>Tablas, Ingrese las tablas separadas por coma y sin dejar espacios. Máximo 5 tablas.</h3>
				<input type ="text" name="tablas" id ="tablas" size="90">
				<br />
				<br />
				<input type ="submit">
			</form>
		</td>
	</tr>
</table>
<br><br>
</center>