<center><br><br>
<table align="center">
	<tr>
		<td width="750" align="left">
			<form method="POST" action="<?= KUMBIA_PATH ?>calculo/capturaCalculo/" onSubmit="return validar(this);">
				<h3>Ingresar el número de nómina del profesor para modificar sus cursos</h3>
				<input type ="text" name="nominaProf" id ="nominaProf">
				<br />
				<br />
				<input type ="submit">
			</form>
		</td>
	</tr>
</table>
<br><br>
</center>