<style type="text/css">	
	.infoalumno{
		text-align:justify;
		font-size:13px;
	}
	.infoalumno td{
		padding:0 10px 0 10px;
	}
	.infoalumno th{
		padding:0 10px 0 10px;
		font-size:14px;
	}
</style>
	
<center>
<table>
	<tr>
		<td width="750" bgcolor="#FFFFFF"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>MÓDULO DE EVALUACIÓN DOCENTE</b></div>
			<hr><br>
			<div style="font-size: 12px;">
			Este módulo es el encargado de diseñar, monitorear y calificar el proceso de evaluación docente, en el cual los alumnos desde su cuenta deberán evaluar a los profesores que les hayan impartido clases en determinado periodo escolar.
			<br><br>
			Este módulo ofrece a la administración poder diseñar el cuestionario de evaluación docente agregando, o eliminando preguntas como se desee, además podrám organizarse en rubros o aspectos a evaluar de cada uno de nuestros profesores. También podrán obtenerse diferentes estadísticas y reportes con los resultados obtenidos en la evaluación docente.
			</div>
		</td>
	</tr>
</table>
<br>
</center>