<center><br>
			<table border="1">
				<tr><th colspan="8" height="50" bgcolor="#0559B7" style="color:#ffffff">MODULO DE PROFESOR</th></tr>
				<tr>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64"  width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/informacion"><?= img_tag("profesores/avisos.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">INFORMACIÓN DEL ALUMNO</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">
							<tr>
								<th height="64" width="110">
									<a href="<?= KUMBIA_PATH ?>profesor/listas"><?= img_tag("profesores/listas.jpg","border: 0","width: 60","height: 60") ?></a>
								</th>
							</tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">LISTAS DE ASISTENCIA</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/horario"><?= img_tag("profesores/horario.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">HORARIO DEL PROFESOR</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/captura"><?= img_tag("profesores/capturar.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">CAPTURA DE CALIFICACIONES</div>
							</th></tr>
						</table>
					</th>
				</tr>
				<tr>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/evaluaciones"><?= img_tag("profesores/encuestas.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">TUTORADOS ASIGNADOS</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64"  width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/encuestas"><?= img_tag("profesores/evaluacion.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">ENCUESTAS DE INTERES</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/historico"><?= img_tag("profesores/historico.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">HISTORIAL Y ESTADISTICAS</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="125" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="64" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/salir"><?= img_tag("profesores/cerrar.jpg","border: 0","width: 60","height: 60") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">TERMINAR LA SESION</div>
							</th></tr>
						</table>
					</th>
				</tr>
			</table>
			</center><br>