<div class="menu">
	<a href="<?= KUMBIA_PATH ?>tgojefe/alumnos">Alumnos</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/profesores">Profesores</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/coordinadores">Coordinadores</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/materias">Materias</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/grupos">Grupos</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/horarios">Horarios</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/calificaciones">Calificaciones</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/apoyo">Apoyo Académico</a>
	&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgojefe/salir">Salir</a>
<div>