<?php $horas = array("7:00 - 7:55","7:55 - 8:50","9:30 - 10:25","10:25 - 11:20","11:20 - 12:15","12:15 - 13:10","13:10 - 14:05","14:05 - 15:00","15:00 - 15:55","15:55 - 16:50","16:50 - 17:45","17:45 - 18:40","18:40 - 19:35","19:35 - 20:30"); ?>
<table border="1" style="font-size:10px;" class="bordeazul">
						<th height="20" class="naranja" colspan="7">
							<?= utf8_encode($propietario) ?>
						</th>
						<tr>
							<td width="100" align="center" class="azul">&nbsp;</td>
							<th width="50" align="center" class="azul">Lun</th>
							<th width="50" align="center" class="azul">Mar</th>
							<th width="50" align="center" class="azul">Mie</th>
							<th width="50" align="center" class="azul">Jue</th>
							<th width="50" align="center" class="azul">Vie</th>
							<th width="50" align="center" class="azul">Sab</th>
						</tr>
						<?php for($i=0;$i<2;$i++){ ?>
						<tr>
							<th height="25" class="naranja"><?= $horas[$i] ?></th>
							<?php if(isset($jornada)) if(substr($jornada -> lunes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> lunes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> martes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> martes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> miercoles,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> miercoles,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> jueves,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> jueves,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> viernes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> viernes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> sabado,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> sabado,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
						</tr>
						<?php } ?>
						<tr>
							<th height="10" class="naranja">8:50 - 9:30</th>
							<th colspan="6" class="negro">RECESO</th>
						</tr>
						<?php for($i=2;$i<8;$i++){ ?>
						<tr>
							<th height="25" class="naranja"><?= $horas[$i] ?></th>
							<?php if(isset($jornada)) if(substr($jornada -> lunes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> lunes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> martes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> martes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> miercoles,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> miercoles,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> jueves,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> jueves,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> viernes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> viernes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> sabado,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> sabado,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
						</tr>
						<?php } ?>
					</table><br>
					<table border="1" style="font-size:10px;" class="bordeazul">
						<tr>
							<td width="100" align="center" class="azul">&nbsp;</td>
							<th width="50" align="center" class="azul">Lun</th>
							<th width="50" align="center" class="azul">Mar</th>
							<th width="50" align="center" class="azul">Mie</th>
							<th width="50" align="center" class="azul">Jue</th>
							<th width="50" align="center" class="azul">Vie</th>
							<th width="50" align="center" class="azul">Sab</th>
						</tr>
						<?php for($i=8;$i<14;$i++){ ?>
						<tr>
							<th height="25" class="naranja"><?= $horas[$i] ?></th>
							<?php if(isset($jornada)) if(substr($jornada -> lunes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> lunes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> martes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> martes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> miercoles,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> miercoles,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> jueves,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> jueves,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> viernes,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> viernes,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
							<?php if(isset($jornada)) if(substr($jornada -> sabado,$i*4,3) == "XXX") echo '<th>-</th>'; else echo '<th class="gris">'.substr($jornada -> sabado,$i*4,3).'</th>'; else echo "<th>-</th>"; ?>
						</tr>
						<?php } ?>
					</table>