<center>
	<table border="1" style="font-size: 10px;" bordercolor="#003399">
		<tr>
			<td width="75" height="20" class="naranja">&nbsp;Nomina: </td>
			<td width="50" class="gris">&nbsp;2306&nbsp;</td>
			<td width="75" class="naranja">&nbsp;Nombre: </td>
			<td width="300" class="gris">&nbsp;RAMIRO ALONSO VERA CONTRERAS&nbsp;</td>
			<td width="75" height="20" class="naranja">&nbsp;División: </td>
			<td class="gris">&nbsp;MANUFACTURA DE PLÁSTICOS&nbsp;</td>
		</tr>
	</table>
</center>