<script language="JavaScript">
function setIt( Objeto ){
	if( Objeto.value == "" && Objeto.name == "nombreAlumno" )
		Objeto.value = "Nombre Alumno";
	if( Objeto.value == "" && Objeto.name == "registroAlumno" )
		Objeto.value = "Registro Alumno";
}
function clearIt( Objeto ){
	if( Objeto.value == "Registro Alumno" || Objeto.value == "Nombre Alumno" )
		Objeto.value = "";
}

</script>

<br />

<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
	<tr>
		<th width="140" height="25" bgcolor="#FFCA5B">&nbsp;Nombre del alumno:</th>
		<th width="500" colspan="3" bgcolor="#EEEEEE" colspan="3">&nbsp;<?php echo $alumno -> vcNomAlu ?> (<?php echo $alumno -> miReg ?>)</th>
	</tr>
	<tr>
		<th width="140" height="25" bgcolor="#FFCA5B">&nbsp;Carrera:</th>
		<th width="300" bgcolor="#EEEEEE">&nbsp;<?php echo $carrera -> nombre ?>
			<? if( isset($areadeformacion) ) echo "en&nbsp;".htmlentities($areadeformacion -> nombreareaformacion); ?>
		</th>
		<th width="100" height="25" bgcolor="#FFCA5B">&nbsp;Plantel:</th>
		<th width="100" bgcolor="#EEEEEE">&nbsp;<?= $plantel ?></th>
	</tr>
</table>
<br />
<br />