<?php
if( ($j % 2) == 0 )
	$bg = "#EEEEEE";
else
	$bg = "#C3C3C3";
?>
<td width="50" height="25" bgcolor="<?php echo $bg ?>">
	<?php echo $alumno -> registro ?>
</td>
<td width="200" height="25" bgcolor="<?php echo $bg ?>">
	<?php echo $alumno -> vcNomAlu ?>
</td>
<td width="50" height="25" bgcolor="<?php echo $bg ?>">
	<?php echo $alumno -> periodo ?>
</td>
<td width="50" height="25" bgcolor="<?php echo $bg ?>">
	<?php echo $alumno -> descripcion ?>
</td>
<td width="50" height="25" bgcolor="<?php echo $bg ?>">
	<?php if( $alumno -> aun_con_problemas == 1 ) echo "No"; else echo "Si"; ?>
</td>
<td width="50" height="25" bgcolor="<?php echo $bg ?>">
	<?php echo $alumno -> creado_at ?>
</td>
<td width="50" height="25" bgcolor="<?php echo $bg ?>">
	<?php echo $alumno -> modificado_at ?>
</td>
<td width="50" align="center" bgcolor="<?= $bg ?>">
<?php
	echo form_remote_tag("ingcalculo/problema_alumno_eliminar","update: tr[".$j."]", "name: Formulariio".$j)
?>
	<input type="image" src="<?= KUMBIA_PATH ?>img/delete.gif" border="0" alt="Eliminar Problema"
	onClick="return preguntar_eliminar_kardex()">
	<input type="hidden" id="id_problema" name="id_problema"
			value="<?php echo $alumno -> id ?>">
	</form>
</td>
<td width="50" align="center" bgcolor="<?= $bg ?>">
<?php
	echo form_remote_tag("ingcalculo/problema_alumno_solucion","update: tr[".$j."]", "name: Formularioo".$j)
?>
	<input type="image" src="<?= KUMBIA_PATH ?>img/activar_desactivar.jpg" border="0" alt="Desactivar Problema" width="25">
	<input type="hidden" id="id_problema" name="id_problema"
			value="<?php echo $alumno -> id ?>">
	<input type="hidden" id="row" name="row"
			value="<?php echo $j ?>">
	</form>
</td>