<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" align="center">
	<tr>
		<td width="100" height="25" bgcolor="#FFCA5B"><b>&nbsp;Promedio: </b></td>
		<td width="100" bgcolor="#EEEEEE">&nbsp;<?echo $promedio; ?></td>
		<td width="100" height="25" bgcolor="#FFCA5B"><b>N&uacute;mero de<br />cr&eacute;ditos: </b></td>
		<td width="100" bgcolor="#EEEEEE">&nbsp;<?= $ncreditos ?></td>
	</tr>
</table>