<style type="text/css">
	.a a{
		color: #404040;
		background: #f27822;
		padding: 10px;
		font-weight: bold;
	}
</style>
<br /><br />
<table border="0" cellpadding="0" cellspacing="0" width="900" >
	<tr>
		<td style="font-family: Verdana;">

<div class="">

<br />
			<h1 class="centrar">Abrir Cupo</h1>
			<br />
			<h3 class="centrar">Para dar m&aacute;s espacio en el curso, sólo con dar clic en el radio button</h3>
			<form action="<?= KUMBIA_PATH ?>capturarcursos/masCupoEnCursosCyTExcel/"
				method="post" name="Formulario2" id="Formulario2">
			<input type="image" src="<?= KUMBIA_PATH ?>img/exportarexcel.jpg"
					width="55" title="Exportar a Excel" class="exportarExcel" />
			</form>
			<div id="notificacion"></div>
			<br />
			
			<?php
			
			$i = 0;
			foreach( $curso as $cur ) {
				echo "<div id= \"listadoCursos\">
					<input type=\"radio\" value=\"<?= $cur ?>\" id=\"cursoo".$cur."\" name=\"cursoo".$cur."\">&nbsp;".
					$cur." ".$materia[$i]." ".$matnombre[$i].
					" ".$nomina[$i]." ".$maestro[$i]." ".$cupo[$i]." ".$disponibilidad[$i].
					"</div>";
				$i++;
			}
			?>
			<br />
	<br />&nbsp;
		</td>
	</tr>
</table>
<br /><br />
</div>

<?
	foreach($curso as $cur){
		print "<script type=\"text/javascript\">
		new Event.observe(\"cursoo".$cur."\", \"click\", function(){
		new AJAX.viewRequest({
			action: \"capturarcursos/abriendoCupoEnCursos/".$cur."\",
			container: \"notificacion\"
		})
		})
		</script>";
	}
?>