<script language="javascript">  
function validar(){
	var F=document.getElementById("nuevaSituacion").value;
	var REF=document.getElementById("referencia").value;

if (REF=="" && F==1){
alert("Se debe poner referencia del tramite");
return false;
}
if (REF=="" && F==2){
alert("Se debe poner referencia del tramite");
return false;
}


}

</script>

<?= form_remote_tag("apoyo/guardarCambioEstado", "update: resultado") ?>
<table class="bordeAzul" style="font-size: 10px; width: 100%;">
	<tr class="naranja">
		<th colspan="8">INFORMACION DEL ALUMNO</th>		
	</tr>
	<tr class="azul">
		<th>Registro</th>
		<th width="250">Alumno</th>
		<th>Estado Actual</th>
		<th>Nuevo Estado</th>
		<th>Fecha del Movimiento</th>
		<th>Periodo</th>
		<th>Referencia</th>
		<th>&nbsp;</th>
	</tr>
	<tr class="grisClaro">
		<th><?= $alumno -> miReg ?></th>
		<th><?= $alumno -> vcNomAlu ?></th>
		<th><?php
		
			$HistorialAlumno = new HistorialAlumno();
			if($HistorialAlumno -> find_first("registro = ".$alumno -> miReg, "order by: id desc")){
			// if($HistorialAlumnoo -> find_first("registro = ".$alumno -> miReg, " order: id DESC")){
				$Situaciones = new Situaciones();
				$Situaciones -> find_first("id = ".$HistorialAlumno -> situacion_id);
//				$Situaciones -> find_first("id = 7");
				echo $Situaciones -> nombre;
			}else{
				echo $alumno -> stSit;
			}
			
		?>
		</th>
		<th><?php
		if($situaciones){
		?>
			<select name="nuevaSituacion" id="nuevaSituacion" class="lista">
		<?php
			
			foreach($situaciones as $s){			
				echo '<option value="'.$s -> id.'">'.$s -> nombre.'</option>';
			}					
		?>
			</select>
			<?php } ?>
		</th>
		<?php
		if($HistorialAlumno -> fecha != ''){
			$fecha = $HistorialAlumno -> fecha;
		}else{
			$day = date ("d");
			$month = date ("m");
			$year = date ("Y");
			$fecha = $year."-".$month."-".$day;
		}
		
		?>
		<th><input type="text" name="fecha" value="<?= $fecha ?>"></th>
		<th><input type="text" name="periodo" value="<?= $HistorialAlumno -> periodo ?>"></th>
		<th>
      <input name="referencia" type="text" id="referencia" size="20" /></th>
		<th>
			<input type="hidden" name="registro" value="<?= $alumno -> miReg?>">
			<input type="submit" value="GUARDAR" onclick="return validar()">
		</th>
	</tr>	
 </table>
 <br />
 <?= end_form_tag() ?>