<div class="menu">
	<a href="<?= KUMBIA_PATH ?>apoyo/index">Inicio</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;&nbsp;	
	<a href="<?= KUMBIA_PATH ?>apoyo/cambiarEstado">Cambiar Estado</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;&nbsp;	
	<a href="<?= KUMBIA_PATH ?>apoyo/becas">Becas</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;&nbsp;		
	<a href="<?= KUMBIA_PATH ?>apoyo/salir">Salir</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;&nbsp;	
<div>