<center>
<?php echo form_remote_tag("apoyo/guardarModificacion", "update: contenido") ?>
<table style="font-size: 10px;" width="90%">
	<tr>
		<td class="naranja">
			Asignar Recargo
		</td>
		<td class="azul">
			<select name="recargo">
				<option value="0">Sin Recargos</option>
				<option value="1">Recargo No. 1</option>
				<option value="2">Recargo No. 2</option>
				<option value="3">Recargo No. 3</option>
			</select>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="grisClaro">
			<center>			
				<input type="submit" value="Guardar">			
			<center>
		</td>
	</tr>
</table>
</form>
</center>