<?php
	$Periodo = new Periodos();
	$Periodo -> find_first("activo = 1");	
?>
<br/>
<center>
<table class="bordeAzul" style="font-size: 10px; width:600px;">
	<tr class="naranja">
		<td width="100">Periodo Activo</td>
		<td width="200" class="azul"><?= $Periodo -> periodo ?></td>
		<td rowspan="2" class="gris">
			<div id="modificacion">
			<center>
				<?php echo form_remote_tag("apoyo/modificacion", "update: modificacion") ?>
					<input type="submit" value="Cambiar Recargo">
				</form>			
		</center>
			</div>
		</td>
	</tr>
	<tr class="naranja">
		<td>Recargo</td>		
		<td class="azul">
			<?php 
			if($Periodo -> recargo == 0){
				echo "No hay Recargo para este Periodo";
			}else{
				echo "Recargo No.".$Periodo -> recargo;
			}
			 ?>						
		</td>
	</tr>		
</table>
</center>