<center>
	<table border="1" align="center">
		<tr>
			<br /> <br />
			<td class="naranjaa" width="50px">N&oacute;mina:&nbsp;</td>
			<td class="azull" width="50px"><?php echo $nomina ?></td>
			
			<td class="naranjaa" width="50px">Profesor:&nbsp;</td>
			<td class="azull"><?php echo $coordinador -> nombre ?></td>
			
			<td class="naranjaa" width="50px">Divisi&oacute;n:&nbsp;</td>
			<td class="azull" width="50px"><?php echo $division ?></td>
		</tr>
	</table>
</center>