<center>
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/capturaT"><? echo "Captura Tonala" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/cursosT"><? echo "Cursos Tonala" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/salonesT"><? echo "Salones Tonala" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/nuevoSalonT"><? echo "Nuevo Salon Tonala" ?></a>
			</td>
		</tr>
	</table>
</center>