<center>
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/captura"><? echo "Captura" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/cursos"><? echo "Cursos" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/salones"><? echo "Salones" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/nuevoSalon"><? echo "Nuevo Salon" ?></a>
			</td>
		</tr>
	</table>
</center>