<center>
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/cursos_intersemestrales"><? echo "Captura" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/cursos_intersemestrales_listado"><? echo "Cursos" ?></a>
			</td>
		</tr>
	</table>
</center>