<center><br><br>
<table>
	<tr>
		<td width="900" align="left">
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>Estado de la Apertura: </b></div>
			<br />
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
				<tr>
					<td width="800" bgcolor="#EEEEEE">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?
						echo $mensaje;
?>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<br><br>
</center>