<?= render_partial("info"); ?>

<br />
<br />
<?= render_partial("menucursos"); ?>
<br />
<br />
<table align="center">
	<tr>
		<td colspan="3" valign="center" class="encabezadoo">
		<?
			if( $exito == 1 ){
				echo "<h3>Curso creado exit&oacute;samente. La clave del curso es: ".$clavecursoo."</h3>";
			}
			if( $exito == 2 ){
				echo "<h3>Curso espejo creado exit&oacute;samente. La clave del curso es: ".$clavecursooespejo."</h3>";
			}
			if( $exito == 0 ){
				echo "<h3>Error:</h3>";
				echo "<h3>".$error."</h3>";
			}
		?>
		</td>
	</tr>
</table>
</table>