<center><br><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			<table border="1">
				<tr><th colspan="8" height="25" bgcolor="#1569c7" style="color:#e9ab17">MODULO DE PROFESOR</th></tr>
				<tr>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44"  width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/informacion"><?= img_tag("profesores/avisos.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">AVISOS</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/listas"><?= img_tag("profesores/listas.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">LISTAS</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/horario"><?= img_tag("profesores/horario.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">HORARIO</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/captura"><?= img_tag("profesores/capturar.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">CAPTURA</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44"  width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/encuestas"><?= img_tag("profesores/encuestas.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">ENCUESTAS</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/evaluaciones"><?= img_tag("profesores/evaluacion.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">EVALUACION</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/historico"><?= img_tag("profesores/historico.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">HISTORIAL</div>
							</th></tr>
						</table>
					</th>
					<th width="125" height="110" align="center" valign="center">
						<table cellspacing="0" cellpadding="0">	
							<tr><th height="44" width="110">
								<a href="<?= KUMBIA_PATH ?>profesor/salir"><?= img_tag("profesores/cerrar.jpg","border: 0","width: 40","height: 40") ?></a>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">&nbsp;</div>
							</th></tr>
							<tr><th>
								<div style="font-size:10px;">SALIR</div>
							</th></tr>
						</table>
					</th>
				</tr>
			</table><br><br>
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>SECCION DE EVALUACIONES: </b></div>
				<br>
				En esta sección se presentarán las evaluaciones que se realizan al personal academico a traves de la opinión de sus alumnos, por el momento esta sección esta en construcción, se les informa que próximamente será implementada.
				<br><br>
			</div>
		</div></td>
	</tr>
</table>
</center>