<center><br><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>SECCION DE HISTORIAL: </b></div>
				<br>
				Actulamente existe una base de datos que contiene información de los periodos escolares anteriores, con lo cual se puede presentar un archivo histórico, donde el profesor podrá comparar cada uno de estos periodos.
				<br><br>Por el momento esta sección esta en construcción, se les informa que próximamente será implementada, si fuera necesario tener esta información y no es mostrada aquí podrá solicitarla en el área de calculo.
				<br><br>
			</div>
		</div></td>
	</tr>
</table>
</center>