<center>
<table align="center">
	<tr>
		<td>
			<br />
			<div style="font-size: 14px;" align="center"><div style="color: #FF0000;"><b>CAPTURA DE CURSOS: </b></div>
			<br />
			<br />
			<br />
			<div style="width: 300px; height: 50px; float: left; margin-right: 5px; margin-left: 35px;">
				<a href="<?= KUMBIA_PATH ?>capturarcursos/captura">
					Abrir captura del plantel Colomos
				</a>
			</div>
			<div style="width: 300px; height: 50px; float: left; margin-right: 5px; margin-left: 3px;">
				<a href="<?= KUMBIA_PATH ?>capturarcursos/capturaT">
					Abrir captura del plantel Tonala
				</a>
			</div>
			<div style="width: 300px; float: left; margin-right: 5px; margin-left: 3px;">
				<a href="<?= KUMBIA_PATH ?>capturarcursos/cursos_intersemestrales">
					Abrir Captura Intersemestrales
				</a>
			</div>
		</td>
	</tr>
</table>
<br />
<br>
</center>