<?php header("content-disposition: attachment;filename=lista.xls"); ?>
<center><br><br>
<table>
	<tr>
		<td width="900">
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
				<tr>
					<td width="200" colspan="2" height="25" bgcolor="#FFCA5B"><b>&nbsp;Número de curso: </b></td>
					<td width="600" bgcolor="#EEEEEE" colspan="3">&nbsp;<?= $curso ?></td>
				</tr>
				<tr>
					<td width="200" colspan="2" height="25" bgcolor="#FFCA5B"><b>&nbsp;Profesor: </b></td>
					<td width="600" bgcolor="#EEEEEE" colspan="3">&nbsp;<?= $profesor ?> (<?= $nomina ?>)</td>
				</tr>
				<tr>
					<td width="200" colspan="2" height="25" bgcolor="#FFCA5B">&nbsp;<b>Materia: </b></td>
					<td width="600" bgcolor="#EEEEEE" colspan="3">&nbsp;<?= $materia ?> (<?= $clave ?>)</td>
				</tr>
			</table>
			<br>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
				<tr bgcolor="#FFCA5B">
					<th width="50" height="25">No.</th>
					<th width="100">Registro</th>
					<th width="300">Nombre del alumno</th>
					<th width="250">Especialidad</th>
					<th width="100">Situación</th>
				</tr>
				<?php foreach($alumnado as $a){ $i++; if($i%2==0){$bg = "#EEEEEE";}else{$bg = "#FFFFFF";} ?>
					<tr bgcolor="<?= $bg ?>">
						<td width="50" height="20" align="center"><?= $i ?></td>
						<td width="100" align="center"><?= $a["registro"] ?></td>
						<td width="300" align="center"><?= $a["nombre"] ?></td>
						<td width="250" align="center"><?= $a["especialidad"] ?></td>
						<td width="100" align="center"><?= $a["situacion"] ?></td>
					</tr>
				<?php } ?>
			</table>
		</td>
	</tr>
</table>
</center>