<style type="text/css">
	.a a{
		color: #404040;
		background: #f27822;
		padding: 10px;
		font-weight: bold;
	}
</style>
<br /><br />
<table border="0" cellpadding="0" cellspacing="0" width="900" >
	<tr>
		<td style="font-family: Verdana;">

<div class="">

<br />
			<h1 class="centrar">Abrir Cupo</h1>
			<br />
			<h3 class="centrar">Para dar m&aacute;s espacio en el curso, sólo con dar clic en el radio button</h3>
			<form action="<?= KUMBIA_PATH ?>capturarcursos/masCupoEnCursosCyTExcel/"
				method="post" name="Formulario2" id="Formulario2">
			<input type="image" src="<?= KUMBIA_PATH ?>img/exportarexcel.jpg"
					width="55" title="Exportar a Excel" class="exportarExcel" />
			</form>
			<div id="notificacion"></div>
			<h3>COLOMOS</h3>
			<table>
				<tr id="listadoCursos">
					<th>CLAVE CURSO</th>
					<th>CLAVE MATERIA</th>
					<th>NOMBRE MATERIA</th>
					<th>NOMINA PROF</th>
					<th>NOMBRE PROFESOR</th>
					<th>CUPO / DISPONIBILIDAD</th>
					<th>AUMENTAR / DISMINUIR</th>
				</tr>
			<?php
			foreach( $xccursos as $xcc ) {
			?>
				<tr id="listadoCursos">
					<td><?= $xcc->curso ?></td>
					<td><?= $xcc->materia ?></td>
					<td><?= $xcc->matnombre ?></td>
					<td><?= $xcc->nomina ?></td>
					<td><?= $xcc->nombre_profesor ?></td>
					<td id="cupo<?= $xcc->curso_id ?>" name="cupo<?= $xcc->curso_id ?>">
						<?= $xcc->cupo ?>&nbsp;/&nbsp;<?= $xcc->disponibilidad ?>
					</td>
					<td>
						<div style="float: left; margin-left: 15px;">
							<?= form_remote_tag("capturarcursos/aumentar_cupo_en_xccursos","update: cupo$xcc->curso_id", "name: Form$xcc->curso_id") ?>
								<input type="image" src="<?= KUMBIA_PATH ?>img/plus_button.gif" width="20px" />
								<input type="hidden" id="curso_id_plus" name="curso_id_plus" value="<?= $xcc->curso_id ?>" />
							</form>
						</div>
						<div style="float: right; margin-right:15px;">
							<?= form_remote_tag("capturarcursos/disminuir_cupo_en_xccursos","update: cupo$xcc->curso_id", "name: Formulario$xcc->curso_id") ?>
								<input type="image" src="<?= KUMBIA_PATH ?>img/less_button.gif" width="20px" />
								<input type="hidden" id="curso_id_less" name="curso_id_less" value="<?= $xcc->curso_id ?>" />
							</form>
						</div>
					</td>
				</tr>
				</tr>
			<?php
			}
			?>
			</table>
			
			<h3>TONALA</h3>
			<table>
				<tr id="listadoCursos">
					<th>CLAVE CURSO</th>
					<th>CLAVE MATERIA</th>
					<th>NOMBRE MATERIA</th>
					<th>NOMINA PROF</th>
					<th>NOMBRE PROFESOR</th>
					<th>CUPO / DISPONIBILIDAD</th>
					<th>AUMENTAR / DISMINUIR</th>
				</tr>
			<?php
			foreach( $xtcursos as $xcc ) {
			?>
				<tr id="listadoCursos">
					<td><?= $xcc->curso ?></td>
					<td><?= $xcc->materia ?></td>
					<td><?= $xcc->matnombre ?></td>
					<td><?= $xcc->nomina ?></td>
					<td><?= $xcc->nombre_profesor ?></td>
					<td id="cupo<?= $xcc->curso_id ?>" name="cupo<?= $xcc->curso_id ?>">
						<?= $xcc->cupo ?>&nbsp;/&nbsp;<?= $xcc->disponibilidad ?>
					</td>
					<td>
						<div style="float: left; margin-left: 15px;">
							<?= form_remote_tag("capturarcursos/aumentar_cupo_en_xtcursos","update: cupo$xcc->curso_id", "name: Form$xcc->curso_id") ?>
								<input type="image" src="<?= KUMBIA_PATH ?>img/plus_button.gif" width="20px" />
								<input type="hidden" id="curso_id_plus" name="curso_id_plus" value="<?= $xcc->curso_id ?>" />
							</form>
						</div>
						<div style="float: right; margin-right:15px;">
							<?= form_remote_tag("capturarcursos/disminuir_cupo_en_xtcursos","update: cupo$xcc->curso_id", "name: Formulario$xcc->curso_id") ?>
								<input type="image" src="<?= KUMBIA_PATH ?>img/less_button.gif" width="20px" />
								<input type="hidden" id="curso_id_less" name="curso_id_less" value="<?= $xcc->curso_id ?>" />
							</form>
						</div>
					</td>
				</tr>
				</tr>
			<?php
			}
			?>
			<br />
	<br />&nbsp;
		</td>
	</tr>
</table>
<br /><br />
</div>

<?
	foreach($curso as $cur){
		print "<script type=\"text/javascript\">
		new Event.observe(\"cursoo".$cur."\", \"click\", function(){
		new AJAX.viewRequest({
			action: \"capturarcursos/abriendoCupoEnCursos/".$cur."\",
			container: \"notificacion\"
		})
		})
		</script>";
	}
?>