<center>
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>asignarEspecialidad/alumnosSinEsp"><? echo "Alumnos Sin Especialidad" ?></a>
			</td>
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>asignarEspecialidad/alumnosConEsp"><? echo "Alumnos con Especialidad" ?></a>
			</td>
		</tr>
	</table>
</center>