<div class="alinearDerechaPaginacion">
<table align="center" cellspacing="4">
	<tr>
		<td colspan="2">
			<?= $numAlumnoConEsp ?> Alumnos con Especialidad Asignada
		</td>
	</tr>
	<tr>
		<td>
			&nbsp;Anterior&nbsp;
		</td>
		<td>
			Siguiente
		</td>
	</tr>
	<tr>
		<td align="center" class="azull2">
		<?= link_to_remote
			("asignarEspecialidad/alumnosConEspAjax/".$p1,
			'<img src="'.KUMBIA_PATH.'public/img/left.gif" border=0>',
				 "update: asignadoEsp"); ?>
		</td>
		<td align="center" class="azull2">
		<?= link_to_remote
			("asignarEspecialidad/alumnosConEspAjax/".$p2,
			'<img src="'.KUMBIA_PATH.'public/img/right.gif" border=0>',
				"update: asignadoEsp"); ?>
		</td>
	</tr>
</table>
</div>