<div id="encabezado">
<img src="<?= KUMBIA_PATH ?>public/img/adorno.gif">&nbsp;
	INGRESO AL SISTEMA DE CONTROL ESCOLAR<br />
 	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CETI Plantel Colomos
</div>
<br />
<br />
<div class="naranja" style="font-size: 13px; padding: 20px;">
<p style="font-weight: normal;">
Bienvenido <b>Ing. Juan Antonio González AréchigaRamíez Wiella</b> este es el sistema para buscar alumnos y 
profesores asi como para ingresar a sus cuentas respectivamente. A continuación un breve explicación de los mismos.</p>
<p>
<li>En la sección de buscar Alumnos se encontrara con un recuadro en el cual hay dos opciones para hacer la búsqueda, una colocando el
registro en el recuadro correspondiente; la otra es colocando el nombre o solo parte de el mismo. Esto le desplegara una sección justo dejaba
donde saldrán los resultados a la búsqueda correspondiente, en esta parte podrá observar que el nombre del alumno se encuentra de color azul, 
dando clic en este podrá ingresar al sistema como si fuera el mismo alumno, y poder consultar en tiempo real toda la información correspondiente 
que se proporciona en el sistema. Para poder regresar al modulo de dirección general será necesario dar clic en la parte donde dice 
"Volver a Modulo de Dirección General"</li>
</p>
<br />
<p>
<li>En la sección se divide en dos, la primera opción es la de seleccionar una división y presionar el botón de buscar, debajo de esta `parte se desplegara otro listado
en donde se colocara a todos los profesores que corresponden a esta división y se presionara el botón de imprimir para que muestre el PDF con la información solicitada, 
la segunda opción es la de buscar Profesores se encontrara con un recuadro en el cual hay dos opciones para hacer la búsqueda, una colocando el numero de nomina
en el recuadro correspondiente; una vez presionado el botón de buscar saldrá un listado con los resultados encontrados con la opción al lado para poder imprimir el horario del
Profesor correspondiente.</li>
</p>

</div>