<?php echo form_remote_tag("ingcalculo/corregirKardex2","update: mostrandoInfo", "name: FormularioCorregirKardex") ?>
<!-- <form action="<?php echo KUMBIA_PATH ?>ingcalculo/corregirKardex2" method="post" name="FormularioCorregirKardex" id="FormularioCorregirKardex"> -->
<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
	<tr>
		<th width="400" height="25" bgcolor="#FFCA5B">&nbsp;Clave y Nombre Materia</th>
		<th width="100" height="25" bgcolor="#FFCA5B">&nbsp;Periodo</th>
		<th width="200" height="25" bgcolor="#FFCA5B">&nbsp;Tipo de Ex&aacute;men</th>
		<th width="100" height="25" bgcolor="#FFCA5B">&nbsp;Promedio</th>
	</tr>
	<tr>
		<th width="400" bgcolor="#EEEEEE">
			<?php echo $materiaCorreccion -> clave ?>&nbsp;-&nbsp;
			<?php echo htmlentities($materiaCorreccion -> nombre) ?>
		</th>
		<th width="100" bgcolor="#EEEEEE">
			<input type="text" name="periodo" id="periodo" maxlength="5" size="5" value="<?php echo $materiaCorreccion -> periodo ?>" />
		</th>
		<th width="200" bgcolor="#EEEEEE">
			<select name="tipo_de_ex" id="tipo_de_ex">
				<option value="D" <?php if( $materiaCorreccion -> tipo_de_ex == "D" ) echo "SELECTED"; ?>>Ordinario (D)</option>
				<option value="E" <?php if( $materiaCorreccion -> tipo_de_ex == "E" ) echo "SELECTED"; ?>>Extraordinario (E)</option>
				<option value="T" <?php if( $materiaCorreccion -> tipo_de_ex == "T" ) echo "SELECTED"; ?>>Titulo de Suficiencia (T)</option>
				<option value="R" <?php if( $materiaCorreccion -> tipo_de_ex == "R" ) echo "SELECTED"; ?>>Regularizaci&oacute;n (R)</option>
				<option value="A" <?php if( $materiaCorreccion -> tipo_de_ex == "A" ) echo "SELECTED"; ?>>Acreditaci&oacute;n (A)</option>
				<option value="V" <?php if( $materiaCorreccion -> tipo_de_ex == "V" ) echo "SELECTED"; ?>>Revalidaci&oacute;n (V)</option>
				<option value="EQ" <?php if( $materiaCorreccion -> tipo_de_ex == "EQ" ) echo "SELECTED"; ?>>Equivalencia (EQ)</option>
				<option value="EG" <?php if( $materiaCorreccion -> tipo_de_ex == "EG" ) echo "SELECTED"; ?>>Examen Global (EG)</option>
				<option value="NIV" <?php if( $materiaCorreccion -> tipo_de_ex == "NIV" ) echo "SELECTED"; ?>>Nivelaci&oacute;n (NIV)</option>
				<option value="ACR" <?php if( $materiaCorreccion -> tipo_de_ex == "ACR" ) echo "SELECTED"; ?>>Acreditaci&oacute;n (ACR)</option>
				<option value="DP" <?php if( $materiaCorreccion -> tipo_de_ex == "DP" ) echo "SELECTED"; ?>>Derecho de Pasante (DP)</option>
				<option value="CO" <?php if( $materiaCorreccion -> tipo_de_ex == "CO" ) echo "SELECTED"; ?>>Convalidaci&oacute;n (CO)</option>
				<option value="I" <?php if( $materiaCorreccion -> tipo_de_ex == "I" ) echo "SELECTED"; ?>>Intersemestral (I)</option>
			</select>
		</th>
		<th width="100" bgcolor="#EEEEEE">
			<input type="text" name="promedio" id="promedio" maxlength="5" size="5" value="<?php echo $materiaCorreccion -> promedio ?>" />
		</th>
	</tr>
	<tr>
		<th width="100" bgcolor="#EEEEEE" colspan="4">
			<input type="hidden" name="kardexID" id="kardexID" value="<?php echo $materiaCorreccion -> id ?>" />
			<input type="hidden" name="registro" id="registro" value="<?php echo $materiaCorreccion -> registro ?>" />
			<input type="submit" value="Corregir Kardex" onClick="return preguntar_envio()" />
			<button type="button" id="cancelar" name="cancelar">&nbsp;&nbsp;Cancelar&nbsp;&nbsp;</button>
		</th>
	</tr>
</table>
</form>
<br />

<?php
print "<script type=\"text/javascript\">
new Event.observe(\"cancelar\", \"click\", function(){
new AJAX.viewRequest({
	action: \"ingcalculo/corrigiendoKardexContainer/\",
	container: \"mostrandoInfo\"
})
})
</script>";
?>