<form action="<?= KUMBIA_PATH ?>impresiones/imprimir_certificado/"
	method="post" name="Formulario2" id="Formulario2" target="_blank">
<input type="hidden" id="registroimprimir" name="registroimprimir" value="<?php echo $alumno -> miReg ?>"/>
<div class="imprimirkardex" style="color: #1569C7; font-weight:bold;">
Imprimir Certificado <input type="image" src="<?= KUMBIA_PATH ?>img/print.gif" title="Imprimr Certificado" />
</div>
</form>