<table align="center">
	<tr>
		<td width="900"><div align="justify">
			<br>
			<div style="font-size: 14px;"><div style="color: #1569C7;"><?= img_tag("adorno.gif","border: 0") ?><b>IMPRESION CERTIFICADO</b></div>
			<hr><br>
			<br>
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" align="center">
				<tr>
					<th width="150" height="25" bgcolor="#FFCA5B">&nbsp;Nombre del alumno:</th>
					<th width="300" colspan="5" bgcolor="#EEEEEE" colspan="3">
						&nbsp;<?= $alumno -> vcNomAlu ?> (<?= $alumno -> miReg ?>)</th>
					<td width="100" height="25" bgcolor="#FFCA5B"><b>&nbsp;Promedio: </b></td>
					<td width="100" bgcolor="#EEEEEE">&nbsp;<?echo $promedio; ?></td>
				</tr>
				<tr>
					<th width="150" height="25" bgcolor="#FFCA5B">&nbsp;Carrera:</th>
					<th width="300" bgcolor="#EEEEEE">&nbsp;<?= $carrera -> nombre ?>
						<? if( isset($areadeformacion) ) echo "en&nbsp;".utf8_encode($areadeformacion -> nombreareaformacion); ?>
					</th>
					<th width="50" height="25" bgcolor="#FFCA5B">&nbsp;Turno:</th>
					<td width="30" bgcolor="#EEEEEE" class="centrar"><?php echo $alumno -> enTurno ?></td>
					<th width="100" height="25" bgcolor="#FFCA5B">&nbsp;Plantel:</th>
					<th width="100" bgcolor="#EEEEEE">&nbsp;<?php if( strtoupper($alumno -> enPlantel) == "C" ) echo "Colomos"; else echo "Tonala"; ?></th>
					<td width="100" height="25" bgcolor="#FFCA5B"><b>Número de<br />cr&eacute;ditos: </b></td>
					<td width="100" bgcolor="#EEEEEE">&nbsp;<?= $ncreditos ?></td>
				</tr>
			</table>
	</tr>
</table>