<center><br><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>SECCION DE ENCUESTAS: </b></div>
				<br>
				En esta sección contestarás encuestas de interés que se realizen entre el personal académico, por el momento esta sección esta en construcción, pero será un punto importante para conocer la opinión e intereses del personal académico.
				<br><br>
			</div>
		</div></td>
	</tr>
</table>
</center>