<center><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>MODULO DE PROFESORES: </b></div>
				<br>
				Bienvenidos al nuevo modulo de profesores, el cual ofrece al personal académico una interfaz en la cual podrá consultar los grupos que tiene asignados, sus listas de asistencia, así como la posiblidad de capturar las calificaciones de sus alumnos.
				<br><br>
				Este nuevo modulo pretende mejorar la experiencia anterior en nuestro sistema de control escolar, cualquier comentario o sugerencia acerca de nuevo modulo, favor de comunicarlo al Departamento de Apoyo Académico.
			</div>
			<br>
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>CAPTURA DE CALIFICACIONES: </b></div>
				<br>
				El periodo de captura de calificaciones para el tercer parcial estará disponible para todos los profesores del nivel de Ingeniería en las siguientes fechas:
				<br><br>
				<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;">
					<tr><td bgcolor="#FFCA5B" width="150" height="20"><b>&nbsp;Inicio del periodo:</b></td><td width="200" height="20">&nbsp;Lunes, 23 de Junio del 2008</td></tr>
					<tr><td bgcolor="#FFCA5B" width="150" height="20"><b>&nbsp;Fin del periodo:</b></td><td width="200" height="20">&nbsp;Viernes, 27 de Junio del 2008</td></tr>
				</table>
				<br>
				Las calificaciones pueden capturarse o incluso corregirse dentro de ese rango de fechas, si por alguna razón no se hubiese capturado alguna calificación será necesario ponerse en contacto con el <b>Jefe del Departamento Estudios Nivel Licenciatura</b>
			</div>
		</div></td>
	</tr>
</table>
<br>
</center>