<style type="text/css">
	.barra_menu{
		color:#FFF; 
		font-family:Verdana; 
		font-size: 11px; 
		font-weight: bold;
		width:1000px; 
		height:30px;
	}
	.menu{
		background-color: #1569c7;
		height:32px;
	}
	.menu a{
		color:#FFF;
		width:199px; 
		padding: 10px 0 10px 0;
		text-decoration: none;
		display: block;
		float: left;
		border-right: 1px solid;
	}
	.menu a:hover{
		color:#000;		
		text-decoration: underline;
		background-color: #2244ff;
	}
	.naranja{
		background-color: #ffca5b;
	}
	.azul{
		background-color: #1569c7;
	}
	.gris{
		background-color: #BBBBBB;
	}
	.bordeazul{
		border: solid 1px #003399;
	}

	.bordeazul th{
		border: solid 1px #003399;
	}

	.bordeazul td{
		border: solid 1px #003399;
	}
	
</style>
<div class="menu">
	<center>
	<a href="<?= KUMBIA_PATH ?>administrador/index">Inicio</a>
	<a href="<?= KUMBIA_PATH ?>apoyo/cambiarEstado">Cambiar Estado</a>
	<a href="<?= KUMBIA_PATH ?>apoyo/becas">Becas</a>
	<a href="<?= KUMBIA_PATH ?>apoyo/salir">Salir</a>
	</center>
</div>