<div class="menu" align="center">
	<a href="<?= KUMBIA_PATH ?>administrador/index">Inicio</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>apoyo/cambiarEstado">Cambiar Estado</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>apoyo/becas">Becas</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>administrador/checarPagos">Checar Pagos</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>ventanilla/aspirantes">Aspirantes</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>ventanilla/checarEstado">Checar Estado del Alumno</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>ventanilla/checarContra">Contrase&ntilde;a del Alumno</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>administrador/buscarAlumno">Buscar Alumno</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>calificaciones/buscar">Ver Calificaciones</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>administrador/cambiar_contrasena">Cambiar Contrase&ntilde;a</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
	<a href="<?= KUMBIA_PATH ?>apoyo/salir">Salir</a>
	&nbsp;&nbsp;&nbsp;<span style="color:F27822">|</span>&nbsp;&nbsp;
</div>