		<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left"><b>CARRERAS DEL PLANTEL</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
						<br>
						Cada uno de nuestros planteles ofrece a los estudiantes diferentes carreras, las cuales estan presentadas en esta sección, si
						<br><br>
						<div style="color: #FF0000; font-size: 18px;" align="center"><b><?= $mensaje ?></b></div>
						<br>
						<div style="color: #FF0000; font-size: 18px;" align="center"><b><?= $plantel -> nombre ?></b></div>
						<br>
					</div>
					<div style="color: #000000; font-size: 11px;" align="center">
						<?php if($ingenieria) { ?>
						<table border="1" cellpadding="1" cellspacing="1" width="500">
							<tr>
								<th colspan="3" align="center" height="25" class="fondoazul">
									INGENIERIA
								</th>
							</tr>
							<tr>
								<th align="center" height="25" class="fondonaranja">
									Clave
								</th>
								<th align="center" height="25" class="fondonaranja">
									Nombre
								</th>
							</tr>
							
							<?php foreach($ingenieria  as $carrera){ $k++; if( $k % 2 == 0){ $bg="#FFFFFF"; } else{ $bg="#DDDDDD"; } ?>
							<tr>
								<th align="center" height="25" width="100" bgcolor="<?= $bg ?>">
									<?= $carrera -> clave ?>
								</th>
								<th align="left" height="25" width="400" bgcolor="<?= $bg ?>">
									&nbsp;<?= $carrera -> nombre ?>
								</th>
							</tr>
							<?php } ?>
						</table>
						<?php } ?>
						<?php if($tecnologo) { ?>
						<br>
						<table border="1" cellpadding="1" cellspacing="1" width="500">
							
							<tr>
								<th colspan="3" align="center" height="25" class="fondoazul">
									TECNOLOGO
								</th>
							</tr>
							<tr>
								<th align="center" height="25" class="fondonaranja">
									Clave
								</th>
								<th align="center" height="25" class="fondonaranja">
									Nombre
								</th>
							</tr>
							<?php foreach($tecnologo  as $carrera){ $k++; if( $k % 2 == 0){ $bg="#FFFFFF"; } else{ $bg="#DDDDDD"; } ?>
							<tr>
								<th align="center" height="25" width="100" bgcolor="<?= $bg ?>">
									<?= $carrera -> clave ?>
								</th>
								<th align="left" height="25" width="400" bgcolor="<?= $bg ?>">
									&nbsp;<?= $carrera -> nombre ?>
								</th>
							</tr>
							<?php } ?>
						</table>
						<?php } ?>
						<br>
						<table border="1" cellpadding="1" cellspacing="1" width="500">						
							<form action="<?= KUMBIA_PATH ?>administrador/agregarCarrera" method="POST">
							<tr>
								<th colspan="3" align="center" height="25" class="fondoazul">
									AGREGAR CARRERAS AL PLANTEL
								</th>
							</tr>
							<tr>
								<th align="center" height="70" bgcolor="<?= $bg ?>">
									<select name="carrera">
										<option value="">&nbsp;</option>
										<?php if($carreras) foreach($carreras as $carrera){ ?>
										
											<?php
												switch($carrera -> clavenivel){
													case 'I': echo '<option value="I'.$carrera -> clave.'">'; echo "INGENIERIA "; break;
													case 'T': echo '<option value="T'.$carrera -> clave.'">'; echo "TECNOLOGO EN "; break;
												}
											?><?= $carrera -> nombre ?>
										</option>
										<?php } ?>
								</select><br><br>
									<input type="submit" value="Agregar Carrera" class="boton">
									<input type="hidden" name="plantel" value="<?= $plantel -> clave ?>">
								</th>
							</tr>
							</form>
						</table>
					</div>
				</td>
			</tr>
		</table>
	
		<br><br>