		<table border="0" cellpadding="0" cellspacing="0" width="770">
			<tr>
				<td style="font-family: Verdana;">
					<br>
					<div style="color: #1569C7; font-size: 14px;" align="left">
					<?= img_tag("adorno.gif","border: 0") ?> <b>ASPIRANTES</b></div>
					<div style="color: #000000; font-size: 11px;" align="justify">
					<br>
						<center>
							<a href="img/imagen2.jpg">
								<?= img_tag("imagen2.jpg","border: 0", "width: 205", "height: 154") ?>
							</a>
							<a href="img/imagen1.jpg">
								<?= img_tag("imagen1.jpg","border: 0", "width: 205", "height: 154") ?>
							</a>
							<a href="img/imagen3.jpg">
								<?= img_tag("imagen3.jpg","border: 0", "width: 205", "height: 154") ?>
							</a>
						</center>
						<br><br>
						En esta página web encontrarás infomación académica, todos los procesos realizados por de Departamento de Apoyo Académico cunjuntamente con todo el personal académico.
						<br><br>
						Este sistema se define como un conjunto de elementos que conforman la estructura administrativa y académica del <b>Centro de Enseñanza Técnica Industrial</b>. Se encarga de operar todos los procesos tanto en la administración, como en la gestión acádemica. Así mismo, apoya en la generación, mantenimiento y el uso de la información.
						<br><br>
						Este es un proyecto que busca modernizar los procesos de administración y gestión con el objetivo de establecer mejoras en la calidad de los servicios ofrecidos por el Departamento de Apoyo Académico para los miembros de la institución y el público en general.
						<br><br>
						En este sistema podrá ser utilizado por alumnos, profesores, coordinadores, y administrativos, así como el público en general interesado en los servicios y programas académicos ofrecidos por nuestra institución.
						<br><br>
					</div>
				</td>
			</tr>
		</table>
		<input type="submit" value="ENTRAR AL SISTEMA" style="font-family: Verdana; font-size: 14px; background: #FFCA5B;">
		<br><br>