<div class="menu">
	<a href="<?= KUMBIA_PATH ?>modificaciones/index">Inicio</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>modificaciones/alumnos">Alumnos</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>modificaciones/calificaciones">Calificaciones</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>modificaciones/usuarios">Usuarios</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>modificaciones/tutorias">Tutorias</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>modificaciones/tickets">Tickets</a>
	&nbsp;<span style="color:F27822">|</span>&nbsp;
	<a href="<?= KUMBIA_PATH ?>tgoalumno/salir">Salir</a>
</div>