<center>
	<table border="1" align="center">
		<tr>
			<br /> <br />
			<td class="azull" width="150px"><a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesor/permitirCrucesColomos">Permitir cruces Colomos</a></td>
			
			<td class="azull" width="150px"><a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesor/permitirCrucesTonala">Permitir cruces Tonal&aacute;</a></td>
			
			<td class="azull" width="150px"><a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesor/permitirCrucesComunesC">Cursos en Com&uacute;n Colomos</a></td>
			
			<td class="azull" width="150px"><a class="linksobreazul" href="<?= KUMBIA_PATH ?>profesor/permitirCrucesComunesT">Cursos en Com&uacute;n Tonal&aacute;</a></td>
		</tr>
	</table>
</center>