<table>
	<tr class="naranja">
		<th class="bordeAzul2" colspan="17">
			Actividades Asignadas Actualmente
		</td>
	</tr>
	<tr class="naranja">
		<th class="bordeAzul2">Borrar</th>
		<th class="bordeAzul2">Editar</th>
		<th class="bordeAzul2">Actividad</th>
		<th class="bordeAzul2">Horas Estimadas</th>
		<th class="bordeAzul2">Objetivo</th>
		<th class="bordeAzul2">Meta</th>
		<th class="bordeAzul2">Periodo</th>
		<th class="bordeAzul2">% Avance 1</th>
		<th class="bordeAzul2">% Avance 2</th>
		<th class="bordeAzul2">% Avance 3</th>
		<th class="bordeAzul2">Fecha Creaci&oacute;n</th>
		<th class="bordeAzul2">Fecha &uacute;ltima modifiaci&oacute;n</th>
	</tr>
	<?
	if( isset($actividadMaestro) ){
	foreach( $actividadMaestro as $actividad ){
	?>
		<tr>
			<th class="bordeAzul2">
			<form action="<?= KUMBIA_PATH ?>profesor/borrandoActividad"
					method="post" onSubmit="return delete1();">
				<input type="image" src="<?= KUMBIA_PATH ?>img/delete2.gif"
					border="0" onClick="return eliminar()" alt="Eliminar Actividad">
				<input type="hidden" id="deleteID" name="deleteID" onClick="return eliminar()"
						value="<? echo $actividad -> id; ?>">
			</form>
			</th>
			<th class="bordeAzul2">
			<?= form_remote_tag("profesor/editarActividad","update: editarActividad", "name: Formulario0") ?>
				<input type="image" src="<?= KUMBIA_PATH ?>img/edit.gif" border="0" alt="Editar Actividad">
				<input type="hidden" id="editID" name="editID"
						value="<? echo $actividad -> id; ?>">
			</form>
			</th>
			<th class="bordeAzul2"><?= $actividad -> actividad ?></th>
			<th class="bordeAzul2"><?= $actividad -> horas ?></th>
			<th class="bordeAzul2"><?= $actividad -> objetivo ?></th>
			<th class="bordeAzul2"><?= $actividad -> meta ?></th>
			<th class="bordeAzul2"><?= $actividad -> periodo ?></th>
			<th class="bordeAzul2"><?= $actividad -> avance1 ?></th>
			<th class="bordeAzul2"><?= $actividad -> avance2 ?></th>
			<th class="bordeAzul2"><?= $actividad -> avance3 ?></th>
			<th class="bordeAzul2"><?= $actividad -> creado_at ?></th>
			<th class="bordeAzul2"><?= $actividad -> modificado_in ?></th>
		</tr>
	<?
	}
	}
	?>
</table>