<?php
	echo "<h3>Debido a que por normatividad (Manual de la función docente DI-MN-200-04-04 REVB<br />
	Capitulo I Inciso 1.2.1.3 y Capitulo IV Inciso 4.3) el docente de Asignatura";
	echo " participa<br />en el programa de tutorías del plantel usted podrá asignarse máximo dos horas <br />
	a esta actividad, está actividad es opcional para los profesores de asignatura.</h3>";
	echo "<h4 class='letraRoja'>Horas de Tutoría: <input type='text' value='2' name='horasTutorias' 
		id='horasTutorias' onChange='validarHorasTutoriasAsignatura()' maxlength='1' size='1' /></h4>";
?>