<br />
<br />
<?= render_partial("menuestadisticas"); ?>
<br />
<br />

<center>
	<table border="1" align="center">
		<tr>
			<br />
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>estadisticas/indicesReprobacionListado"><? echo "Listado" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/indicesReprobacionCurso"><? echo "Por Curso" ?></a>
			</td>
			
			<td class="azull2" width="150px" align="center">
				<a class="linksobreazul" href="<?= KUMBIA_PATH ?>capturarcursos/indicesReprobacionMateria"><? echo "Por Materia" ?></a>
			</td>
			
		</tr>
	</table>
</center>