<center><br><br>
<form action="<?= KUMBIA_PATH ?>profesor/cambiandoContrasenaZopilote" method="post">
<table>
	<tr>
		<td width="900" align="left">
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" align="center">
				<tr>
					<td width="500" height="25" bgcolor="#FFCA5B" align="center">
						<h2>&nbsp;Cambiar contrase&ntilde;a de Zopilote:</h2>
					</td>
				</tr>
			</table>
			<br />
			<p class="letraRoja11px centrar">Ahora la contrase&ntilde;a Zopilote s&oacute;lo servir&aacute; para entrar como alumno y NO como profesor</p>
			<p class="letraRoja11px centrar">Su contrase&ntilde;a Zopilote ha cambiado, favor de cambiarla a la brevedad posible.</p>
			<br />
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" align="center" >
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">Nombre del profesor:</th>
					<th width="250" align="center"><?= $maestro -> nombre ?></th>
				</tr>
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">N&oacute;mina:</th>
					<th width="250" align="center"><?= $maestro -> nomina ?></th>
				</tr>
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">Contrase&ntilde;a Actual:</th>
					<th width="250" align="center"><?= $login -> pwd ?></th>
				</tr>
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">Nueva Contrase&ntilde;a:</th>
					<th width="250" align="center">
						<input type="text" name="contrasena" id="contrasena">
					</th>
				</tr>
				<tr bgcolor="#FFCA5B">
					<td colspan="2" align="center">
							<input type="hidden" value="<?= $login -> login ?>" id="login" name="login">
							<input type="submit" value="Cambiar Contrase&ntilde;a" >
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</form>
<br><br>
</center>