<div id ="centrar">
	<h2 class="letraRoja">
		<?
		switch($vacia){
			case 1: echo "Favor de ingresar un email"; break;
			case 2: echo "La direcci&oacute;n de email es incorrecta"; break;
		}
		?>
	</h2>
<br />
</div>
<center>
<form action="<?= KUMBIA_PATH ?>profesor/cambiandoCorreo" method="post">
<table>
	<tr>
		<td width="900" align="left">
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" align="center">
				<tr>
					<td width="500" height="25" bgcolor="#FFCA5B" align="center">
						<h2>&nbsp;Cambiar correo:</h2>
					</td>
				</tr>
			</table>
			<br />
			<br />
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" align="center" >
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">Nombre del profesor:</th>
					<th width="250" align="center"><?= $maestro -> nombre ?></th>
				</tr>
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">N&oacute;mina:</th>
					<th width="250" align="center"><?= $maestro -> nomina ?></th>
				</tr>
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">Correo Actual:</th>
					<th width="250" align="center"><?= $maestro -> correo ?></th>
				</tr>
				<tr>
					<th width="250" height="25" bgcolor="#FFCA5B" align="center">Nuevo Correo:</th>
					<th width="250" align="center">
						<input type="text" name="correo" id="correo">
					</th>
				</tr>
				<tr bgcolor="#FFCA5B">
					<td colspan="2" align="center">
							<input type="submit" value="Cambiar Contrase&ntilde;a" >
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</form>
<br><br>
</center>