<script language="JavaScript">
	var nav4 = window.Event ? true : false;
	function acceptNum(evt){   
		if(evt.keyCode==112) evt.keyCode = 80;
		if(evt.keyCode==110) evt.keyCode = 78;
		var key = evt.keyCode;   
		return (key == 80 || key == 78 || key == 112 || key == 110 || key <= 13 || (key>= 48 && key <= 57));
	}
</script>
<script type='text/javascript'>
function validar( formulario ) {
  	<?php foreach($alumnado as $a){ ?>
  	if (formulario.faltas<?= $a["id"] ?>.value >= 0 && formulario.faltas<?= $a["id"] ?>.value <= 100) {
		if(formulario.faltas<?= $a["id"] ?>.value == ""){
			formulario.faltas<?= $a["id"] ?>.value = 0;
		}
  	} else {
    	alert("Error en el número de faltas del alumno, tendrás que utilizar un número entre 0 y 100");
		formulario.faltas<?= $a["id"] ?>.focus();
    	return false;
  	}
  	if (formulario.calificacion<?= $a["id"] ?>.value >= 0 && formulario.calificacion<?= $a["id"] ?>.value <= 100 && formulario.calificacion<?= $a["id"] ?>.value != "") {

  	} else {
  		if (formulario.calificacion<?= $a["id"] ?>.value == "NP" || 
				formulario.calificacion<?= $a["id"] ?>.value == "np" || 
					formulario.calificacion<?= $a["id"] ?>.value == "nP" || 
						formulario.calificacion<?= $a["id"] ?>.value == "Np" ){
		// || formulario.calificacion<?= $a["id"] ?>.value == "PD" || formulario.calificacion<?= $a["id"] ?>.value == "pd" || formulario.calificacion<?= $a["id"] ?>.value == "pD" || formulario.calificacion<?= $a["id"] ?>.value == "Pd"){

  		}
  		else{
  			alert("La calificación de un alumno debe estar en entre 0 y 100");
			formulario.calificacion<?= $a["id"] ?>.focus();
    		return false;
  		}
  	}
  	<?php } ?>
}
</script>
<center><br><br>
<table>
	<tr>
		<td width="900" align="left">
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 11px;" >
				<tr>
					<td width="200" height="25" bgcolor="#FFCA5B"><b>&nbsp;Número de curso: </b></td>
					<td width="600" bgcolor="#EEEEEE">&nbsp;<?= $curso ?></td>
				</tr>
				<tr>
					<td width="200" height="25" bgcolor="#FFCA5B"><b>&nbsp;Profesor: </b></td>
					<td width="600" bgcolor="#EEEEEE">&nbsp;<?= $profesor ?> (<?= $nomina ?>)</td>
				</tr>
				<tr>
					<td width="200" height="25" bgcolor="#FFCA5B">&nbsp;<b>Materia: </b></td>
					<td width="600" bgcolor="#EEEEEE">&nbsp;<?php echo $materia -> nombre ?> (<?php echo $materia -> clave ?>)</td>
				</tr>
			</table>
			<br><center><b>
			</b><center><div align="justify" style="font-size: 11px;">Las calificaciones deber&aacute;n
			estar en un rango entre <b>0 y 100</b>, en el caso de que el alumno no merezca calificación
			podra utilizar <b>NP</b>, no podr&aacute; capturar calificaciones como NR (No reportadas). 
			Deberá además capturar las faltas que tuvo cada alumno.</div><br />
			<form method="POST" action="<?= KUMBIA_PATH ?>profesor/capturar_intersemestral" 
					onSubmit="return validar(this);" name="Formulario1" id="Formulario1">
			<table border="1" cellpadding="1" cellspacing="1" bordercolor="#FF6633" style="font-size: 10px;" >
				<tr bgcolor="#FFCA5B">
					<th width="50" height="50" rowspan="2"  align="center">No.</th>
					<th width="75" rowspan="2" align="center">Registro</th>
					<th width="300" rowspan="2" align="center">Nombre del alumno</th>
					<th width="100" colspan="2" align="center">Calificaci&oacute;n</th>
					<div></div>
				</tr>
				<tr bgcolor="#FFCA5B">
					<th width="50" height="25" align="center">F</th>
					<th width="50" align="center">CAL</th>
					<div></div>
				</tr>
				<?php
				$i = 0;
				foreach($alumnado as $a){
					$i++;
					if($i%2==0)
						$bg = "#EEEEEE";
					else
						$bg = "#FFFFFF";
				?>
					<tr bgcolor="<?= $bg ?>">
						<td width="50" height="25" align="center"><?= $i ?></td>
						<td width="75" align="center"><?= $a["registro"] ?></td>
						<td width="300" align="center"><?= $a["nombre"] ?></td>
						
						<th width="50">
								<input type="text" name="faltas<?= $a["id"] ?>"
								size="3" value="<?= $a["faltas"] ?>" style="text-align: center;" 
								maxlength="2" OnKeyPress="return acceptNum(event)" />
						</th>
						<th width="50">
								<input type="text" name="calificacion<?= $a["id"] ?>"
								size="3" value="<?= $a["calificacion"] ?>" style="text-align: center;"
								maxlength="3" OnKeyPress="return acceptNum(event)" />
						</th>
					</tr>
				<?php
				}
				?>
			</table>
			<input type="hidden" name="parcial" value="<?= $parcialito ?>">
			<input type="hidden" name="curso" id="curso" value="<?php echo $curso ?>" />
			<br><input type="submit" value="GUARDAR CALIFICACIONES" style="color: #000000;background: #FFCA5B;">
			</form>
			<form method="POST" action="<?= KUMBIA_PATH ?>profesor/captura">
				<input type="submit" value="CANCELAR" style="color: #000000;background: #FFCA5B;">
			</form>
		</td>
	</tr>
</table>
</center>