<center><br><br>
<table>
	<tr>
		<td width="900"><div align="justify">
			
			<div style="font-size: 14px;"><div style="color: #FF0000;"><b>CURSOS QUE PERTENECEN A ESTA COORDINACION: </b></div>
				<br>
				Los cursos listados a continuación son aquellos en los que se imparte alguna materia de la coordinación de <b><?= $coordinacion ?></b>. Estos cursos solo podrán ser modificados en el periodo de captura por el coordinador correspondiente o en su defecto el jefe de nivel o el personal de calculo. (21 de Julio - 26 de Julio).
				<br><br>
				<center>
				<table border="0" cellpadding="0" cellspacing="0" width="400">
					<tr>
						<td><a href="<?= KUMBIA_PATH ?>profesor/cgrupos" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('coordinador_r1_c3','','<?= KUMBIA_PATH ?>/public/img/coordinador/coordinador_r1_c3_f2.gif',1);"><img name="coordinador_r1_c3" src="<?= KUMBIA_PATH ?>/public/img/coordinador/coordinador_r1_c3.gif" width="100" height="30" border="0" id="coordinador_r1_c3" alt="" /></a></td>
						<td><a href="<?= KUMBIA_PATH ?>profesor/csalones" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('coordinador_r1_c4','','<?= KUMBIA_PATH ?>/public/img/coordinador/coordinador_r1_c4_f2.gif',1);"><img name="coordinador_r1_c4" src="<?= KUMBIA_PATH ?>/public/img/coordinador/coordinador_r1_c4.gif" width="100" height="30" border="0" id="coordinador_r1_c4" alt="" /></a></td>
					</tr>
				</table>
				<?php if($error==1){ ?>
					<br><br><font color="#FF0000"><b>ERROR EN LA CAPTURA: </b></font>Existe un cruce de horarios.
				<?php } ?>
					<br>
				<form action="<?= KUMBIA_PATH ?>profesor/cmodificargrupo" method="POST">
				<input type="hidden" name="idcurso" value="<?= $curso ?>">
				<table border="1" cellspacing="1" cellpadding="1" style="font-size: 10px;">
					<tr>
						<th width="300" class="fondoazul" align="center" height="20" colspan="2">
							<b>Materia</b>
						</th>
						<th width="50" class="fondoazul">
							<b>Cupo</b>
						</th>
						<th colspan="6" class="fondoazul">
							Horario
						</th>
					</tr>
					<tr>
						<th width="300" class="fondonaranja" height="20">
							<?php
								if($xmateria!=""){
									echo $xmateria;
									?>
									<input type="hidden" name="materia" value="<?= $xclave ?>">
									<?php
								}
								else{
							?>
							<select name="materia" style="font-size:9px;" onChange="modificaMateria(<?= $curso ?>,this);" DISABLED>
							<option value="">&nbsp;</option>
								<?php foreach($xmaterias as $materia){ if($materia -> clave != ""){ ?>
									<option value="<?= $materia -> clave ?>"><?= $materia -> clave ?> - <?= $materia -> nombre ?></option>
								<?php  } } ?>
							</select>
							<?php } ?>
						</th>
						<th width="20" class="fondonaranja">
							<img src="<?= KUMBIA_PATH ?>public/img/edit.gif" border="0" width="15" height="15">
						</th>
						<th width="50" class="fondonaranja">
							<select name="cupo" style="font-size:9px;" DISABLED>
								<?php for($i=10;$i<=50;$i++){ ?>
									<?php if($i == $xcurso -> cupo){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							Lunes
						</th>
						<th width="30" class="fondonaranja">
							<select name="lunesi" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=15;$i<=21;$i++){ ?>
									<?php if($i == $xcurso -> lunesi){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="lunesf" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=16;$i<=22;$i++){ ?>
									<?php if($i == $xcurso -> lunesf){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="luness" style="font-size:9px;" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($xsalones) foreach($xsalones as $salon){ ?>
									<?php if($salon -> id == $xcurso -> luness){ ?>
										<option value="<?= $salon -> id ?>" SELECTED><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } else { ?>
										<option value="<?= $salon -> id ?>"><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
					</tr>
					<tr>
						<th width="300" class="fondoazul" colspan="2">
							<b>Profesor</b>
						</th>
						<th width="50" class="fondoazul">
							<b>Mínimo</b>
						</th>		
						<th width="30" class="fondonaranja">
							Martes
						</th>
						<th width="30" class="fondonaranja">
							<select name="martesi" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=15;$i<=21;$i++){ ?>
									<?php if($i == $xcurso -> martesi){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="martesf" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=16;$i<=22;$i++){ ?>
									<?php if($i == $xcurso -> martesf){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="martess" style="font-size:9px;" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($xsalones) foreach($xsalones as $salon){ ?>
									<?php if($salon -> id == $xcurso -> martess){ ?>
										<option value="<?= $salon -> id ?>" SELECTED><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } else { ?>
										<option value="<?= $salon -> id ?>"><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
					</tr>
					<tr>
						<th width="300" class="fondonaranja">
							<?php
								if($xmaestro!=""){
									echo $xmaestro;
									?>
									<input type="hidden" name="maestro" value="<?= $xnomina ?>">
									<?php
								}
								else{
							?>
							<select name="maestro" style="font-size:9px;" onChange="modificaMaestro('<?= $xclave ?>',this);" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($maestros){ ?>
									<option value="9999">MAESTRO POR DESIGNAR</option>
								<?php foreach($maestros as $maestro){ ?>
									<option value="<?= $maestro -> nomina ?>"><?= $maestro -> paterno ?> <?= $maestro -> materno ?> <?= $maestro -> nombre ?></option>
								<?php } } ?>
							</select>
							<?php } ?>
						</th>
						<th width="20" class="fondonaranja">
							<img src="<?= KUMBIA_PATH ?>public/img/edit.gif" border="0" width="15" height="15">
						</th>
						<th width="50" class="fondonaranja">
							<select name="minimo" style="font-size:9px;" DISABLED>
								<?php for($i=10;$i<=50;$i++){ ?>
									<?php if($i == $xcurso -> minimo){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							Miercoles
						</th>
						<th width="30" class="fondonaranja">
							<select name="miercolesi" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=15;$i<=21;$i++){ ?>
									<?php if($i == $xcurso -> miercolesi){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="miercolesf" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=16;$i<=22;$i++){ ?>
									<?php if($i == $xcurso -> miercolesf){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="miercoless" style="font-size:9px;" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($xsalones) foreach($xsalones as $salon){ ?>
									<?php if($salon -> id == $xcurso -> miercoless){ ?>
										<option value="<?= $salon -> id ?>" SELECTED><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } else { ?>
										<option value="<?= $salon -> id ?>"><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
					</tr>
					<tr>
						<th class="fondonaranja" rowspan="3" colspan="3">
							
						</th>
						<th width="30" class="fondonaranja">
							Jueves
						</th>
						<th width="30" class="fondonaranja">
							<select name="juevesi" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=15;$i<=21;$i++){ ?>
									<?php if($i == $xcurso -> juevesi){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="juevesf" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=16;$i<=22;$i++){ ?>
									<?php if($i == $xcurso -> juevesf){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="juevess" style="font-size:9px;" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($xsalones) foreach($xsalones as $salon){ ?>
									<?php if($salon -> id == $xcurso -> juevess){ ?>
										<option value="<?= $salon -> id ?>" SELECTED><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } else { ?>
										<option value="<?= $salon -> id ?>"><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
					</tr>
					<tr>
						<th width="30" class="fondonaranja">
							Viernes
						</th>
						
						<th width="30" class="fondonaranja">
							<select name="viernesi" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=15;$i<=21;$i++){ ?>
									<?php if($i == $xcurso -> viernesi){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="viernesf" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=16;$i<=22;$i++){ ?>
									<?php if($i == $xcurso -> viernesf){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="vierness" style="font-size:9px;" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($xsalones) foreach($xsalones as $salon){ ?>
									<?php if($salon -> id == $xcurso -> vierness){ ?>
										<option value="<?= $salon -> id ?>" SELECTED><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } else { ?>
										<option value="<?= $salon -> id ?>"><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
					</tr>
					<tr>
						<th width="30" class="fondonaranja">
							Sábado
						</th>
						
						<th width="30" class="fondonaranja">
							<select name="sabadoi" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=15;$i<=21;$i++){ ?>
									<?php if($i == $xcurso -> sabadoi){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="sabadof" style="font-size:9px;" DISABLED>
								<option value="" SELECTED>&nbsp;</option>
								<?php for($i=16;$i<=22;$i++){ ?>
									<?php if($i == $xcurso -> sabadof){ ?>
										<option value="<?= $i ?>" SELECTED><?= $i ?></option>
									<?php } else { ?>
										<option value="<?= $i ?>"><?= $i ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
						<th width="30" class="fondonaranja">
							<select name="sabados" style="font-size:9px;" DISABLED>
							<option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
								<?php if($xsalones) foreach($xsalones as $salon){ ?>
									<?php if($salon -> id == $xcurso -> sabados){ ?>
										<option value="<?= $salon -> id ?>" SELECTED><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } else { ?>
										<option value="<?= $salon -> id ?>"><?= $salon -> edificio ?>:<?= $salon -> nombre ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</th>
					</tr>
				</table>
				</form>
				
				<br>
				</center>
				<br>
			</div>
		</div></td>
	</tr>
</table>
</center>